export const ARABIC_CONFIG = {
  name: 'Arabic',
  prefix: 'ARB',
  category: 'arts',
  priority: 11,
  totalQuestions: 40,
  topics: {
    'COMPREHENSION': {
      subtopics: [
        'It consists of a passage of seventy (70) words.',
        'Five multiple-choice questions are to be set on the passage.',
        'The contents should be within the experience of the candidates e.g. current affairs, sports, education, politics, economy, health, culture and ethics.',
      ],
      objectives: [
        'use appropriate words or phrases for specific thought;',
        'deduce the lesson in the passage;',
        'determine the main theme of the passage;',
        'give an appropriate title to the passage;',
        'interpret the meanings of particular words.',
      ],
    },
    'TRANSLATION': {
      subtopics: [
        'This section consists of ten (10) questions.',
        'Five of them are on translation from English into Arabic while the other five are on translation from Arabic into English.',
        'Translation into English includes key words and phrases in a sentence.',
        'Translated questions are to be based on standard Arabic and English usages.',
      ],
      objectives: [
        'use an appropriate Arabic word or phrase to convey the meaning of an English word or phrase;',
        'determine an appropriate English word or phrase for an Arabic statement;',
        'interpret idiomatic expressions in both Arabic and English;',
        'transfer ideas expressed in Arabic to English and vice versa;',
        'communicate effectively in Arabic and English.',
      ],
    },
    'GRAMMAR': {
      subtopics: [
        'أسماء اإلشارة والموصولة والشرط واالستفهام.',
        'Demonstrative, relative pronouns, conditional and interrogative.',
        'المذكر والمؤنث.',
        'Gender (Masculine and Feminine).',
        'عالمات االسم.',
        'Characteristics of noun.',
        'المثنى.',
        'Dual.',
        'الجموع:',
        'جمع المذكر السالم.',
        'sound masculine plural',
        'جمع المؤنث السالم',
        'sound feminine plural',
        'جمع التكسير',
        'broken plural',
        'المضاف والمضاف إليه.',
        'Construct phrase.',
        'الضمائر المنفصلة و المتصلة',
        'Separable and inseparable pronouns.',
        'التوابع:',
        'النعت.',
        'adjective.',
        'العطف.',
        'conjunction.',
        'البدل.',
        'the permutative.',
        'التوكيد.',
        'emphasis.',
        'حروف الجر والنصب والجزم',
        'Prepositions.',
        'الفعل الالزم والفعل المتعدي.',
        'Transitive & Intransitive verbs.',
        'الفعل الماضي',
        'The perfect verb.',
        'فعل المضارع:',
        'المرفوع.',
        'the indicative.',
        'المنصوب.',
        'the subjunctive.',
        'المجزوم.',
        'the jussive.',
        'فعل األمر.',
        'The imperative verb.',
        'النواسخ:',
        'كان و أخواتها',
        'Kana and its associates',
        'إن و أخواتها',
        'Inna and its associates',
        'ظن و أخواتها',
        'Zanna and its associates',
        'الفعل الثالثي المجرد و المزيد فيه.',
        'Trilateral and derived verb.',
        'المصدر.',
        'Verbal noun.',
        'المشتقات:',
        'اسم الفاعل.',
        'active participle.',
        'اسم المفعول.',
        'passive participle.',
        'اسم التفضيل.',
        'comparative/superlative.',
        'اسم اآللة.',
        'noun of instrument.',
        'اسما الزمان و المكان.',
        'nouns of time and place.',
        'اسم النسبة.',
        'relative adjective.',
        'اسم المبالغة',
        'hyperbole noun.',
        'الجملة الشرطية',
        'Conditional sentence.',
        'العدد )1 – 1000 فقط(',
        'Numeral (1 – 1000).',
        'الفاعل و نائب الفاعل.',
        'Active and passive voice.',
        'المبتدأ والخبر.',
        'Subject and predicate.',
        'منصوبات األسماء:',
        'المفعول به.',
        'direct object.',
        'المفعول فيه )ظرف(.',
        'adverbs of place and time.',
        'الحال.',
        'adverb of circumstance.',
        'المستثنى بإال.',
        'the exempted with illa.',
        'التمييز.',
        'the specification.',
        'المنادى.',
        'the vocative.',
      ],
      objectives: [
        'identify the various forms of demonstrative and relative pronouns;',
        'compare gender markers in Arabic;',
        'identify the characteristics of Arabic nouns;',
        'differentiate between singular and dual forms of nouns;',
        'construct plural forms of singular nouns;',
        'identify construct phrases and their usages;',
        'differentiate between separable and inseparable pronouns;',
        'identify correct usage of adjectives, conjunctions, permutative and emphasis in Arabic sentences;',
        'apply correct preposition particles in a given sentence;',
        'differentiate between transitive and intransitive verbs and use them in sentences;',
        'identify the perfect verbs and their forms;',
        'identify the imperfect verbs and their grammatical words in sentences;',
        'identify the imperative verbs and their forms;',
        'identify the kinds of modifiers and apply them in Arabic usage;',
        'differentiate between trilateral and derived verbs;',
        'identify the types of derivatives;',
        'apply the rules governing conditional sentences, identify, construct and differentiate them in normal sentences;',
        'recognise and count Arabic numerals from 1 to 1000 and identify the intricacies involved in their usage;',
        'distinguish between doer and doer-substitute and apply them in sentences;',
        'identify different types of adverbial clause, the exempted, specification and the vocative and use them in standard Arabic;',
      ],
    },
    'COMPOSITION': {
      subtopics: [
        'This section consists of five (5) questions on subjects relating to the lives and environment of the candidates, e.g. education, culture, health, politics, economy, sports and current affairs.',
      ],
      objectives: [
        'use appropriate words for specific thoughts;',
        'use correct idiomatic expressions in Arabic;',
        'communicate effectively in Arabic;',
        'express ideas clearly in Arabic;',
        'demonstrate the use of common Arabic idioms and proverbs;',
      ],
    },
    'ARABIC LITERATURE': {
      subtopics: [
        'المدخل إلى األدب العربي.',
        'Introduction to Arabic literature.',
        'األدب تعريفه وأقسامه وفنونه.',
        'العصور األدبية.',
        'الشعر تعريفه وأنواعه وأغراضه.',
        'النثر تعريفه وفنونه',
        'العصر الجاهلي )حوالى 500 – 610 م (.',
        'The Pre-Islamic Period (500 – 610 C.E.).',
        'الشنفرى والميته "أقيموا بني أمي صدور مطيكم # ".',
        'أكثم بن الصيفي التميمي وخطبته عند كسرى "إن أفضل األشياء...".',
        'العصور اإلسالمية )610 – 1798م(.',
        'The Islamic Periods (610 – 1798 C.E.).',
        'الحجاج بن يوسف الثقفي وخطبته الوعظية "أيها الناس قد أصبحتم في.".',
        'علي بن أبي طالب وخطبته في الجهاد باإلخالص',
        'عبدهللا بن المقفع ورسالته في معاملته الصديق وبدايتها "أبذل لصديقك ".',
        'جرير بن عطية وقصيدته في مدح الخليفة عمر بن عبدالعزيز.',
        'العصر الحديث )1798م إلى اليوم(.',
        'The Modern Period (1978 to date).',
        'أحمد شوقي وقصيدته " العلم والتعليم وواجب المعلم"',
        'جبران خليل جبران وقصيدته الموكب "الخير في الناس مصنوع ..."',
        'عباس محمود العقاد وكتابه "اللغة الشاعرة"',
        'األدب العربي في غرب إفريقيا.',
        'Arabic Literature in West Africa .',
        'أسماء بنت الشيخ عثمان بن فودي وقصيدتها "أعيني جودا وابكيا لحبيبتي "',
        'علي عبدالقادر العسلي وكتابه قصة عبث الطفولة"',
        'محمد األمين سامبوا غساما وقصيدته "االفتخار بالقارة اإلفريقية العريقة "',
        'يحيى آدم الفالني وكتابه " أهل التكرور"',
      ],
      objectives: [
        'identify the essence of Arabic literature; poetry, prose and their periods.',
        'identify pre-Islamic Arabic poetic and prosaic traditions and conventions;',
        'identify and analyse the style of figurative expressions contained in a given Islamic literature;',
        'describe the aesthetic features in literary texts and assess their modern cultural values;',
        'evaluate areas of successful use of Arabic as a medium of West African novel and drama, analyse their contents and describe their major characteristics and plots.',
      ],
    },
  },
} as const

export type ArabicTopic = keyof typeof ARABIC_CONFIG.topics