export const BIOLOGY_CONFIG = {
  name: 'Biology',
  prefix: 'BIO',
  category: 'science',
  priority: 3,
  totalQuestions: 40,
  topics: {
    'Variety of organisms': {
      subtopics: [
        'Living organisms',
        'Characteristics',
        'Cell structure and functions of cell components',
        'Level of organization',
        'Cell e.g. euglena and paramecium',
        'Tissue e.g. epithelial tissues and hydra',
        'Organ e.g. onion bulb',
        'Systems e.g. reproductive, digestive and excretory',
        'Organisms e.g. Chlamydomonas',
        'Evolution among the following',
        'Monera (prokaryotes), e.g. bacteria and blue green algae',
        'Protista (protozoans and protophyta), e.g. Amoeba, Euglena and Paramecium',
        'Fungi, e.g. mushroom and Rhizopus',
        'Plantae (plants)',
        'Thallophyta (e.g. Spirogyra)',
        'Bryophyta (mosses and liverworts) e.g. Brachmenium and Merchantia',
        'Pteridophyta (ferns) e.g. Dryopteris',
        'Spermatophyta (Gymnospermae and Angiospermae)',
        'Gymnosperms e.g. Cycads and conifers',
        'Angiosperms (monocots, e.g. maize; dicots, e.g. water leaf)',
        'Animalia (animals)',
        'Invertebrates',
        'coelenterate e.g. Hydra',
        'Platyhelminthes flatworms e.g. Taenia',
        'Nematoda (roundworms)',
        'Annelida e.g. earthworm',
        'Arthropoda e.g. mosquito, cockroach, housefly, bee, butterfly',
        'Mollusca e.g. snails',
        'Multicellular animals (vertebrates)',
        'Pisces (cartilaginous and bony fish)',
        'Amphibia e.g. toads and frogs',
        'Reptilia e.g. lizards, snakes and turtles',
        'Aves (birds)',
        'Mammalia (mammals)',
        'Structural/functional and behavioural adaptations of organisms',
        'adaptive colouration and its functions',
        'Behavioural adaptations in social animals',
        'Structural adaptations in organisms',
      ],
      objectives: [
        'differentiate between the characteristics of living and non-living things.',
        'identify the structures of plant and animal cells.',
        'analyse the functions of the components of plant and animal cells.',
        'compare and contrast the structure of plant and animal cells.',
        'trace the levels of organization among organisms in their logical sequence in relation to the five levels of organization of living organisms.',
        'analyse external features and characteristics of the listed organisms.',
        'apply the knowledge from (i) above to demonstrate increase in structural complexity.',
        'trace the stages in the life histories of the listed organisms.',
        'apply the knowledge of the life histories to demonstrate gradual transition from life in water to life on land.',
        'trace the evolution of the listed plants.',
        'trace the advancement of the invertebrate animals.',
        'determine the economic importance of the insects studied.',
        'assess their values to the environment.',
        'trace the advancement of multi-cellular animals.',
        'determine their economic importance.',
        'describe how the various structures, functions and behaviour adapt these organisms to their environment, and way of life.',
        'Categorize countershading in fish, toads, snakes and warning colouration in mushrooms.',
        'Differentiate various castes in social insects like termites and their functions in their colony hive.',
        'Account for basking in lizards, territorial behavour of other animals under unfavourable conditions (hibernation and aestivation).',
        'account for adaptation in organisms with respect to the following:',
      ],
    },
    'Form and functions': {
      subtopics: [
        'Internal structure of plants and animals',
        'Internal structure of a flowering plant',
        'Root',
        'Stem',
        'Leaf',
        'Internal structure of a mammal',
        'Nutrition',
        'Modes of nutrition',
        'Autotrophic',
        'Heterotrophic',
        'Types of Nutrition',
        'Plant nutrition',
        'Photosynthesis',
        'Chemosynthesis',
        'Mineral requirements',
        'macro and micro-nutrients',
        'Animal nutrition',
        'Classes of food substances; carbohydrates, proteins, fats and oils, vitamins, mineral salts and water',
        'Food tests (e.g. starch, reducing sugar, protein, oil, fat etc.)',
        'The mammalian tooth (structures, types and functions)',
        'Mammalian alimentary canal',
        'Nutrition process (ingestion, digestion, absorption, and assimilation of digested food)',
        'Transport',
        'Need for transportation',
        'Materials for transportation',
        'Excretory products, gases, manufactured food, digested food, nutrient, water and hormones',
        'Channels for transportation',
        'Mammalian circulatory system (heart, arteries, vein and capillaries)',
        'Plant vascular system (phloem and xylem)',
        'Media and processes of mechanism for transportation',
        'Respiration',
        'Respiratory organs and surfaces',
        'The mechanism of gaseous exchange in plants',
        'The mechanism of gaseous exchange in animals',
        'Aerobic respiration',
        'Anaerobic respiration',
        'Excretion',
        'Types of excretory structures',
        'contractile vacuole, flame cell, nephridium, Malpighian tubule, kidney, stoma and lenticel',
        'Excretory mechanisms',
        'Kidneys',
        'lungs',
        'skin',
        'Excretory products of plants',
        'Support and movement',
        'Tropic, tactic, nastic and sleep movements in plants',
        'supporting tissues in animals',
        'Types and functions of the skeleton',
        'Exoskeleton',
        'Endoskeleton',
        'Functions of the skeleton in animals',
        'Reproduction',
        'Asexual reproduction',
        'Fission (e.g. Paramecium)',
        'Budding (e.g. yeast)',
        'Natural vegetative propagation',
        'Artificial vegetative propagation',
        'Sexual reproduction in flowering plants',
        'Floral parts and their functions',
        'Pollination and fertilization',
        'products of sexual reproduction',
        'Reproduction in mammals',
        'Structures and functions of the male and female reproductive organs',
        'Fertilization and development',
        'Fusion of gametes',
        'Growth',
        'Meaning of growth',
        'Germination of seeds and condition necessary for germination of seeds',
        'Co-ordination and control',
        'Nervous coordination',
        'the components, structure and functions of the central nervous system',
        'The components and functions of the peripheral nervous system',
        'Mechanism of transmission of impulses',
        'Reflex action',
        'The sense organs',
        'Skin (tactile)',
        'Nose (olfactory)',
        'Tongue (taste)',
        'Eye (sight)',
        'Ear (auditory)',
        'Hormonal control',
        'animal hormonal system (Pituitary, thyroid, parathyroid, adrenal gland, pancreas, gonads)',
        'Plant hormones (phytohormones)',
        'Homeostasis',
        'Body temperature regulation',
        'Salt and water regulation',
      ],
      objectives: [
        'identify the transverse sections of these organs.',
        'relate the structure of these organs to their functions.',
        'identify supporting tissues in plants (collenchyma) sclerenchyma, xylem and phloem fibres)',
        'describe the distribution of supporting tissues in roots, stem and leaf',
        'examine the arrangement of the mammalian internal organs.',
        'describe the appearance and position of the digestive, reproductive and excretory organs.',
        'compare autotrophic and heterotrophic modes of nutrition.',
        'provide examples from both flowering and non- flowering plants.',
        'compare the photosynthetic and chemosynthetic modes of nutrition;',
        'differentiate the following examples of heterotrophic feeding:',
        'differentiate the light and dark reactions, of photosynthesis.',
        'determine the necessity of light, carbon (IV) oxide and chlorophyll in photosynthesis.',
        'detect the presence of starch in a leaf as an evidence of photosynthesis.',
        'identify macro-and micro-elements required by plants.',
        'recognise the deficiency symptoms of nitrogen, phosphorous and potassium.',
        'indicate the sources of the various classes of food;',
        'determine the nutritional value of food',
        'relate the importance and deficiency (e.g. scurvy, rickets, kwashiorkor etc.) of each class of food;',
        'determine the importance of a balanced diet.',
        'detect the presence of a food type from the result of a given experiment.',
        'describe the structure of a typical mammalian tooth',
        'differentiate the types of mammalian tooth and relate their structures to their functions.',
        'compare the dental formulae of man, sheep and dog.',
        'relate the structure of the various components of the alimentary canal and its accessory organs (liver, pancreas and gall bladder) to their functions.',
        'identify the general characteristics of digestive enzymes',
        'associate enzymes with digestion of carbohydrates, proteins and fats and',
        'determine the end products of these classes of food.',
        'determine the relationship between increase in size and complexity; and the need for the development of a transport system in plants and animals.',
        'determine the sources of materials and the forms in which they are transported.',
        'describe the general circulatory system',
        'compare specific functions of the hepatic portal vein, the pulmonary vein and artery, aorta, the renal artery and vein.',
        'identify the organs of the plant vascular system.',
        'understand the specific functions of the phloem and xylem.',
        'identify media of transportation (e.g. cytoplasm, cell sap, body fluid, blood and lymph)',
        'state the composition and functions of blood and lymph',
        'describe diffusion, osmosis, plasmolysis and turgidity as mechanisms of transportation in organisms.',
        'compare the various mechanisms of open circulatory systems in animal, transpiration pull, root pressure and active transport as mechanisms of transportation in plants.',
        'explain the significance of respiration;',
        'describe a simplified outline of the chemical processes involved in glycolysis and krebs cycle with reference to ATP production',
        'deduce gaseous exchange and products, exchange and production of heat energy during respiration from experimental set up.',
        'describe the following respiratory organs and surfaces with organisms in which they occur; body surface, gill, trachea, lungs, stomata and lenticel.',
        'describe the mechanism for the opening and closing of the stomata',
        'determine respiratory mechanisms in plants and animals.',
        'examine the role of oxygen in the liberation of energy for the activities of the living organisms',
        'explain the effect of insufficient supply of oxygen to the muscles.',
        'use yeast cells and sugar solution to demonstrate the process of fermentation.',
        'state the economic importance of yeasts.',
        'define the meaning and state the significance of excretion',
        'relate the characteristics of each structure with functions.',
        'relate the structure of the kidneys to the excretory and osmo-regulatory functions.',
        'identify the functions and excretory products of the lungs and the skin.',
        'deduce the economic importance of the excretory products of plants e.g. carbon (IV) oxide, oxygen, tannins, resins, gums, mucilage, alkaloids etc.',
        'determine the need for support and movement in organisms',
        'identify supporting tissues in plants (collenchyma, sclerenchyma, xylem and phloem fibres)',
        'describe the distribution of supporting tissues in root, stem and leaf.',
        'relate the response of plants to the stimuli of light, water, gravity and touch',
        'identify the regions of growth in roots and shoots and the roles of auxins in tropism.',
        'relate the location of chitin, cartilage and bone to their supporting function.',
        'relate the structure and the general layout of the mammalian skeleton to their supportive, locomotive and respiratory function.',
        'differentiate types of joints using appropriate examples.',
        'apply the protective, supportive, locomotive and respiratory functions of the skeleton to the well being of the animal.',
        'differentiate between asexual and sexual reproduction',
        'apply natural vegetative propagation in crop production and multiplication.',
        'apply grafting, budding and layering in agricultural practices.',
        'relate parts of flower to their functions and reproductive process.',
        'state the advantages of cross pollination.',
        'deduce the different types of placentation that develop into simple, aggregate, multiple and succulent fruits.',
        'differentiate between male and female reproductive organs.',
        'relate their structure and function to the production of offspring.',
        'describe the fusion of gametes as a process of fertilization.',
        'relate the effects of the mother’s health, nutrition and indiscriminate use of drugs on the developmental stages of the embryo up to birth.',
        'explain the modern methods of regulating reproduction on e.g. invitro fertilization and birth control',
        'apply the knowledge of the conditions necessary for germination on plant growth.',
        'differentiate between epigeal and hypogeal germination.',
        'apply the knowledge of the structure and function of the central nervous system in the coordination of body functions in organisms.',
        'illustrate reflex actions such as blinking of the eyes, knee jerk etc.',
        'differentiate between reflex and voluntary actions as well as conditioned reflexes such as salivation, riding a bicycle and swimming.',
        'relate the listed sense organs with their functions.',
        'apply the knowledge of the structure and functions of these sense organs in detecting and correcting their defects.',
        'state the location of the listed endocrine glands in animals.',
        'relate the hormone produced by each of these glands to their functions.',
        'examine the effects of various phytohormones (e.g. auxins, gibberellin, cytokinin, and ethylene) on growth, tropism, flowering, fruit ripening and leaf abscission.',
        'relate the function of hormones in homeostasis.',
      ],
    },
    'Ecology': {
      subtopics: [
        'Factors affecting the distribution of Organisms',
        'Abiotic',
        'Biotic',
        'Symbiotic interactions of plants and animals',
        'Energy flow in the ecosystem: food chains, food webs and trophic levels',
        'Nutrient cycling in nature',
        'carbon cycle',
        'water cycle',
        'Nitrogen cycle',
        'Natural Habitats',
        'Aquatic (e.g. ponds, streams, lakes, seashores and mangrove swamps)',
        'Terrestrial/arboreal (e.g. tree-tops, abandoned farmland or a dry grassy (savanna) field, and burrow or hole',
        'Local (Nigerian) Biomes',
        'Tropical rainforest',
        'Guinea savanna (southern and northern)',
        'Sudan Savanna',
        'Desert',
        'Highlands of montane forests and grasslands of the Obudu -, Jos -, Mambilla - Plateaus',
        'The Ecology of Populations',
        'Population density and overcrowding',
        'Adaptation for survival',
        'Factors that bring about competition',
        'Intra and inter-specific competition',
        'Relationship between competition and succession',
        'Factors affecting population sizes',
        'Biotic (food, pest, disease, predation, competition and reproductive ability)',
        'Abiotic (temperature, space, light, rainfall, topography, pressure, pH) etc.',
        'Ecological succession',
        'primary succession',
        'secondary succession',
        'SOIL',
        'Characteristics of different types of soil (sandy, loamy, clayey)',
        'soil structure',
        'porosity, capillarity and humus content',
        'Components of the soil',
        'inorganic',
        'organic',
        'soil organisms',
        'soil air',
        'soil water',
        'Soil fertility',
        'loss of soil fertility',
        'renewal and maintenance of soil fertility',
        'Humans and Environment',
        'Diseases',
        'Common and endemic diseases',
        'Easily transmissible diseases and disease syndrome',
        'poliomyelitis',
        'cholera',
        'tuberculosis',
        'sexually transmitted disease/syndrome (gonorrhea, syphilis, AIDS, etc.)',
        'Pollution and its control',
        'Sources, types, effects and methods of control',
        'Sanitation and sewage',
        'Conservation of Natural Resources',
        'Game reserves and National parks',
      ],
      objectives: [
        'relate the effects of temperature; rainfall, relative humidity, wind speed and direction, altitude, salinity, turbidity, pH and edaphic (soil) conditions on the distribution of organisms.',
        'use appropriate equipment (secchi disc, thermometer, rain gauge) to measure abiotic factors.',
        'describe how the activities of plants/animals (particularly human) affect the distribution of organisms.',
        'determine appropriate examples of symbiosis, parasitism, saprophytism, commensalism, mutualism, amensalism, competition, predation and cooperation among organisms.',
        'explain the distribution of organisms with food chains and food webs in particular habitats.',
        'define chains and webs',
        'describe the carbon cycle and its significance including the balance of atmospheric oxygen and carbon (IV) oxide and global warming.',
        'assess the effects of water cycle on other nutrient cycles.',
        'relate the roles of bacteria and leguminous plants in the cycling of nitrogen.',
        'associate plants and animals with each of these habitats.',
        'relate adaptive features to the habitats in which organisms live.',
        'locate biomes in regions',
        'apply the knowledge of the features of the listed local biomes in determining the characteristics of different regions of Nigeria.',
        'determine the reasons for rapid changes in human population and the consequences of overcrowding.',
        'compute/calculate density as the number of organisms per unit area.',
        'Relate increase in population, diseases, shortage of food and space with intra- and inter-specific competition.',
        'Determine niche differentiation as a means of reducing intra-specific completion.',
        'Relate competition to succession.',
        'deduce the effect of these factors on the size of population.',
        'determine the interactions between biotic and abiotic factors, (e.g. drought or scarcity of water which leads to food shortage and lack of space which causes increase in disease rates).',
        'trace the sequence in succession to the climax stage of stability in plant population.',
        'identify physical properties of different soil types based on simple measurement of particle size, porosity or water retention ability.',
        'determine the amounts of air, water, humus and capillarity in different soil types experimentally.',
        'relate soil characteristics, types and components to the healthy growth of plants',
        'relate such factors as loss of inorganic matter, compaction, leaching, erosion of the top soil and repeated cropping with one variety.',
        'apply the knowledge of the practice of contour ridging, terracing, mulching, poly-cropping, strip-cropping, use of organic and inorganic fertilizers, crop rotation, shifting cultivation, etc. to enhance soil conservation.',
        'identify ecological conditions that favour the spread of common endemic and potentially epidemic diseases e.g. malaria, meningitis, drancunculiasis, schistosomiasis, onchocerciasis, typhoid fever and cholera.',
        'relate the biology of the vector or agent of each disease with its spread and control',
        'use the knowledge of the causative organisms, mode of transmission and symptoms of the listed diseases to their prevention - treatment - control',
        'apply the principles of inoculation and vaccination on disease prevention.',
        'categorize pollution into air, water and soil',
        'relate the effects of common pollutants to human health and environmental degradation.',
        'determine the methods by which each pollutant may be controlled.',
        'explain the importance of sanitation with emphasis on solid waste, sewage disposal, community health and personal hygiene.',
        'assess the roles and functions of international and national health agencies e.g. World Health Organization (WHO), United Nations International Children Emergency Fund (UNICEF), International Red Cross Society (IRCS) and the ministries of health and environment.',
        'apply the various methods of conservation of both the renewable and non-renewable natural resources for the protection of our environment for present and future generations.',
        'outline the benefits of conserving natural resources, prevention of desertification.',
        'identify the bodies responsible for the conservation of resources at the national and international levels e.g. Nigerian Conservation Foundation (NCF), Federal Ministry of Environment, Nigeria National Parks, World Wildlife Foundation (WWF), International Union for Conservation of Nature (IUCN), United Nations Environmental Programme (UNEP) and their activities.',
        'identify and state the location and importance of game reserves and National parks in Nigeria',
      ],
    },
    'Heredity and variations': {
      subtopics: [
        'Variation In Population',
        'Morphological variations in the physical appearance of individuals',
        'size (height and weight)',
        'Colour (skin, eye, hair, coat of animals, scales and feathers)',
        'Fingerprints',
        'Physiological variation',
        'Ability to roll tongue',
        'Ability to taste phenylthiocarbamide (PTC)',
        'Blood groups',
        'Application of discontinuous variation in crime detection, blood transfusion and determination of paternity',
        'Heredity',
        'Inheritance of characters in organisms',
        'Heritable characters',
        'Non-heritable characters',
        'Chromosomes – the basis of heredity',
        'Structure',
        'Process of transmission of hereditary characters from parents to offsprings',
        'Probability in genetics and sex determination',
        'Application of the principles of heredity in',
        'Agriculture',
        'Medicine',
        'Sex – linked characters e.g. baldness, haemophilia, colour blindness, etc.',
      ],
      objectives: [
        'differentiate between continuous and discontinuous variations with examples.',
        'relate the role of environmental conditions, habitat and the genetic constitution to variation.',
        'measure heights and weights of pupils of the same age group',
        'plot graphs of frequency distribution of the heights and weights.',
        'observe and record various colour patterns in some plants and animals.',
        'apply classification of fingerprints in identity detection.',
        'identify some specific examples of physiological variation among human population.',
        'categorize people according to their physiological variation.',
        'apply the knowledge of blood groups in blood transfusion and determination of paternity.',
        'use discontinuous variation in crime detection.',
        'determine heritable and non-heritable characters with examples.',
        'illustrate simple structure of DNA',
        'illustrate segregation of genes at meiosis and recombination of genes at fertilization to account for the process of transmission of characters from parents to offsprings.',
        'deduce that segregation of genes occurs during gamete formation and that recombination of genes at fertilization is random in nature.',
        'analyze data on cross-breeding experiments.',
        'apply the principles of heredity in the production of new varieties of crops and livestock through cross-breeding.',
        'deduce advantages and disadvantages of out-breeding and in-breeding.',
        'analyze elementarily the contentious issues of genetically modified organisms (GMO) and gene therapy and biosafety.',
        'apply the knowledge of heredity in marriage counselling with particular reference to blood grouping, sickle-cell anaemia and the Rhesus factors.',
        'describe the significance of using recombinant DNA materials in the production of important medical products such as insulin, interferon and enzymes.',
        'identify characters that are sex linked.',
      ],
    },
    'Evolution': {
      subtopics: [
        'Theories of evolution',
        'Lamarck’s theory',
        'Darwin’s theory',
        'organic theory',
        'Evidence of evolution',
      ],
      objectives: [
        'relate organic evolution as the sum total of all adaptive changes that have taken place over a long period of time resulting in the diversity of forms, structures and functions among organisms.',
        'explain the contributions of Lamarck and Darwin to the theory of evolution.',
        'state the evidences in support of organic evolution',
        'mention the evidences for evolution such as fossil records, comparative anatomy, physiology and embryology.',
        'trace evolutionary trends in plants and animals.',
        'state the evidence of modern evolutionary theories such as genetic studies and the role of mutation.',
      ],
    },
  },
} as const

export type BiologyTopic = keyof typeof BIOLOGY_CONFIG.topics