export const CHEMISTRY_CONFIG = {
  name: 'Chemistry',
  prefix: 'CHEM',
  category: 'science',
  priority: 4,
  totalQuestions: 40,
  topics: {
    'Separation of Mixtures and Purification of Chemical Substances': {
      subtopics: [
        'Pure and impure substances',
        'Boiling and melting points',
        'Elements, compounds and mixtures',
        'Chemical and physical changes',
        'Separation processes',
        'Evaporation',
        'simple and fractional distillation',
        'sublimation',
        'filtration',
        'crystallization',
        'paper and column chromatography',
        'simple and fractional crystallization',
        'magnetization',
        'decantation',
      ],
      objectives: [
        'distinguish between pure and impure substances;',
        'use boiling and melting points as criteria for purity of chemical substances;',
        'distinguish between elements, compounds and mixture;',
        'differentiate between chemical and physical changes;',
        'identify the properties of the components of a mixture;',
        'specify the principle involved in each separation method; and',
        'apply the basic principle of separation processes in everyday life.',
      ],
    },
    'Chemical Combination': {
      subtopics: [
        'Laws of definite, multiple and reciprocal proportions',
        'law of conservation of matter',
        'Gay Lussac’s law of combining volumes',
        'Avogadro’s law',
        'chemical symbols',
        'formulae',
        'equations and their uses',
        'relative atomic mass based on 12C=12',
        'the mole concept and Avogadro’s number',
        'stoichiometry of reactions',
      ],
      objectives: [
        'perform simple calculations involving formulae, equations/chemical composition and the mole concept;',
        'deduce the chemical laws from given expressions/statements/data;',
        'interpret graphical representations related to these laws; and',
        'deduce the stoichiometry of chemical reactions.',
      ],
    },
    'Kinetic Theory of Matter and Gas Laws': {
      subtopics: [
        'Phenomena to support the kinetic theory of matter using',
        'melting',
        'vapourization',
        'boiling',
        'freezing',
        'condensation',
        'in terms of molecular motion and Brownian movement',
        'The laws of Boyle, Charles, Graham and Dalton (law of partial pressure)',
        'combined gas law',
        'molar volume and atomicity of gases',
        'The ideal gas equation (PV = nRT)',
        'The relationship between vapour density of gases and the relative molecular mass',
      ],
      objectives: [
        'apply the theory to distinguish between solids, liquids and gases;',
        'deduce reasons for change of state;',
        'draw inferences based on molecular motion;',
        'deduce gas laws from given expressions/statements;',
        'interpret graphical representations related to these laws; and',
        'perform simple calculations based on these laws, equations and relationships.',
      ],
    },
    'Atomic Structure and Bonding': {
      subtopics: [
        'The concept of atoms, molecules and ions, the works of Dalton, Millikan, Rutherford, Moseley, Thompson and Bohr',
        'Atomic structure, electron configuration, atomic number, mass number and isotopes',
        'specific examples should be drawn from elements of atomic number 1 to 20',
        'Shapes of s and p orbitals',
        'The periodic table and periodicity of elements',
        'presentation of the periodic table with a view to recognizing families of elements e.g. alkali metals, halogens, the noble gases and transition metals',
        'The variation of ionization energy, ionic radii, electron affinity and electronegativity',
        'Chemical bonding',
        'Electrovalency and covalency',
        'the electron configuration of elements and their tendency to attain the noble gas structure',
        'Hydrogen bonding and metallic bonding as special types of electrovalency and covalency respectively',
        'coordinate bond as a type of covalent bond as illustrated by complexes like [Fe(CN)6]3-, [Fe(CN)6]4-, [Cu(NH3)4]2+ and [Ag(NH3)2]+',
        'van der Waals’ forces should be mentioned as a special type of bonding forces',
        'Shapes of simple molecules',
        'linear ((H2, O2, C12, HCl and CO2)',
        'non-linear (H2O)',
        'tetrahedral (CH4)',
        'pyramidal (NH3)',
        'Nuclear Chemistry',
        'Radioactivity – Types and properties of radiations',
        'Nuclear reactions',
        'Simple equations',
        'uses and applications of natural and artificial radioactivity',
      ],
      objectives: [
        'distinguish between atoms, molecules and ions;',
        'identify the contributions of these scientists to the development of the atomic structure;',
        'deduce the number of protons, neutrons and electrons from atomic and mass numbers of an atom;',
        'apply the rules guiding the arrangement of electrons in an atom;',
        'identify common elements exhibiting isotopy;',
        'relate isotopy to mass number;',
        'perform simple calculations relating to isotopy;',
        'differentiate between the shapes of the orbitals;',
        'determine the number of electrons in s and p atomic orbitals;',
        'relate atomic number to the position of an element on the periodic table;',
        'relate properties of groups of elements on the periodic table;',
        'identify reasons for variation in properties across the period and down the groups;',
        'differentiate between the different types of bonding;',
        'deduce bond types based on electron configurations;',
        'relate the nature of bonding to properties of compounds;',
        'differentiate between the various shapes of molecules;',
        'distinguish between ordinary chemical reaction and nuclear reaction;',
        'differentiate between natural and artificial radioactivity;',
        'compare the properties of the different types of nuclear radiations;',
        'compute simple calculations on the half-life of a radioactive material;',
        'balance simple nuclear equation; and',
        'identify the various applications of radioactivity.',
      ],
    },
    'Air': {
      subtopics: [
        'The natural gaseous constituents and their proportion in the air',
        'nitrogen',
        'oxygen',
        'water vapour',
        'carbon (IV) oxide',
        'the noble gases (argon and neon)',
        'Air as a mixture and some uses of the noble gas',
      ],
      objectives: [
        'deduce reason (s) for the existence of air as a mixture;',
        'identify the principle involved in the separation of air components;',
        'deduce reasons for the variation in the composition of air in the environment; and',
        'specify the uses of some of the constituents of air.',
      ],
    },
    'Water': {
      subtopics: [
        'Water as a product of the combustion of hydrogen and its composition by volume',
        'Water as a solvent, atmospheric gases dissolved in water and their biological significance',
        'Hard and soft water',
        'Temporary and permanent hardness and methods of softening hard water',
        'Treatment of water for town supply',
        'Water of crystallization',
        'efflorescence',
        'deliquescence',
        'hygroscopy',
        'Examples of the substances exhibiting these properties and their uses',
      ],
      objectives: [
        'identify the various uses of water;',
        'identify the effects of dissolved atmospheric gases in water;',
        'distinguish between the properties of hard and soft water;',
        'determine the causes of hardness;',
        'identify methods of removal of hardness;',
        'describe the processes involved in the treatment of water for town supply;',
        'distinguish between these phenomena; and',
        'identify the various compounds that exhibit these phenomena.',
      ],
    },
    'Solubility': {
      subtopics: [
        'Unsaturated, saturated and supersaturated solutions',
        'Solubility curves and simple deductions from them',
        'solubility defined in terms of mole per dm3',
        'simple calculations',
        'Solvents for fats, oil and paints and the use of such solvents for the removal of stains',
        'True and False solutions (Suspensions and colloids)',
        'Properties and examples',
        'Harmattan haze and water paints as examples of suspensions',
        'fog, milk, aerosol spray, emulsion paints and rubber solution as examples of colloids',
      ],
      objectives: [
        'distinguish between the different types of solutions;',
        'interpret solubility curves;',
        'calculate the amount of solute that can dissolve in a given amount of solvent at a given temperature;',
        'deduce that solubility is temperature-dependent;',
        'relate nature of solvents to their uses;',
        'differentiate among true solutions, suspensions and colloids;',
        'compare the properties of a ‘true’ solution and a ‘false’ solution; and',
        'provide typical examples of suspensions and colloids.',
      ],
    },
    'Environmental Pollution': {
      subtopics: [
        'Sources and effects of pollutants',
        'Air pollution',
        'Examples of air pollutants such as H2S, CO, SO2, oxides of nitrogen, chlorofluorocarbons and dust',
        'Water pollution',
        'Sewage and oil pollution should be known',
        'Soil pollution',
        'Oil spillage',
        'biodegradable and non-biodegradable pollutants',
      ],
      objectives: [
        'identify the different types of pollution and pollutants;',
        'specify different sources of pollutants;',
        'classify pollutants as biodegradable and non-biodegradable;',
        'specify the effects of pollution on the environment; and',
        'identify measures for control of environmental pollution.',
      ],
    },
    'Acids, Bases and Salts': {
      subtopics: [
        'General characteristics, properties and uses of acids, bases and salts',
        'Acids/base indicators',
        'basicity of acids',
        'normal, acidic, basic and double salts',
        'An acid defined as a substance whose aqueous solution furnishes H3O+ ions or as a proton donor',
        'Ethanoic, citric and tartaric acids as examples of naturally occurring organic acids',
        'alums as examples of double salts',
        'preparation of salts by neutralization, precipitation and action of acids on metals',
        'Oxides and trioxocarbonate (IV) salts',
        'Qualitative comparison of the conductance of molar solutions of strong and weak acids and bases',
        'relationship between conductance and amount of ions present',
        'pH and pOH scale',
        'Simple calculations',
        'Acid/base titrations',
        'Hydrolysis of salts',
        'Simple examples such as NH4Cl, AlCl3, Na2CO3 and CH3COONa',
      ],
      objectives: [
        'distinguish between the properties of acids and bases;',
        'identify the different types of acids and bases;',
        'determine the basicity of acids;',
        'differentiate between acidity and alkalinity using acid/base indicators;',
        'identify the various methods of preparation of salts;',
        'classify different types of salts;',
        'relate degree of dissociation to strength of acids and bases;',
        'relate degree of dissociation to conductance;',
        'perform simple calculations on pH and pOH;',
        'identify the appropriate acid-base indicator;',
        'interpret graphical representation of titration curves;',
        'perform simple calculations based on the mole concept;',
        'balance equations for the hydrolysis of salts; and',
        'deduce the properties (acidic, basic, neutral) of the resultant solution.',
      ],
    },
    'Oxidation and Reduction - Redox': {
      subtopics: [
        'Oxidation in terms of the addition of oxygen or removal of hydrogen',
        'Reduction as removal of oxygen or addition of hydrogen',
        'Oxidation and reduction in terms of electron transfer',
        'Use of oxidation numbers',
        'Oxidation and reduction treated as change in oxidation number and use of oxidation numbers in balancing simple equations',
        'IUPAC nomenclature of inorganic compounds using oxidation number',
        'Tests for oxidizing and reducing agents',
      ],
      objectives: [
        'identify the various forms of expressing oxidation and reduction;',
        'classify chemical reactions in terms of oxidation or reduction;',
        'balance redox reaction equations;',
        'deduce the oxidation number of chemical species;',
        'compute the number of electron transfer in redox reactions;',
        'identify the name of redox species in a reaction',
        'distinguish between oxidizing and reducing agents in redox reactions;',
        'apply oxidation number in naming inorganic compounds; and',
        'relate reagents to their oxidizing and reducing abilities.',
      ],
    },
    'Electrolysis': {
      subtopics: [
        'Electrolytes and non-electrolytes',
        'Faraday’s laws of electrolysis',
        'Electrolysis of dilute H2SO4',
        'aqueous CuSO4',
        'CuCl2 solution',
        'dilute and concentrated NaCl solutions',
        'fused NaCl',
        'Factors affecting discharge of ions at the electrodes',
        'Uses of electrolysis',
        'Purification of metals e.g. copper',
        'production of elements and compounds (Al, Na, O2, Cl2 and NaOH)',
        'Electrochemical cells',
        'Electrochemical series (K, Ca,Na, Mg, Al, Zn, Fe, Sn, Pb, H, Cu, Hg, Ag, Au,)',
        'half-cell reactions and electrode potentials',
        'Simple calculations only',
        'Corrosion as an electrolytic process',
        'cathodic protection of metals',
        'painting',
        'electroplating',
        'coating with grease or oil as ways of preventing iron from corrosion',
      ],
      objectives: [
        'distinguish between electrolytes and non-electrolytes;',
        'perform calculations based on faraday as mole of electrons;',
        'identify suitable electrodes for different electrolytes;',
        'specify the chemical reactions at the electrodes;',
        'determine the products at the electrodes;',
        'identify the factors that affect the products of electrolysis;',
        'specify the different areas of application of electrolysis;',
        'identify the various electrochemical cells;',
        'calculate electrode potentials using half-cell reaction equations;',
        'determine the different areas of application of electrolytic processes; and',
        'identify methods used in protecting metals.',
      ],
    },
    'Energy Changes': {
      subtopics: [
        'Energy changes (∆H) accompanying physical and chemical changes',
        'dissolution of substances in/or reaction with water e.g. Na, NaOH, K, NH4Cl',
        'Endothermic (+∆H) and exothermic (-∆H) reactions',
        'Entropy as an order-disorder phenomenon',
        'simple illustrations like mixing of gases and dissolution of salts',
        'Spontaneity of reactions',
        '∆Gѳ = 0 as a criterion for equilibrium',
        '∆G greater or less than zero as a criterion for non-spontaneity or spontaneity respectively',
      ],
      objectives: [
        'determine the types of heat changes (∆H) in physical and chemical processes;',
        'interpret graphical representations of heat changes;',
        'relate the physical state of a substance to the degree of orderliness;',
        'determine the conditions for spontaneity of a reaction;',
        'relate ∆H0, ∆S0 and ∆G0 as the driving forces for chemical reactions; and',
        'solve simple problems based on the relationships ∆Gѳ = ∆H0 - T∆S0',
      ],
    },
    'Rates of Chemical Reaction': {
      subtopics: [
        'Elementary treatment of the following factors which can change the rate of a chemical reaction',
        'Temperature',
        'e.g. the reaction between HCl and Na2S2O3 or Mg and HCl',
        'Concentration/pressure',
        'e.g. the reaction between HCl and Na2S2O3, HCl and marble and the iodine clock reaction',
        'for gaseous systems, pressure may be used as concentration term',
        'Surface area',
        'e.g. the reaction between marble and HCl with marble in powdered form and lumps of the same mass',
        'Catalyst',
        'e.g. the decomposition of H2O2 or KClO3 in the presence or absence of MnO2',
        'Reaction rate curves',
        'Activation energy',
        'Qualitative treatment of Arrhenius’ law and the collision theory',
        'effect of light on some reactions',
        'e.g. halogenation of alkanes',
      ],
      objectives: [
        'identify the factors that affect the rates of a chemical reaction;',
        'determine the effects of temperature on the rate of reactions;',
        'examine the effect of concentration/pressure on the rate of a chemical reaction;',
        'describe how the rate of a chemical reaction is affected by surface area;',
        'determine the types of catalysts suitable for different reactions and their effects;',
        'determine ways of moderating these effects in chemical reactions;',
        'interpret reaction rate curves;',
        'solve simple problems on the rate of reactions;',
        'relate the rate of reaction to the kinetic theory of matter.',
        'examine the significance of activation energy to chemical reactions; and',
        'deduce the value of activation energy (Ea) from reaction rate curves.',
      ],
    },
    'Chemical Equilibra': {
      subtopics: [
        'Reversible reactions and factors governing the equilibrium position',
        'Dynamic equilibrium',
        'Le Chatelier’s principle and equilibrium constant',
        'Simple examples to include action of steam on iron and N2O4 2NO2',
        'No calculation will be required',
      ],
      objectives: [
        'identify the factors that affect the position of equilibrium of a chemical reaction;',
        'predict the effects of each factor on the position of equilibrium; and',
        'determine the effects of these factors on equilibrium constant.',
      ],
    },
    'Non-metals and Their Compounds': {
      subtopics: [
        'Hydrogen',
        'commercial production from water gas and cracking of petroleum fractions',
        'laboratory preparation',
        'properties',
        'uses and test for hydrogen',
        'Halogens',
        'Chlorine as a representative element of the halogen',
        'Laboratory preparation',
        'industrial preparation by electrolysis',
        'properties and uses, e.g. water sterilization, bleaching, manufacture of HCl, plastics and insecticides',
        'Hydrogen chloride and Hydrochloric acid',
        'Preparation and properties',
        'Chlorides and test for chlorides',
        'Oxygen and Sulphur',
        'Oxygen',
        'Laboratory preparation, properties and uses',
        'Commercial production from liquid air',
        'Oxides',
        'Acidic, basic, amphoteric and neutral',
        'trioxygen (ozone) as an allotrope and the importance of ozone in the atmosphere',
        'Sulphur',
        'Uses and allotropes',
        'preparation of allotropes is not expected',
        'Preparation, properties and uses of sulphur (IV) oxide',
        'the reaction of SO2 with alkalis',
        'Trioxosulphate (IV) acid and its salts',
        'the effect of acids on salts of trioxosulphate (IV)',
        'Tetraoxosulphate (VI) acid',
        'Commercial preparation (contact process only)',
        'properties as a dilute acid, an oxidizing and a dehydrating agents and uses',
        'Test for SO42-',
        'Hydrogen sulphide',
        'Preparation and properties as a weak acid, reducing and precipitating agents',
        'Test for S2-',
        'Nitrogen',
        'Laboratory preparation',
        'Production from liquid air',
        'Ammonia',
        'Laboratory and industrial preparations (Haber Process only)',
        'properties and uses',
        'ammonium salts and their uses',
        'oxidation of ammonia to nitrogen (IV) oxide and trioxonitrate (V) acid',
        'Test for NH4+',
        'Trioxonitrate (V) acid',
        'Laboratory preparation from ammonia',
        'properties and uses',
        'Trioxonitrate (V) salt-action of heat and uses',
        'Test for NO3-',
        'Oxides of nitrogen',
        'Properties',
        'The nitrogen cycle',
        'Carbon',
        'Allotropes',
        'Uses and properties',
        'Carbon (IV) oxide',
        'Laboratory preparation, properties and uses',
        'Action of heat on trioxocarbonate (IV) salts and test for CO32-',
        'Carbon (II) oxide',
        'Laboratory preparation, properties including its effect on blood',
        'sources of carbon (II) oxide to include charcoal, fire and exhaust fumes',
        'Coal',
        'Different types',
        'products obtained from destructive distillation of wood and coal',
        'Coke',
        'Gasification and uses',
        'Manufacture of synthesis gas and uses',
      ],
      objectives: [
        'predict reagents for the laboratory and industrial preparation of these gases and their compounds;',
        'identify the properties of the gases and their compounds;',
        'compare the properties of these gases and their compounds;',
        'specify the uses of each gas and its compounds;',
        'determine the specific test for each gas and its compounds;',
        'determine specific tests for Cl-, SO42-, SO32-, S2-,NH4+, NO3-, CO32-, HCO3-',
        'predict the reagents for preparation, properties and uses of HCl(g) and HCl(aq);',
        'identify the allotropes of oxygen;',
        'determine the significance of ozone to our environment;',
        'classify the oxides of oxygen and their properties;',
        'identify the allotropes of sulphur and their uses;',
        'predict the reagents for preparation, properties and uses of SO2 and H2S;',
        'specify the preparations of H2SO4 and H2SO3, their properties and uses;',
        'specify the laboratory and industrial preparation of NH3;',
        'identify the properties and uses of NH3;',
        'identify reagents for the laboratory preparation of HNO3, its properties and uses;',
        'specify the properties of N2O, NO, NO2 gases.',
        'examine the relevance of nitrogen cycle to the environment;',
        'identify allotropes of carbon;',
        'predict reagents for the laboratory preparation of CO2;',
        'specify the properties of CO2 and its uses;',
        'determine the reagents for the laboratory preparation of CO;',
        'predict the effects of CO on human;',
        'identify the different forms of coal;',
        'determine their uses;',
        'specify the products of the destructive distillation of wood and coal; and',
        'specify the uses of coke and synthesis gas.',
      ],
    },
    'Metals and their compounds': {
      subtopics: [
        'General properties of metals',
        'Alkali metals e.g. sodium',
        'Sodium hydroxide',
        'Production by electrolysis of brine',
        'its action on aluminium, zinc and lead ions',
        'Uses including precipitation of metallic hydroxides',
        'Sodium trioxocarbonate (IV) and sodium hydrogen trioxocarbonate (IV)',
        'Production by Solvay process',
        'properties and uses',
        'e.g. Na2CO3 in the manufacture of glass',
        'Sodium chloride',
        'its occurrence in sea water and uses',
        'the economic importance of sea water and the recovery of sodium chloride',
        'Alkaline-earth metals, e.g. calcium',
        'calcium oxide, calcium hydroxide and calcium trioxocarbonate (IV)',
        'Properties and uses',
        'Preparation of calcium oxide from sea shells',
        'the chemical composition of cement and the setting of mortar',
        'Test for Ca2+',
        'Aluminium',
        'Purification of bauxite',
        'electrolytic extraction',
        'properties and uses of aluminium and its compounds',
        'Test for Al3+',
        'Tin',
        'Extraction from its ores',
        'Properties and uses',
        'Metals of the first transition series',
        'Characteristic properties',
        'electron configuration',
        'oxidation states',
        'complex ion formation',
        'formation of coloured ions',
        'catalysis',
        'Iron',
        'Extraction from sulphide and oxide ores',
        'properties and uses',
        'different forms of iron and their properties and advantages of steel over iron',
        'Test for Fe2+ and Fe3+',
        'Copper',
        'Extraction from sulphide and oxide ores',
        'properties and uses of copper',
        'Preparation and uses of copper (II) Tetraoxosulphate (VI)',
        'Test for Cu2+',
        'Alloy',
        'Steel',
        'stainless steel',
        'brass',
        'bronze',
        'type-metal',
        'duralumin',
        'soft solder',
        'permallory and alnico (constituents and uses only)',
      ],
      objectives: [
        'specify the general properties of metals;',
        'determine the method of extraction suitable for each metal;',
        'relate the methods of extraction to the properties for the metals;',
        'compare the chemical reactivities of the metals;',
        'specify the uses of the metals;',
        'determine specific test for metallic ions;',
        'determine the process for the production of the compounds of these metals;',
        'compare the chemical reactivities of the compounds;',
        'specify the uses of these compounds;',
        'specify the chemical composition of cement.',
        'describe the method of purification of bauxite;',
        'specify the ores of tin;',
        'relate the method of extraction to its properties;',
        'specify the uses of tin;',
        'identify the general properties of the first transition metals;',
        'deduce reasons for the specific properties of the transition metals;',
        'determine the IUPAC names of simple transition metal complexes;',
        'determine the suitable method of extraction of iron;',
        'specify the properties and uses of iron;',
        'identify the different forms of iron, their compositions, properties and uses;',
        'identify the appropriate method of extraction of copper from its compounds;',
        'relate the properties of copper and its compound to their uses;',
        'specify the method for the preparation of CuSO4;',
        'specify the constituents and uses of the various alloys mentioned; and',
        'compare the properties and uses of alloys to pure metals.',
      ],
    },
    'Organic Compounds': {
      subtopics: [
        'An introduction to the tetravalency of carbon',
        'the general formula',
        'IUPAC nomenclature',
        'the determination of empirical formula of each class of the organic compounds mentioned below',
        'Aliphatic hydrocarbons',
        'Alkanes',
        'Homologous series in relation to physical properties',
        'substitution reaction and a few examples and uses of halogenated products',
        'Isomerism: structural only',
        'examples on isomerism should not go beyond six carbon atoms',
        'Petroleum: composition',
        'fractional distillation and major products',
        'cracking and reforming',
        'Petrochemicals – starting materials of organic syntheses',
        'quality of petrol and meaning of octane number',
        'Alkenes',
        'Isomerism: structural and geometric isomerism',
        'additional and polymerization reactions',
        'polythene and synthetic rubber as examples of products of polymerization and its use in vulcanization',
        'Alkynes',
        'Ethyne – production from action of water on carbides',
        'simple reactions and properties of ethyne',
        'Aromatic hydrocarbons e.g. benzene - structure, properties and uses',
        'Alkanols',
        'Primary, secondary, tertiary',
        'production of ethanol by fermentation and from petroleum by-products',
        'Local examples of fermentation and distillation',
        'e.g. gin from palm wine and other local sources and glycerol as a polyhydric alkanol',
        'Reactions of OH group – oxidation as a distinguishing test among primary, secondary and tertiary alkanols (Lucas test)',
        'Alkanals and alkanones',
        'Chemical test to distinguish between alkanals and alkanones',
        'Alkanoic acids',
        'Chemical reactions',
        'neutralization and esterification',
        'ethanedioic (oxalic) acid as an example of a dicarboxylic acid',
        'benzene carboxylic acid as an example of an aromatic acid',
        'Alkanoates',
        'Formation from alkanoic acids and alkanols – fats and oils as alkanoates',
        'Saponification',
        'Production of soap and margarine from alkanoates and distinction between detergents and soaps',
        'Amines (Alkanamines) Primary, Secondary, and tertiary',
        'Carbohydrates',
        'Classification – mono-, di- and polysaccharides',
        'composition',
        'chemical tests for simple sugars',
        'reaction with concentrated tetraoxosulphate (VI) acid',
        'Hydrolysis of complex sugars e.g. cellulose from cotton and starch from cassava',
        'the uses of sugar and starch in the production of alcoholic beverages, pharmaceuticals and textiles',
        'Proteins',
        'Primary structures',
        'hydrolysis and tests (Ninhydrin, Biuret, Millon’s and xanthoproteic)',
        'Enzymes and their functions',
        'Polymers',
        'Natural and synthetic rubber',
        'addition and condensation polymerization',
        'Methods of preparation, examples and uses',
        'Thermoplastic and thermosetting plastics',
      ],
      objectives: [
        'derive the name of organic compounds from their general formulae;',
        'relate the name of a compound to its structure;',
        'relate the tetravalency of carbon to its ability to form chains of compound (catenation);',
        'classify compounds according to their functional groups;',
        'derive empirical formula and molecular formula, from given data;',
        'relate structure/functional groups to specific properties;',
        'derive various isomeric forms from a given formula;',
        'distinguish between the different types of isomerism;',
        'classify the various types of hydrocarbons;',
        'distinguish each class of hydrocarbons by their properties;',
        'specify the uses of various hydrocarbons;',
        'identify crude oil as a complex mixture of hydrocarbons;',
        'relate the fractions of hydrocarbons to their properties and uses;',
        'relate transformation processes to quality improvement of the fractions;',
        'distinguish between various polymerization processes;',
        'specify the process involved in vulcanization;',
        'specify chemical test for terminal alkynes;',
        'distinguish between aliphatic and aromatic hydrocarbons;',
        'relate the properties of benzene to its structure;',
        'compare the various classes of alkanols;',
        'determine the processes involved in ethanol production;',
        'examine the importance of ethanol as an alternative energy provider;',
        'distinguish the various classes of alkanols;',
        'differentiate between alkanals and alkanones;',
        'compare the various types of alkanoic acids;',
        'identify natural sources of alkanoates;',
        'specify the methods for the production of soap, detergent and margarine;',
        'distinguish between detergent and soap;',
        'compare the various classes of alkanamine;',
        'identify the natural sources of carbohydrates;',
        'compare the various classes of carbohydrates;',
        'infer the products of hydrolysis and dehydration of carbohydrates;',
        'determine the uses of carbohydrates;',
        'specify the tests for simple sugars;',
        'identify the basic structure of proteins;',
        'specify the methods and products of hydrolysis;',
        'specify the various tests for proteins;',
        'distinguish between natural and synthetic polymers;',
        'differentiate between addition and condensation polymerization processes;',
        'classify natural and commercial polymers and their uses; and',
        'distinguish between thermoplastics and thermosetting plastics.',
      ],
    },
    'Chemistry and Industry': {
      subtopics: [
        'Chemical industries',
        'Types',
        'raw materials',
        'relevance',
        'Biotechnology',
      ],
      objectives: [
        'classify chemical industries in terms of products;',
        'identify raw materials for each industry;',
        'distinguish between fine and heavy chemicals;',
        'enumerate the relevance of each of these industries; and',
        'relate industrial processes to biotechnology.',
      ],
    },
  },
} as const

export type ChemistryTopic = keyof typeof CHEMISTRY_CONFIG.topics