export const COMMERCE_CONFIG = {
  name: 'Commerce',
  prefix: 'COM',
  category: 'commercial',
  priority: 3,
  totalQuestions: 40,
  topics: {
    'Commerce': {
      subtopics: [
        'Meaning and scope',
        'Characteristics',
        'Functions',
      ],
      objectives: [
        'differentiate between Commerce and other related subjects;',
        'describe the characteristics of Commerce;',
        'Identify the functions of Commerce.',
      ],
    },
    'Occupation': {
      subtopics: [
        'Meaning and importance',
        'Types (industrial, commercial and services)',
        'Factors that determine choice of occupation',
      ],
      objectives: [
        'State the importance of occupation;',
        'Compare the different types of occupation;',
        'Identify the factors determining the choice of occupation.',
      ],
    },
    'Production': {
      subtopics: [
        'Factors, characteristics and rewards (land, labour, capital and entrepreneur)',
        'Division of Labour and specialization',
        'Types (primary, secondary and tertiary)',
      ],
      objectives: [
        'identify the Factors of Production and their rewards;',
        'distinguish between Division of Labour and Specialization;',
        'classify the types of production.',
      ],
    },
    'Trade': {
      subtopics: [
        'Home Trade',
        'Retail trade:',
        'Types of retailers',
        'Functions of retailers',
        'Factors to be considered in setting up retail trade',
        'Trends in retailing (branding, self -service, vending machines, the use of luncheon, fuel vouchers, etc)',
        'Advantages and disadvantages of retailers',
        'Wholesale trade:',
        'Types of wholesalers (merchant, agent, general, etc)',
        'Functions of wholesalers',
        'Advantages and disadvantages of wholesalers',
        'Foreign trade',
        'Basic issues in foreign trade (balance of trade, balance of payments and counter trade)',
        'Procedures and documents used in export, import and entrepôt trade',
        'Barriers to international trade',
        'Role of Customs and Excise Authority, Ports Authority, etc in foreign trade',
      ],
      objectives: [
        'compare the various types of retailers;',
        'identify the functions of retailers;',
        'highlight the factors in setting up retail trade;',
        'classify modern retailing practices;',
        'identify the advantages and disadvantages of retail business;',
        'classify the types of wholesalers;',
        'discuss the functions of wholesalers;',
        'outline the merits and demerits of the middleman;',
        'analyse the basic issues in foreign trade;',
        'explain the procedures and documents used in foreign trade;',
        'identify the barriers to international trade;',
        'appraise the role of government agencies in foreign trade.',
      ],
    },
    'Purchase and Sale of Goods': {
      subtopics: [
        'Procedure and documentation (enquiry, quotation, order, invoice, proforma invoice, statement of accounts, indent, consular invoice, bill of lading, certificate of origin, consignment note, etc)',
        'Terms of trade (trade discount, quantity discount, cash discount, warranties, C.O.D., C.I.F., F.O.B., and E.O.E.etc)',
        'Terms of payments',
        'Cash - Legal tender',
        'Credit',
        'Types and functions',
        'Merits and demerits',
      ],
      objectives: [
        'examine the procedures and documents used in the purchase and sale of goods;',
        'determine the terms of trade;',
        'distinguish between cash and credit forms of payment;',
        'identify the types of credit;',
        'analyse the merits and demerits of credit transactions.',
      ],
    },
    'Aids-to-trade': {
      subtopics: [
        'Advertising:',
        'Types and media',
        'Advantages and disadvantages',
        'Banking:',
        'Types of bank',
        'Services',
        'Challenges',
        'Communication:',
        'Process and procedure',
        'Types',
        'Trends',
        'Merits and demerits',
        'Barriers',
        'Insurance:',
        'Types',
        'Principles',
        'Terms',
        'Importance',
        'Tourism:',
        'Importance',
        'Agencies that promote tourism in Nigeria',
        'Challenges',
        'Transportation:',
        'Mode',
        'Importance',
        'Advantages and disadvantages',
        'Warehousing:',
        'Importance',
        'Types and functions',
        'Factors to be considered in siting a warehouse',
      ],
      objectives: [
        'identify the different types of advertising and its media;',
        'analyse the advantages and disadvantages of advertising;',
        'categorize the different types of bank;',
        'assess the services rendered by banks;',
        'identify the challenges facing banks;',
        'assess the different stages in the communication process;',
        'analyse the types of communication;',
        'appraise the contributions of courier services, GSM, etc., to businesses;',
        'state the merits and demerits of communication;',
        'outline the barriers to communication',
        'describe the types of insurance;',
        'apply the principles of insurance to life situations;',
        'explain the terms in insurance;',
        'state the importance of insurance;',
        'examine the importance of tourism;',
        'identify the agencies that promote tourism in Nigeria;',
        'analyse the challenges facing tourism in Nigeria;',
        'appraise the relevance of the various modes of transportation;',
        'list the importance of transportation;',
        'discuss the advantages and disadvantages of transportation;',
        'highlight the importance of warehousing;',
        'appraise the contributions of warehouses to businesses.',
        'evaluate the factors that determine the siting of warehouses.',
      ],
    },
    'Business Units': {
      subtopics: [
        'Forms and features (Sole Proprietorship, Partnership, Limited Liability Companies, Public Corporations, Cooperative Societies, etc.)',
        'Registration of businesses',
        'Business Mergers',
        'Determination of choice of business units',
        'Dissolution and liquidation',
        'Merits and demerits',
      ],
      objectives: [
        'identify the forms and features of business units;',
        'analyse the procedures for registering businesses;',
        'appraise the different forms of business mergers and the reasons for merging;',
        'examine the factors which determine the choice of business units;',
        'differentiate between dissolution and liquidation of business;',
        'state the merits and demerits of business units.',
      ],
    },
    'Financing Business': {
      subtopics: [
        'Sources of finance (personal savings, sale of shares and bonds, loans, debentures, mortgage, bank overdraft, ploughing back of profit, credit purchase, leasing, etc.)',
        'Types of capital (share capital, capital owned, authorized capital, issued capital, called-up capital, paid-up capital, liquid capital, working capital and owners’ equity)',
        'Calculation of forms of capital, profits (gross and net) and turnover',
        'Problems of sourcing finance',
        'The role of Bureau de change in an economy',
      ],
      objectives: [
        'identify the various ways of financing a business;',
        'discuss the different types of capital',
        'compute the different forms of capital, profits and turnover;',
        'appraise the problems associated with sourcing finances for business;',
        'assess the role of Bureau de change in an economy.',
      ],
    },
    'Trade Associations': {
      subtopics: [
        'Objectives and functions of trade and manufacturer’s associations (Cocoa Farmers’ Association, Garri Sellers’ Association, Poultry Farmers’ Association, etc.)',
        'Objectives and functions of Chambers of Commerce.',
      ],
      objectives: [
        'discuss the objectives and functions of trade and manufacturer’s associations;',
        'list the objectives and functions of Chambers of Commerce.',
      ],
    },
    'Money': {
      subtopics: [
        'Evolution',
        'Forms and qualities',
        'Functions',
      ],
      objectives: [
        'discuss the origin of money;',
        'analyse the forms and qualities of money;',
        'appraise the functions of money.',
      ],
    },
    'Stock Exchange': {
      subtopics: [
        'Importance and functions',
        'Types of securities (stocks, shares, bonds, debentures, etc)',
        'Procedure of transactions and speculations',
        'Second-Tier Securities Market, (listing requirements, types of companies for the market, advantages and operating regulations of the market.)',
      ],
      objectives: [
        'state the importance and functions of the Stock Exchange;',
        'identify the different securities traded on the Stock Exchange;',
        'analyse the procedure of transactions and speculations on the Stock Exchange;',
        'appraise the advantages and operating regulations of the market.',
      ],
    },
    'Elements of Business Management': {
      subtopics: [
        'Functions (planning, organizing, staffing, coordinating, motivating, communicating, controlling etc.)',
        'Principles (span of control, unity of command, delegation of authority, etc.)',
        'Organizational structure (line, line and staff, functional, matrix and committee)',
        'Functional areas of business (production, marketing, finance and personnel)',
        'Business resources (man, money, materials, machines and opportunities/goodwill)',
      ],
      objectives: [
        'appraise the functions of management;',
        'analyse the principles of management;',
        'identify organizational structures;',
        'assess the functional areas of business;',
        'examine the business resources.',
      ],
    },
    'Elements of Marketing': {
      subtopics: [
        'Importance and Functions',
        'The marketing concept (consumer orientation, customer satisfaction, integrated marketing, etc)',
        'Marketing mix (product, price, place and promotion)',
        'Market Segmentation',
        'Public relations and Customer Service.',
      ],
      objectives: [
        'highlight the importance and functions of marketing;',
        'discuss the marketing concept;',
        'assess the elements of marketing mix;',
        'explain market segmentation;',
        'examine public relations and customer service.',
      ],
    },
    'Legal Aspects of Business': {
      subtopics: [
        'Meaning and validity of a simple contract',
        'Agency, Sale of Goods Act and Hire Purchase Act',
        'Contract of employment',
        'Government regulations of business (registration of business, patents, trademarks, copyrights, etc)',
        'Consumer protection (Government legislation, Standards Organization Trade Descriptions Act, Consumer Protection Council, NAFDAC, NDLEA, Customs and Excise, etc.)',
        'Regulatory agencies.',
      ],
      objectives: [
        'analyse the elements and validity of a simple contract;',
        'examine Agency, Sale of Goods Act and Hire Purchase Act;',
        'assess the rights and obligations of employers and employees;',
        'distinguish between patents, trademarks and copyrights;',
        'identify the functions of consumerism;',
        'assess the relevance of regulatory agencies and acts in the provision of safe goods and drugs.',
      ],
    },
    'Information and Communication Technology (ICT)': {
      subtopics: [
        'Computer:',
        'Appreciation and application',
        'Types and functions',
        'Merits and demerits',
        'Challenges',
        'Terms (Internet, Intranet, browsing, password, e-mail, google, yahoo, search, Local Area Network, etc.)',
        'Activities:',
        'e-commerce',
        'e-banking',
        'e-business',
      ],
      objectives: [
        'discuss computer appreciation and application;',
        'enumerate the types and functions of computer;',
        'analyse the merits and demerits of ICT;',
        'appraise the challenges of using the computer;',
        'identify the different terms used in ICT;',
        'evaluate the trends in ICT.',
      ],
    },
    'Business Environment and Social Responsibility': {
      subtopics: [
        'Legal, political, economic, social, cultural, technological environments, etc',
        'Safe products, philanthropic and societal consideration',
        'Types and implication of pollution (water, air, land, etc.)',
      ],
      objectives: [
        'discuss the types of business environment;',
        'assess the role of social environment in the provision of safe products;',
        'identify the different types of pollution and their implications on businesses.',
      ],
    },
  },
} as const

export type CommerceTopic = keyof typeof COMMERCE_CONFIG.topics