export const COMPUTER_STUDIES_CONFIG = {
  name: 'Computer Studies',
  prefix: 'CST',
  category: 'science',
  priority: 6,
  totalQuestions: 40,
  topics: {
    'Evolution of Computing': {
      subtopics: [
        'History of computing',
        'Pre-Computing Age - 19th century',
        'Features and components early computing devices',
        'Computing Devices - 20th Century',
        'The history behind each device',
        'Classification of computing devices',
        'By Generation',
        'By Size',
        'By Purpose',
        'By Type',
      ],
      objectives: [
        'Identify the various computing devices since the beginning of counting/computing',
        'Discuss the contributions and uses of each of the founders of these devices:',
        'Relate each generation with its characteristic feature.',
        'Describe each generation under the following:',
        'Explain the differences in the classification of computing systems by size (micro, mini, mainframe, and super)',
        'Differentiate among the various types of modern computer systems in respect of sizes and basic components, data and usage',
        'State the importance and use of these computing systems',
      ],
    },
    'Fundamentals of Computing': {
      subtopics: [
        'Overview of Computing Systems',
        'Two main constituents of a computer (hardware and software)',
        'Characteristics of computers',
        'Type, examples and uses of computer hardware',
        'Logic Circuits',
        'Types, examples and uses of software',
        'Data and Information',
        'Differences between Data and Information',
        'Data representation',
        'Methods of Digitisation',
      ],
      objectives: [
        'Define Computer system in relation to its nature and programmability',
        'List functional parts of computer systems',
        'Explain the characteristics of computers (Electronic, Accuracy, Speed, interactive, Reliability, Consistency, Large Storage etc.)',
        'Identify the differences between hardware and software',
        'Define and give examples of hardware devices',
        'List components of computer hardware, their functions and different types -Central Processing Unit, Peripherals (Input and Output devices) and Storage media',
        'Explain the differences between input and output devices',
        'Explain the functions of major input devices and give examples of the major input devices',
        'Explain the classification of keys on the keyboard (function, numeric, alphabetic, cursors.',
        'Explain the features, functions and operations of the mouse',
        'Explain the differences among keyboard, mouse, light pen and scanner, digital camera and output devices',
        'Define and give examples of output devices (monitor, printer, speaker, plotters)',
        'List the different types, features and uses of each output device above.',
        'Explain the similarities and differences among inkjet, laser and line printers',
        'List the components of CPU – Arithmetic and Logic Unit (ALU), Control Unit (CU) and Registers.',
        'Explain the functions of ALU, CU and Registers.',
        'Distinguish between Primary and Secondary Memory (Storage) units',
        'List the components of Primary Memory Unit (Random Access Memory (RAM), Read Only Memory (ROM))',
        'Explain the uses and differences between RAM and ROM',
        'Explain the functions of secondary (auxiliary) storages',
        'List different types of secondary storages',
        'Give examples of secondary storages (Floppy disks, magnetic tape, hard disks, compact disk (CD), Digital Video Disk (DVD),USB, etc.)',
        'Carry out comparative analysis of auxiliary storage devices in respect of size, speed, cost and technology (access mode, component, etc.).',
        'List different units by which storage are measured and their relationships - bits, bytes, nibbles, words, kilobytes, megabytes, gigabytes, terabytes etc.',
        'Relate the relationships between Micro, Mega, Giga, and Terra bytes.',
        'Define',
        'Explain the functions of the following Registers:',
        'Explain the differences between register and main memory',
        'State the major steps involved in how a computer converts data to required information (Input – Process – Output)',
        'Enumerate factors affecting speed of data transfer (bus speed and bus width)',
        'Define different type types and uses of gates:',
        'Interpret Logic equations for AND, NOT and OR gates',
        'List the symbols of AND, NOT and OR gates',
        'Construct Truth Table for standard logic gates – AND, NOT, OR. gates',
        'Define comparator',
        'Construct a simple comparator with XOR (Exclusive OR) and NOR gate',
        'Differentiate between system and application software.',
        'List different types of System software (Operating Systems, Utility Software, Middleware, Device Drivers, Translators, etc.)',
        'Define Operating System (OS)',
        'List functions of OS',
        'List different types of OS User Interfaces (Text (Command Line and Menu) and Graphical User Interface (GUI))',
        'Give examples of Operating Systems (MS Windows, LINUX, UNIX, etc.)',
        'Discuss different OS on phones, iPad (Android, Blackberry, iPhone, etc.)',
        'Define Utility Software',
        'List functions of Utility Software',
        'List different types of Utility Software',
        'Give examples of Utility Software (Editors, Anti-Virus, etc.)',
        'Define Translators',
        'Explain the functions of Translator Software',
        'List the different categories of translators (Interpreter, Assembler and Compiler)',
        'Explain the differences among the categories of translators.',
        'List examples of application software and their usage',
        'Differentiate between open source and proprietary software',
        'Different methods of acquiring Application software (Built in house and Off the Shelf)',
        'Explain the differences between User Application program and general-purpose Application packages',
        'Give examples of common off the Shelf Application packages and their examples.',
        'Define data and information',
        'List properties of information',
        'List different types of data types (integers, real numbers, strings, multimedia (image, audio/visual, signal etc.)',
        'Identify ways of representing and handling data, that is number bases with special reference to binary, decimal, hexadecimal etc.',
        'Define digitization',
        'Explain the process of digitalization(manual, heads-up, interactive tracing, automatic)',
        'List different formats of digitized data (image, audio, video, motion, text, multimedia, etc.)',
      ],
    },
    'Computer Application Packages': {
      subtopics: [
        'Word Processing package',
        'General concept',
        'Creating and saving documents',
        'Editing, formatting and insertion',
        'Printing',
        'MS Word',
        'Features',
        'Launch MS Word',
        'Basic operations',
        'Other operations',
        'Spreadsheet package',
        'MS Excel',
        'Database package',
        'Definition of Database and examples of database packages',
        'Database organizations',
        'Different features of database format',
        'Basic operations of Database using MS Access',
        'Create database using MS Access',
        'Carry out operations on existing database using MS Access',
        'Graphics Package',
        'Definitions and examples of Graphic packages',
        'Features of CorelDraw',
        'Simple design using CorelDraw',
        'Presentation Package',
        'Definition of Presentation package and examples of Presentation packages',
        'PowerPoint',
        'Features of PowerPoint Environment',
        'Steps in activating an existing PowerPoint',
        'PowerPoint operations',
        'Web Design Package',
        'Definition and examples of Web Design Packages',
        'Uses Web Design Packages',
        'Elements of Web design using Dreamview',
      ],
      objectives: [
        'Define word processing, and give examples of word processing packages. (MS Word, WordStar, WordPerfect, Open Word, etc.,)',
        'Identify features of Word Processing packages in general (create, save, edit, insert, print, share etc.)',
        'List the application areas of Word Processing packages (Office, Publishing, Journalism, Education, etc.)',
        'Launch effectively MS word.',
        'Perform MS Word basic operations',
        'Use different types and sizes of fonts',
        'Perform MS Word operations of:',
        'Close MS Word.',
        'Define Spreadsheet and give examples of Spreadsheet packages. (MS Excel, VisiCalc SuperCalc, SPSS, Calc etc.)',
        'Identify features of Spreadsheet packages in general (Environment, Status bar, menu bar, formula bar, etc.)',
        'List the application areas of Spreadsheet packages (Accounting, Engineering, Statistics, Calculation, what- if -scenarios, Education, etc.)',
        'Launch effectively MS Excel.',
        'Define basic terms in MS Excel',
        'Use MS Excel to:',
        'Use data types in MS Excel (Number, Labels, Formula etc.)',
        'Perform basic operations in MS excel',
        'Perform arithmetic calculations using formula and inbuilt functions, etc.',
        'Use different types and sizes of fonts',
        'Perform additional MS Excel operations (Formatting, Editing, Printing, Drawing charts etc.)',
        'Close MS Excel.',
        'Define Database and give examples of Database packages. (Dbase, Foxbase, MS Access, Oracle, etc.)',
        'Define basic database terms (File, Record, Field, key, form, table, etc.)',
        'List and explain different types of database organisation (Hierarchical, Network and Relational.)',
        'List the application areas of Database in different organizations (Office, Home, Education, Government, Hospital, Agriculture, etc.)',
        'Explain different features of database format in MS Access:',
        'Carry out steps to create a database in MS Access to:',
        'carry out basic operations on an already created MS Access database:',
        'Close the MS Access database.',
        'Define Graphics and give examples of Graphic packages (Paint, Harvard Graphics, Photoshop, CorelDraw, Autocad etc)',
        'Explain features of CorelDraw (LiveSketch Tool, Multi-Monitor, Healing Clone Tools, Copy Curve Segments, Gaussian Blur Feature, Touch-Friendly GU Interface, Powerful Stylus Enhancements, Import Legacy Workspaces, Prominent Interactive Sliders, Custom Node Shapes, Font Filtering and Search, Corel Font Manager, Enhanced Vector Previews, Handles and Node etc.)',
        'Use features of CorelDraw to activate existing CorelDraw file',
        'Use CorelDraw to design',
        'Define Presentation and give examples of Presentation packages (MS PowerPoint, Windows Movie Maker, Micromedia Flash, impress, Apple keynotes, etc.)',
        'Explain features of PowerPoint Environment (Animation Painter, Video Editor, create a video of you presentation, Automatic Ribbons Toolbars, Transitions, Sections, Cropped Tool, Mask Feature, Effective Preview, Screen Shot, Smart Guides,)',
        'Explain steps in activating a PowerPoint presentation',
        'Perform PowerPoint operations to:',
        'Define and Give examples of Web design package (HTML, XML, Dreamweaver, Rapidweaver, Google Web Designer, Microsoft Sharepoint Designer, Net Object Fusion, Xara Web Designer etc.)',
        'List Elements of Web Design',
        'Use Dreamweaver for:',
      ],
    },
    'Managing Computer Files': {
      subtopics: [
        'Concept of Computer Files',
        'Definitions of basic terms',
        'File organisations',
        'Methods of accessing files',
        'File classifications',
        'Criteria for classifying files',
        'Handling Computer Files',
        'Basic operations',
        'Data Loss',
        'Security',
        'Computer versus manual files',
      ],
      objectives: [
        'Define some basic terms (File, record, field, data item etc.).',
        'Identify and use of basic data types (numeric, alphabetic, and alphanumeric)',
        'Explain the relationship among file structure items (Data item – field - record-file-database)',
        'Classify files according to how they are organised. (Serial, Sequential, Index and random)',
        'Access files as appropriate (Serial, Sequential and Random).',
        'Classify files into:',
        'Explain the criteria used in classifying files',
        'Perform basic file operations',
        'Identify causes of data loss',
        'Use different methods of securing data and maintaining its integrity',
        'Compare the advantages and disadvantages of computer and manual file (security, speed of access and creation, cost of setup and maintenance, electricity supply, etc.)',
      ],
    },
    'Computer Maintenance and Safety Measures': {
      subtopics: [
        'Booting and shutting down process',
        'Computer Maintenance',
        'Computer Room Management',
      ],
      objectives: [
        'Define booting',
        'List the two types of booting process (cold and warm booting)',
        'Explain the difference between cold and warm booting.',
        'Explain the steps involved in booting and shutting down a computer system',
        'Perform general cleaning of the computer system',
        'Charge and replace battery for portable systems and UPS',
        'Clean drive lens',
        'Perform simple hardware and software maintenance',
        'Recover data from a crashed system',
        'Define proper sitting arrangement',
        'Position the monitor, keyboard, CPU, Mouse and other peripherals appropriately',
        'Ensure Proper illumination of the computer room',
        'Maintain a dust free environment',
        'Keep liquid away from computer room',
        'Keep strictly to laboratory rules and regulations',
      ],
    },
    'Information & Communication Technology (ICT)': {
      subtopics: [
        'Communication Systems',
        'Definitions and Acronym of ICT',
        'Types and examples of ICT',
        'Application areas of ICT',
        'Application areas',
        'ICT based Devices',
        'Internet',
        'Definition of terms',
        'Internet Browsers',
        'Features of Internet Browsers',
        'Internet Services',
        'Electronic Mail',
        'Definition',
        'E-mail Service',
        'Steps involved in creating and opening mail (email box, and chatting)',
        'Features of e-mail address',
        'Networking',
        'Definitions',
        'Network types',
        'Network topologies',
        'Network devices',
        'World Wide Web (www)',
        'Definition and full meanings of acronyms',
        'Brief history of WWW',
        'Basic terminologies',
        'Protocols',
        'Advantages and disadvantages of www.',
        'Navigation through websites',
        'Software for web development',
        'Differences between email and website',
        'Cables and Connectors',
        'Network cables and connectors',
        'Computer cables and connectors',
      ],
      objectives: [
        'State the full meaning of the acronym ICT',
        'Define ICT',
        'List types of ICT.',
        'Give examples of Broadcasting',
        'List types of Telecommunications',
        'List types of Data Network',
        'List types of Information System',
        'Define Applications Areas of ICT:',
        'List types of ICT Devices:',
        'Define Internet',
        'Define and illustrate use of:',
        'Access the Internet through any of the browsers',
        'Explain features of the Internet Browsers',
        'Describe the use of different types of Internet services:',
        'Define Electronic Mail and Chatting',
        'List e-mail services:',
        'Explain the features in an e-mail address e.g. xyz@jamb.org.ng (user@Domainname) Explain the components of domain name.',
        'Define computer network',
        'List and define various types of Networks:',
        'Explain the differences in basic network topologies:',
        'Define and explain the use of network devices:',
        'Give full meanings of www, HTTP, HTTPS, HTML, XML',
        'Explain the history behind www',
        'Explain basic terminologies:',
        'Define Protocol and list different types of protocols (http, https, ftp, etc.)',
        'List uses and benefits of www.',
        'List disadvantages of www',
        'Navigate through websites.',
        'Use of software for web development',
        'Differentiate between email and website',
        'Identify different network cables and connectors:',
        'Identify different types of Computer Cables and Connectors',
      ],
    },
    'Developing Problem-Solving Skills': {
      subtopics: [
        'Programming Language (PL)',
        'Definition and Classification of PL',
        'Advantages and disadvantages of different levels of PL',
        'High Level Languages (HLL)',
        'Classifications of HLL',
        'Characteristics of HLL',
        'Translators',
        'Algorithm and Flowcharts',
        'Definitions',
        'Functions of Algorithm',
        'Properties of Algorithm',
        'Flowchart symbols',
        'Programming Language Structure',
        'Basic Statements',
        'Arithmetic/string operators',
        'Subunits',
        'Primitive and non-primitive data',
        'Program Development',
        'Definition',
        'Characteristics of programs',
        'Precautions',
        'Steps involved in developing program',
        'System Development Life Cycle (SDLC)',
        'Definition of SDCL',
        'Stages of SDLC',
      ],
      objectives: [
        'Define Programming Language (PL)',
        'Identify different classifications of PL.',
        'Give advantages and disadvantages of Machine Language, Assembly Language and High programming Language.',
        'Classify High-Level programming Languages into:',
        'Explain the characteristics of High Level Programming Languages:',
        'Define translators and its two basic types:',
        'Define Algorithm and Flowchart',
        'State functions of algorithms: They are used to perform:',
        'State and explain the properties of Algorithm',
        'Identify Flowchart symbols',
        'Draw Flowchart of a given programming problem',
        'Identify features/syntax of a programming language',
        'Basic statements of a high-level programming language',
        'Arithmetic operators and expressions',
        'String operators and expressions',
        'Built in functions',
        'Primitive data (Integer, float, Boolean, character, etc.)',
        'Non-Primitive Data Types (Arrays, classes, string, etc.)',
        'Complex data structures (Trees, graphs, linked lists, objects etc.)',
        'Define a program',
        'List characteristics of a good program',
        'State the precautions required in the development of a program',
        'Steps involved in program development',
        'Examples of:',
        'Define SDLC',
        'Describe SDLC',
        'Explain stages in SDLC',
        'Draw diagram of a SDLC',
      ],
    },
    'Artificial Intelligence (AI) and Robotics': {
      subtopics: [
        'Definition of AI',
        'Branches of AI',
        'Applications of AI',
        'Fundamentals of Robotics',
        'Definition of Robotics',
        'Main Components of Robotics',
        'Types of Robots',
        'Application Areas of Robotics',
        'Advantages and Disadvantages of Robots',
      ],
      objectives: [
        'Define AI',
        'Identify branches of AI',
        'List Application Areas of AI',
        'Define Robotics',
        'Define Robots',
        'Identify main components of Robots',
        'Mention types of Robots',
        'Itemise application areas of Robots',
        'State advantages and disadvantages of using Robots',
      ],
    },
    'Computer Ethics and Human Issues': {
      subtopics: [
        'Ethical issues',
        'Computer–related crime',
        'Responsibility for computer failure',
        'Protection of computer property, records and software',
        'Privacy of the company, workers and customers.',
        'Computer Security',
        'Cyber risks and protection',
        'Potentials for Higher Studies in Computing',
      ],
      objectives: [
        'Define computer-related crime.',
        'State examples of computer-related crime.',
        'List methods to prevent unauthorised use of computer system (user identification, Passwords etc.)',
        'List methods to protect computer resources using both electronic and manual methods.',
        'List methods to Protect privacy of individuals (workers, companies, customers, government etc.) by law and electronically.',
        'Define computer security',
        'Identify different types of computer security and their characteristics.',
        'Identify appropriate security tool to use for the different types of computer security (Firewalls, antivirus software, encryption, etc.)',
        'Identify categories of application threats and their characteristics (Input, authorisation, session management, parameter tampering,',
        'Identify basic dimensions of Information Security (Confidentiality, Integrity, and Availability (CIA))',
        'Mention Network security Issues',
        'Mention Network security methods (antivirus software, application security, behavioural analytics, data loss prevention, email security, firewalls, mobile device security, network segmentation, security and event management (SEIM), Virtual Private Network (VPN), Web security, wireless security, Network Access Control (NAC).',
        'List Types of cyber security threats',
        'List Cyber security safety tips',
        'List possible career paths in computing',
      ],
    },
  },
} as const

export type ComputerStudiesTopic = keyof typeof COMPUTER_STUDIES_CONFIG.topics