export const ECONOMICS_CONFIG = {
  name: 'Economics',
  prefix: 'ECO',
  category: 'commercial',
  priority: 2,
  totalQuestions: 40,
  topics: {
    'Economics as a science': {
      subtopics: [
        'Basic Concepts:',
        'wants, scarcity, choice, scale of preference, opportunity cost, rationality, production, distribution, consumption.',
        'Economic problems of:',
        'what, how and for whom to produce and efficiency of resource use.',
        'Application of PPF to solution of economic problems.',
      ],
      objectives: [
        'compare various concepts in economics and their applications;',
        'interpret graphs/schedules in relation to the concepts;',
        'identify economic problems;',
        'proffer solutions to economic problems',
      ],
    },
    'Economic Systems': {
      subtopics: [
        'Types and characteristics of free enterprise, centrally planned and mixed economies',
        'Solutions to economic problems under different systems',
        'Contemporary issues in economic systems (economic reforms e.g deregulation, banking sector consolidation, cash policy reform).',
      ],
      objectives: [
        'compare the various economic systems;',
        'apply the knowledge of economic systems to contemporary issues in Nigeria',
        'proffer solutions to economic problems in different economic systems.',
      ],
    },
    'Methods and Tools of Economic Analysis': {
      subtopics: [
        'Scientific Approach:',
        'inductive and deductive methods',
        'positive and normative reasoning',
        'Basic Tools',
        'tables, charts and graphs',
        'measures of central tendency: mean, median and mode, and their applications.',
        'measures of dispersion; variance, standard deviation, range and their applications;',
        'merits and demerits of the tools.',
      ],
      objectives: [
        'distinguish between the various forms of reasoning;',
        'apply these forms of reasoning to real life situations;',
        'use the tools to interpret economic data;',
        'analyse economic data using the tools;',
        'understand the merits and demerits of the tools.',
      ],
    },
    'The Theory of Demand': {
      subtopics: [
        'meaning and determinants of demand',
        'demand schedules and curves',
        'the distinction between change in quantity demanded and change in demand.',
        'Types of demand:',
        'Composite, derived, competitive and joint demand:',
        'Types, nature and determinants of elasticity and their measurement - price, income and cross elasticity of demand:',
        'Importance of elasticity of demand to consumers, producers and government.',
      ],
      objectives: [
        'identify the factors determining demand;',
        'interpret demand curves from demand schedules;',
        'differentiate between change in quantity demanded and change in demand;',
        'compare the various types of demand and their interrelationships;',
        'relate the determinants to the nature of elasticity;',
        'compute elasticities;',
        'interpret elasticity coefficients in relation to real life situations.',
      ],
    },
    'The Theory of Consumer Behaviour': {
      subtopics: [
        'Basic Concepts:',
        'utility (cardinal, ordinal, total average and marginal utilities)',
        'indifference curve and budget line.',
        'Diminishing marginal utility and the law of demand.',
        'Consumer equilibrium using the indifference curve and marginal analyses.',
        'Effects of shift in the budget line and the indifference curve.',
        'Consumer surplus and its applications.',
      ],
      objectives: [
        'explain the various utility concepts;',
        'apply the law of demand using the marginal utility analysis;',
        'use indifference curve and marginal analyses to determine consumer equilibrium;',
        'relate the income and substitution effects;',
        'apply consumer surplus to real life situations.',
      ],
    },
    'The Theory of Supply': {
      subtopics: [
        'Meaning and determinants of supply',
        'Supply schedules and supply curves',
        'the distinction between change in quantity supplied and change in supply',
        'Types of Supply:',
        'Joint/complementary, competitive and composite',
        'Elasticity of Supply:',
        'determinants, measurements, nature and applications',
      ],
      objectives: [
        'identify the factors determining supply;',
        'interpret supply curves from supply schedules;',
        'differentiate between change in quantity supplied and change in supply;',
        'compare the various types of supply and their interrelationships;',
        'relate the determinants to the nature of elasticity;',
        'compute elasticity coefficients;',
        'interpret the coefficients in relation to real life situations.',
      ],
    },
    'The Theory of Price Determination': {
      subtopics: [
        'The concepts of market and price',
        'Functions of the price system',
        'Equilibrium price and quantity in product and factor markets',
        'Price legislation and its effects',
        'The effects of changes in supply and demand on equilibrium price and quantity.',
      ],
      objectives: [
        'explain the concepts of market and price;',
        'examine the functions of the price system;',
        'evaluate the effects of government interference with the price system;',
        'differentiate between minimum and maximum price legislation;',
        'interpret the effects of changes in supply and demand on equilibrium price and quantity.',
      ],
    },
    'The Theory of Production': {
      subtopics: [
        'Meaning and types of production',
        'Concepts of production and their interrelationships (TP, AP, MP and the law of variable proportion).',
        'Division of labour and specialization',
        'Scale of Production:',
        'Internal and external economies of scale and their implications.',
        'Production functions and returns to scale',
        'Producers’ equilibrium isoquant-isocost and marginal analyses.',
        'Factors affecting productivity.',
      ],
      objectives: [
        'relate TP, AP and MP with the law of variable proportion;',
        'compare internal and external economies of scale in production and their effects;',
        'identify the types of production functions',
        'compare the different types of returns to the scale and their implications;',
        'determine the firm’s equilibrium position using the isoquant-isocost and marginal analyses.',
        'identify the factors affecting productivity.',
      ],
    },
    'Theory of Costs and Revenue': {
      subtopics: [
        'The concepts of cost:',
        'Fixed, Variable, Total Average and Marginal',
        'The concepts of revenue: Total, Average and Marginal revenue;',
        'Accountants’ and Economists’ notions of cost',
        'Short-run and long-run costs',
        'The marginal cost and the supply curve of firm.',
      ],
      objectives: [
        'explain the various cost concepts',
        'differentiate between accountants’ and economists’ notions of costs',
        'interpret the short-run and long-run costs curves',
        'establish the relationship between marginal cost and supply curve.',
        'explain the various revenue concepts.',
      ],
    },
    'Market Structures': {
      subtopics: [
        'Perfectly competitive market:',
        'Assumptions and characteristics;',
        'Short-run and long-run equilibrium of a perfect competitor;',
        'Imperfect Market:',
        'Pure monopoly, discriminatory monopoly and monopolistic competition.',
        'Short-run and long-run equilibrium positions.',
        'Break-even/shut-down analysis in the various markets.',
      ],
      objectives: [
        'analyse the assumptions and characteristics of a perfectly competitive market;',
        'differentiate between short-run and long-run equilibrium of a perfectly competitive firm;',
        'analyse the assumptions and characteristics of imperfect markets;',
        'differentiate between the short-run and long-run equilibria of imperfectly competitive firms;',
        'establish the conditions for the break-even/shut down of firms.',
      ],
    },
    'National Income': {
      subtopics: [
        'The Concepts of GNP, GDP, NI, NNP',
        'National Income measurements and their problems',
        'Uses and limitations of national income estimates',
        'The circular flow of income (two and three-sector models)',
        'The concepts of consumption, investment and savings',
        'The multiplier and it effects',
        'Elementary theory of income determination and equilibrium national income.',
      ],
      objectives: [
        'identify the major concepts in national income;',
        'compare the different ways of measuring national income;',
        'examine their problems;',
        'determine the uses and limitations of national income estimates;',
        'interpret the circular flow of income using the two and three-sector models;',
        'calculate the various multipliers;',
        'evaluate their effects on equilibrium national income;',
        'explain the concepts of consumption, investment and savings.',
      ],
    },
    'Money and Inflation': {
      subtopics: [
        'Types, characteristics and functions of money',
        'Demand for money and the supply of money',
        'Quantity Theory of money (Fisher equation)',
        'The value of money and the price level',
        'Inflation: Types, measurements, effects and control',
        'Deflation: Measurements, effects and control.',
      ],
      objectives: [
        'explain between the types, characteristics and functions of money;',
        'identify the factors affecting the demand for and the supply of money;',
        'examine the relationship between the value of money and the price level;',
        'identify the components in the quantity theory of money;',
        'examine the causes and effects of inflation;',
        'calculate the consumer price index;',
        'interpret the consumer price index;',
        'examine ways of controlling inflation.',
        'examine the causes, measurement, effects and control of deflation.',
      ],
    },
    'Financial Institutions': {
      subtopics: [
        'Types and functions of financial institutions (traditional, central bank, mortgage banks, merchant banks, insurance companies, building societies);',
        'The role of financial institutions in economic development;',
        'Money and capital markets',
        'Financial sector regulations',
        'Deposit money banks and the creation of money',
        'Monetary policy and its instruments',
        'Challenges facing financial institutions in Nigeria.',
      ],
      objectives: [
        'identify the types and functions of financial institutions;',
        'explain the roles of financial institutions in economic development;',
        'distinguish between the money and capital markets;',
        'identify the various financial sector regulators and their functions;',
        'explain the money creation process and its challenges;',
        'examine the various monetary policy instruments and their effects;',
        'appraise the challenges facing the financial institutions in Nigeria.',
      ],
    },
    'Public Finance': {
      subtopics: [
        'Meaning and objectives',
        'Fiscal policy and its instruments',
        'Sources of government revenue (taxes royalties, rents, grants and aids)',
        'Principles of taxation',
        'Tax incidence and its effects',
        'The effects of public expenditure',
        'Government budget and public debts',
        'Revenue allocation and resource control in Nigeria.',
      ],
      objectives: [
        'identify the objectives of public finance;',
        'explain fiscal policy and its instruments;',
        'compare the various sources of government revenue;',
        'analyse the principles of taxation;',
        'analyse the incidence of taxation and its effects;',
        'examine the effects of public expenditure on the economy;',
        'examine the types and effects of budgets;',
        'highlight the criteria for revenue allocation in Nigeria and their impact.',
      ],
    },
    'Economic Growth and Development': {
      subtopics: [
        'Meaning and scope',
        'Indicators of growth and development',
        'Factors affecting growth and development',
        'Problems of development in Nigeria',
        'Development planning in Nigeria.',
      ],
      objectives: [
        'distinguish between economic growth and development;',
        'highlight the indicators of growth and development;',
        'identify the factors affecting growth and development;',
        'examine the problems of development in Nigeria;',
        'examine the role of planning in development;',
      ],
    },
    'Agriculture in Nigeria': {
      subtopics: [
        'Types and features;',
        'The role of agriculture in economic development;',
        'Problems of agriculture;',
        'Agricultural policies and their effects;',
        'Instability in agricultural incomes (causes, effects and solutions).',
      ],
      objectives: [
        'identify the types and features of agriculture;',
        'examine the characteristics and problems of agriculture;',
        'assess the role of agriculture in economic development;',
        'appraise agricultural policies in Nigeria;',
        'evaluate the causes and effects of instability in agricultural incomes.',
      ],
    },
    'Industry and Industrialization': {
      subtopics: [
        'Concepts and effects of location and localization of industry in Nigeria;',
        'Strategies and Industrialization in Nigeria;',
        'Industrialization and economic development in Nigeria;',
        'Funding and management of business organization;',
        'Factors determining the size of firms.',
      ],
      objectives: [
        'differentiate between location and localization of industry;',
        'identify the factors influencing the location and localization of industry;',
        'examine the problems of industrialization;',
        'appraise some industrialization strategies;',
        'examine the role of industry in economic development.',
      ],
    },
    'Natural Resources and the Nigerian Economy': {
      subtopics: [
        'Development of major natural resources (petroleum, gold, diamond, timber etc);',
        'Contributions of the oil and the non-oil sectors to the Nigerian economy;',
        'Linkage effects;',
        'Upstream/downstream of the oil sector;',
        'The role of NNPC and OPEC in the oil sector;',
        'Challenges facing natural resources exploitation.',
      ],
      objectives: [
        'trace the development of the major natural resources in Nigeria;',
        'understand the contribution of the oil and the non-oil sectors to the Nigerian economy;',
        'establish the linkages between the natural resources and other sectors;',
        'analyse the environmental effects of exploitation activities in Nigeria;',
        'distinguish between the upstream and downstream activities in the oil sector;',
        'examine the roles of NNPC and OPEC in the oil sector;',
        'suggest ways of controlling the effects of natural resources exploitation.',
      ],
    },
    'Business Organizations': {
      subtopics: [
        'Private enterprises (e.g. sole-proprietorship, partnership, limited liability companies and cooperative societies)',
        'Problems of private enterprises;',
        'Public enterprises and their problems;',
        'Funding and management of business organizations;',
        'Factors determining the size of firms;',
        'Privatization and Commercialization as solutions to the problems of public enterprises.',
      ],
      objectives: [
        'compare the types and basic features of private business organization;',
        'appreciate the financing and management problems of business organizations;',
        'identify the features of public enterprises;',
        'identify the factors determining the size of firms;',
        'differentiate between privatization and commercialization;',
        'compare the advantages and disadvantages of privatization and commercialization;',
      ],
    },
    'Population': {
      subtopics: [
        'Meaning and theories;',
        'Census: importance and problems.',
        'Size and growth: over-population, under-population and optimum population.',
        'Structure and distribution;',
        'Population policy and economic development.',
      ],
      objectives: [
        'analyse some population theories:',
        'examine the relevance of the theories to Nigeria;',
        'examine the uses and limitations of census data;',
        'identify determinants of the size, composition and growth of population;',
        'analyse the structure and distribution of population;',
        'appraise government population policy in Nigeria.',
      ],
    },
    'International Trade': {
      subtopics: [
        'Meaning and basis for international trade (absolute and comparative costs etc.)',
        'Balance of trade and balance of payments: problems and corrective measures;',
        'Composition and direction of Nigeria’s foreign trade;',
        'Exchange rate: meaning, types and determination.',
      ],
      objectives: [
        'examine the basis for international trade.',
        'differentiate between absolute and comparative advantages;',
        'distinguish between balance of trade and balance of payments and their corrective measures;',
        'highlight the problems of balance of payments and their corrective measures;',
        'examine the composition and direction of Nigeria’s foreign trade;',
        'identify the types of exchange rates;',
        'examine how exchange rates are determined.',
      ],
    },
    'International Economic Organizations': {
      subtopics: [
        'Roles and relevance of international organizations e.g. ECOWAS, AU, EU, ECA, IMF, EEC, OECD, World Bank, IBRD, WTO, ADB and UNCTAD etc. to Nigeria.',
      ],
      objectives: [
        'identify the various economic organizations and their functions;',
        'evaluate their relevance to the Nigerian economy.',
      ],
    },
    'Factors of Production and their Theories': {
      subtopics: [
        'Types, features and rewards;',
        'Determination of wages, interest and profits;',
        'Theories: marginal productivity theory of wages and liquidity preference theory;',
        'Factor mobility and efficiency;',
        'Unemployment and its solutions',
      ],
      objectives: [
        'identify the types; features and rewards of factors of productions;',
        'analyse the determination of wages, interest and profits;',
        'interpret the marginal productivity of liquidity preference theories;',
        'examine factors mobility and efficiency;',
        'examine the types and causes of unemployment in Nigeria;',
        'suggest solutions to unemployment in Nigeria.',
      ],
    },
  },
} as const

export type EconomicsTopic = keyof typeof ECONOMICS_CONFIG.topics