export const FRENCH_CONFIG = {
  name: 'French',
  prefix: 'FRE',
  category: 'arts',
  priority: 10,
  totalQuestions: 40,
  topics: {
    'Written Comprehension in French': {
      subtopics: [
        'topics of general and emergent interest e.g. love, life, death, politics, marriage, health, communication, child trafficking, cultism, travel, corruption, money-laundering, etc.',
      ],
      objectives: [
        'deduce answers to questions on the content, intent and style of proposed texts,',
        'apply reasoning skills.',
      ],
    },
    'Principles Governing the Structure and Use of Written French': {
      subtopics: [
        'Identification of basic form classes',
        'Nouns: simple/compound, singular/plural, masculine/feminine.',
        'Pronouns: personal, impersonal, demonstrative, possessive and relative.',
        'Verbs: reflexive and non-reflexive, their moods and tenses.',
        'Adjectives: qualifying, possessive, interrogative, demonstrative, indefinite (e.g. nul), numeral (e.g. dix) and ordinal (e.g. dixième.)',
        'Adverbs',
        'common forms',
        'with-ment (e.g. lentement)',
        'with préposition + noun (e.g. par avion, à cheval, en voiture, par bateau.)',
        'special forms (e.g. bien, vite, mal, mieux, le mieux, pire, le pis, ne…que.)',
        'types',
        'manner (e.g. debout, facilement.)',
        'purpose (e.g. pour + infinitive, afin de + infinitive.)',
        'cause and consequence (e.g. pour + infinitive perfect, à cause de + noun.)',
        'concession (e.g. malgré + noun.)',
        'place (e.g. y, en, ici, là, là-haut, partout.)',
        'time (e.g. hier, aujourd’hui, avant-hier, après, demain, la veille, le matin, dans un mois.)',
        'Prépositions',
        'simple (e.g. à, de, avec, avant, sur, dans.)',
        'compound (e.g. à côté de, au milieu de.)',
        'Conjunctions',
        'of co-ordination (e.g. mais, ou, et, donc, car, cependant, ne…ni.)',
        'of subordination (e.g. afin que, quoique, à condition que, pour que, parce que.)',
        'Articles',
        'definite, indefinite and partitive.',
        'contraction e.g. à+le = au, à+les = aux etc.',
        'Assessment of vocabulary span',
        'words in contemporary contexts',
        'meaning, use, opposites, synonyms',
        'Importance of word order in',
        'affirmative sentences',
        'interrogative sentences',
        'imperative sentences',
        'passive voice formation',
        'Identification and application of basic processes in language structure',
        'conjugation - in all tenses except l’imparfait du subjonctif, le passé composé du subjonctif, et…le plus-que-parfait du subjonctif.',
        'negation (e.g. ne…pas, ne…plus, ne…rien, nul ne, ne…ni..ni, ne…personne, personne…ne, aucun….ne, rien ne….etc.)',
        'agreement (e.g. les beaux arts, il les a vues, les photos.)',
        'pluralisation (e.g. cheval/chevaux, beau/beaux, belle/belles.)',
        'derivation',
        'from adj. to adv – e.g. lent-lentement,',
        'from adj. to adj. e.g. un – premier,',
        'from adj. to noun – e.g. bon-bonté, riche-richesse, etc',
        'from one degree of comparison to another (using plus…que, moins….que, aussi….que e.g. plus grand que.)',
        'special forms- (e.g. bon, meilleur, le meilleur, la meilleure, mauvais, pire, le pire.)',
        'Use of French in set expressions such as in proverbs, idioms and conventional structures as provided for in common speech acts',
        'proverbs (e.g. tel père tel fils, petit à petit l’oiseau fait son nid.)',
        'idioms (e.g. avoir une faim de loup, crier sur le toit, mourir de peur.)',
        'conventional stretches (e.g. enchanté, c’est dommage, c’est formidable, stationnement interdit, etc.)',
        'Common figures of speech eg métaphore, simile, hyperbole.',
        'Métaphore – Mon père est un lion.',
        'Simile – Elle est maigre comme un clou.',
        'Hyberbole – Il avait tellement faim qu’il a mangé toute une vache.',
        'speech acts (e.g. proposer, conseiller, regretter, admirer, espérer, interroger, reprocher, s’accorder, etc.)',
      ],
      objectives: [
        'identify what constitutes the basic structures of written French,',
        'use the principles governing the structure of written French to determine acceptability, e.g. to transform one form; one class into another,',
        'apply the structure to convey diverse messages.',
        'identify meaning of words',
        'identify meaningful constructed sentences.',
        'apply communicative skills',
        'complete common proverbs and idioms in French',
        'deduce the meaning of idioms and proverbs in French',
        'make appropriate use of these special terms',
      ],
    },
    'Workings of French sounds': {
      subtopics: [
        'sound discrimination (e.g. tout/tu), (fais/fée.)',
        'letter-sound correspondence (e.g. ai-/e/, eau/o/.)',
        'syllabification (e.g. con/tente/ment.)',
        'liaison (e.g. trois animaux, des enfants.)',
        'sense groups in reading e.g. J’ai mal à la tête. J’ai mal/pas à la tête / mais au dos/. Comment vas-tu, Carol?// Comment vas-tu demain?',
        'faux amis (e.g.librairie/library, rester/to rest, blesser/to bless.)',
        'identification of sounds to determine similarity (e.g. maison/saison, dents/don,fond/fonde.)',
      ],
      objectives: [
        'discriminate between French sounds,',
        'deduce meanings out of sound combinations,',
        'use the above to enhance effective communication,',
        'assess sound groupings in terms of how they are affected by such features as syllabification, liaison, e-caduc; pause, intonation, etc.',
      ],
    },
    'Culture and Civilization': {
      subtopics: [
        'Characteristics, (aspects, similarities and differences) of the educational system, socio-economic life, political organization and cultural life of Francophone Africa and France, with reference (where possible) to home country i.e. Nigeria.',
      ],
      objectives: [
        'identify the specific features of the culture of Francophone Africa and France greetings, dressing, food, leisure, marriage, festival, art, profession etc.',
        'compare these features with those of home country (where possible),',
        'apply reasoning skill.',
      ],
    },
  },
} as const

export type FrenchTopic = keyof typeof FRENCH_CONFIG.topics