export const GEOGRAPHY_CONFIG = {
  name: 'Geography',
  prefix: 'GEO',
  category: 'arts',
  priority: 7,
  totalQuestions: 40,
  topics: {
    'PRACTICAL GEOGRAPHY': {
      subtopics: [
        'Maps',
        'Scale and measurement of distances, areas reduction and enlargement, directions, bearings and gradients with reference to topographical maps.',
        'Map reading and interpretation; drawing of cross profiles, recognition of intervisibility, recognition and description of physical and human features and relationship as depicted on topographical maps.',
        'Interpretation of statistical data; maps and diagrams',
        'Elementary Surveying; chain and prismatic, open and close traverse, procedure, problems, advantages and disadvantages.',
        'Geographic Information System (GIS): components, techniques, data sources, applications',
      ],
      objectives: [
        'define and identify different types and uses of maps',
        'apply the different types of scale to distances and area measurement;',
        'understand conversion of scales',
        'apply the knowledge of scale to gradients, map reduction and enlargement;',
        'apply the knowledge of directions and bearings to geographical features.',
        'illustrate the relief of an area through profile drawing;',
        'interpret physical and human features from topographical maps.',
        'Compute quantitative information from statistical data, diagrams and maps,',
        'interpret statistical data, diagrams and maps.',
        'analyse the principle and procedure of each technique;',
        'compare the advantages and disadvantages of the two techniques.',
        'understand GIS and its uses.',
        'understand the basic concepts and components;',
        'express locations through the use of latitudes, longitudes, zipcodes etc;',
        'understand land surveying, remote sensing, map digitizing, map scanning as sources of data;',
        'explain areas of use: Defense, Agriculture, Rural Development etc;',
        'identify problems with GIS in Nigeria.',
      ],
    },
    'PHYSICAL GEOGRAPHY': {
      subtopics: [
        'The earth as a planet',
        'The earth in the solar system, rotation and revolution;',
        'The shape and size of the earth',
        'Latitudes and distances, longitudes and time;',
        'The Earth Crust',
        'The structure of the earth (internal and external) Relationships among the four spheres.',
        'Rocks: Types, characteristics, modes of formation and uses',
        'Earth’s movement: Tectonic forces',
        'Major Landforms: Mountains, Plateau, Plains, Coastal landforms, karst topography and desert landforms',
        'Volcanism and Earthquakes',
        'Landforms associated with volcanic activities',
        'Landforms of Igneous Rocks',
        'Origin and types of Volcanoes',
        'Some volcanic eruptions and earthquakes.',
        'Denudation processes in the tropics',
        'Weathering',
        'Erosion',
        'Mass movement',
        'Deposition',
        'Water Bodies',
        'Oceans and seas (world distribution, salinity and uses)',
        'Ocean currents: types, distribution, causes and effects;',
        'Lakes: types, distribution and uses.',
        'Rivers: Action of running water.',
        'Weather and Climate',
        'Concept of weather and climate',
        'Elements of weather and climate',
        'Factors controlling weather and climate (pressure, air mass, altitude, continentality and winds)',
        'Classification of climate (Greek and Koppen).',
        'Major climate types (Koppen), their characteristics and distribution.',
        'Measuring and recording weather parameters and instruments used.',
        'The basic science of climate change.',
        'Vegetation',
        'Factors controlling growth of plants',
        'The concept of vegetation e.g.plant communities and succession',
        'Major types of vegetation, their characteristics and distribution,',
        'Impact of human activities on vegetation.',
        'Soil',
        'Definition and properties',
        'Factors and processes of formation',
        'Soil profiles',
        'Major tropical types, their characteristics, distribution and uses;',
        'Impact of human activities on soils.',
        'Environmental Resources;',
        'Types of resources (atmospheric, land, soil, vegetation and minerals)',
        'The concept of renewable and non-renewable resources;',
        'Environmental interaction:',
        'Land ecosystem',
        'Environmental balance and human interaction',
        'Effects of human activities on land ecosystem',
        'Environmental hazards:',
        'Natural hazards (droughts, earthquakes, volcanic eruptions, flooding)',
        'Man-induced (soil erosion, deforestation, pollution, flooding and desertification)',
        'Environmental Conservation:',
      ],
      objectives: [
        'identify the relative positions of the planets in the solar system;',
        'understand the effects of the rotation and revolution of the earth;',
        'provide proof for the shape and size of the earth;',
        'differentiate between latitudes and longitudes;',
        'relate lines of latitude to calculation of distance;',
        'relate lines of longitude to calculation of time;',
        'compare the internal and external components of the earth;',
        'understand the existing relationship among atmosphere, biosphere and hydrosphere in terms of energy balance and water cycle;',
        'differentiate between major types of rocks and their characteristics;',
        'analyse the processes of rock formation and the resultant features;',
        'indicate the uses of rocks;',
        'differentiate between tensional and compressional forces and the resultant landforms;',
        'identify and describe the major landforms;',
        'explain the processes of volcanic eruptions and earthquakes;',
        'describe the different landforms associated with both volcanic eruptions and earthquakes;',
        'give examples of major volcanic eruptions and earthquakes in the world.',
        'identify the agents of denudation (water, wind and waves);',
        'identify the landforms associated with each process and agent.',
        'locate oceans and seas on the globe;',
        'examine the characteristics and uses of oceans and seas;',
        'classify the types of ocean currents;',
        'account for the distribution of ocean currents;',
        'evaluate the causes and effects of ocean currents;',
        'identify the types and location of lakes;',
        'indicate the characteristics and uses of lakes;',
        'identify the landforms of the different stages of a river course.',
        'differentiate between weather and climate;',
        'identify the elements of weather and climate;',
        'identify the factors controlling weather and climate;',
        'compare Koppen’s and Greek’s classifications;',
        'identify the major types of climate according to Koppen;',
        'relate the weather instruments to their uses;',
        'define climate change;',
        'understand the causes of climate change;',
        'understand the effects and remedies of climate change.',
        'trace the factors controlling the growth of plants;',
        'analyse the process of vegetation development;',
        'identify the types, their characteristics and distribution;',
        'assess the impact of human activities on vegetation;',
        'identify the importance of vegetation.',
        'classify soils and their properties;',
        'identify the factors of formation;',
        'differentiate between the different types of soil horizons and their characteristics;',
        'compare the major tropical soil types and uses of soils;',
        'account for the distribution and uses ofsoils;',
        'assess the impact of human activities on soils.',
        'interpret the concept of environmental resources;',
        'relate environmental resources to their uses;',
        'differentiate between the concepts of renewable and non-renewable resources.',
        'identify the components of land ecosystem;',
        'establish the interrelationship within the ecosystem;',
        'interpret the concept of environmental balance;',
        'analyse the effects of human activities on land ecosystem.',
        'identify the natural hazards and their causes;',
        'relate the human-induced hazards to their causes;',
        'locate the major areas where environmental hazards are common and their effects;',
        'recommend possible methods of prevention and control.',
        'explain with examples environmental conservation;',
        'identify the resources for conservation;',
        'discuss the different methods of environmental conservation;',
        'explain the need/importance of environmental conservation.',
      ],
    },
    'HUMAN GEOGRAPHY': {
      subtopics: [
        'Population',
        'World population with particular reference to the Amazon Basin, N.E. U.S.A., India, Japan and the West Coast of Southern Africa.',
        'Characteristics – birth and death rates, ages/sex structure.',
        'Factors and patterns of population distribution;',
        'Factors and problems of population growth.',
        'Settlement with particular reference to Western Europe, the USA, Middle East and West Africa:',
        'Types and patterns: rural and urban, dispersed, nucleated and linear;',
        'Rural settlement: classification, factors of growth and functions;',
        'Urban settlement – classification, factors of growth and functions.',
        'Problems of urban centres',
        'Interrelationship between rural and urban settlements.',
        'Selected economic activities',
        'Types of economic activities: primary, secondary, tertiary and quartnary;',
        'Agriculture: types, system, factors and problems',
        'Manufacturing industries, types, locational factors, distribution and socio-economic importance and problems of industrialization in tropical Africa.',
        'Transportation and Communication types, roles in economic development and communication in tropical Africa.',
        'World trade:-factors and pattern of world trade, major commodities (origin, routes and destinations).',
        'Tourism: definition, importance, location, problems and solutions.',
      ],
      objectives: [
        'define different concepts of population;',
        'identify the characteristics of population (growth rates and structure);',
        'determine the factors and the patterns of population distribution;',
        'identify the factors and problems of population growth;',
        'relate the types of migration to their causes and effects;',
        'account for the ways population constitute a resource.',
        'differentiate between types of settlements; (rural and urban);',
        'classify the patterns and functions of rural settlements;',
        'classify the patterns and functions of urban settlements;',
        'identify the factors of settlement location',
        'identify the problems of urban centres;',
        'establish the interrelationship between rural and urban settlements.',
        'identify the types of economic activities;',
        'differentiate between the types of economic activities;',
        'assess the importance and problems of agriculture as an economic activity;',
        'compare the types of manufacturing industries;',
        'identify the factors of industrial location;',
        'examine the socio-economic importance of manufacturing industries;',
        'give reasons for the problems of industrialization in tropical Africa;',
        'differentiate between the modes of transportation and communication;',
        'assess the economic importance of transportation;',
        'give reasons for the problems of transportation in tropical Africa;',
        'relate the factors to the pattern of world trade;',
        'classify the major commodities of trade in terms of their origins, routes and destination;',
        'analyse tourism as an economic activity;',
        'identify the problems of tourism and their solutions.',
      ],
    },
    'REGIONAL GEOGRAPHY': {
      subtopics: [
        'Broad outline of Nigeria',
        'Location, position, size, political division (states) and peoples;',
        'Physical setting: geology, relief, landform, climate and drainage, vegetation and soils;',
        'Population: size, distribution, migration, (types, problems and effects);',
        'Natural resources: types (minerals, soils, water, vegetation, etc.) distribution, uses and conservation.',
        'Economic and Human Geography:',
        'Agricultural Systems: the major crops produced, problems of agricultural development in Nigeria.',
        'Manufacturing Industries: factors of location, types of products, marketing and problems associated with manufacturing;',
        'Transportation and Communication: modes of transportation and communication and their relative advantages and disadvantages;',
        'Trade: Regional and International Trade, advantages and disadvantages;',
        'Tourism: definition, importance, problems and solutions.',
        'ECOWAS',
        'Meaning and objectives',
        'Member states',
        'Advantages and disadvantages',
        'Problems and solutions.',
      ],
      objectives: [
        'describe the location, size and political divisions of Nigeria;',
        'identify the boundaries and neighbours of Nigeria;',
        'identify the ethnic groups and their distributions;',
        'relate the components of physical settings to their effects on human activities;',
        'account for the pattern of population distribution;',
        'examine the types of migration, their problems and effects;',
        'identify the types of natural resources and their distribution;',
        'indicate the uses and conservation of natural resources.',
        'compare the farming systems practised in Nigeria;',
        'identify the crops produced and the problems encountered;',
        'identify the types and location of the major manufacturing industries;',
        'determine the factors of industrial location and the problems associated with the industries;',
        'establish the relationship between transport and communication;',
        'relate the modes of transportation and communication to their relative advantages and disadvantages;',
        'classify the major commodities of regional and international trade;',
        'identify the importance of tourism and tourist centres;',
        'account for the problems of tourism and their solutions.',
        'State the meaning, purpose and objectives;',
        'identify and locate the member countries;',
        'understand the purpose/mandate of the organization;',
        'evaluate the prospects and problems of the organization.',
      ],
    },
  },
} as const

export type GeographyTopic = keyof typeof GEOGRAPHY_CONFIG.topics