export const HAUSA_CONFIG = {
  name: 'Hausa',
  prefix: 'HAU',
  category: 'arts',
  priority: 12,
  totalQuestions: 40,
  topics: {
    'Harshe (Language)': {
      subtopics: [
        'Ƙa’idojin Rubutu (Orthography)',
        'alphabetization, spelling, rules of word merger and division, punctuation and paragraphing all in line with standard Hausa.',
        'Auna Fahimta (Comprehension)',
        'contextual questions from short unseen passages of about 200 words.',
        'Tsarin Rubutun Insha’i (Composition Techniques)',
        'argumentative, descriptive, dialogue, expository, narrative and letter writing.',
        'Fassara (Translation)',
        'Ire-iren fassara (types of translation)',
        'Ƙa’idojin fassara (rules of translation)',
        'Matsalolin fassara (problems of translation)',
        'Dabarun fassara (techniques of translation).',
        'Tsarin Sauti (Phonology)',
        'consonants – production and classification in terms of phonation, place and manner of articulation;',
        'vowels – production and classification in terms of position of tongue and lips; monophthongs and dipthongs;',
        'tone – e.g., high, low and falling tones;',
        'syllable structure – syllable types, e.g., open and close syllables, light and heavy, syllables, syllabic categories of words – monosyllabic, disyllabic, etc.',
        'vowel length – long and short vowels;',
        'phonological processes – e.g., assimilatory: palatalization, labialization and vowel harmony; non-assimilatory: insertion and deletion.',
        'Ƙirar Kalma (Morphology)',
        'roots and stems;',
        'affixation – e.g., prefix, infix suffix and their derivational and inflectional functions;',
        'gender and number inflections;',
        'derivation of nouns and adjectives from verbs; adjectives and verbs from nouns.',
        'Ginin Jumla (Syntax)',
        'word classes-e.g., nouns, pronouns, verbs, adverbs, adjectives, prepositions, conjunctions, interjections and ideophones;',
        'grammatical categories – e.g., tense and aspect (general and relative past: general and relative continuous, first and second future, habitual); mood (subjunctive and negative); gender (masculine, feminine and neuter) and number (singular and plural);',
        'sentence structure – e.g., verbal sentence, nominal phrase + verbal phrase and their components, non-verbal sentence: nominal phrase + stabilizer, nominal phrase+ compliment + stabilizer, nominal phrases + continuous frame (yana../yake…) (+da) + nominal phrase;',
        'sentence types – e.g., simple sentences, compound sentences and complex sentences;',
        'clauses – types (e.g., relative and subjunctive); functions (e.g., main and subordinate).',
        'Ma’ana (Semantics)',
        'lexical aspects of word meaning – e.g., ambiguity, synonym and antonym;',
        'figures of speech – aspects of specialized meanings of words and phrases, e.g., idioms, proverbs etc.',
      ],
      objectives: [
        'recognize the basic Hausa orthographical rules;',
        'apply the Hausa orthographical rules;',
        'identify linguistic errors, such as; grammar, wrong choice of words, wrong spelling etc.',
        'read written Hausa texts;',
        'comprehend Hausa text in a given context;',
        'interpret various meanings and functions of words in a given text;',
        'acquire sufficient vocabulary;',
        'recognize central issues in a given text;',
        'draw conclusions based on available evidence in a given text.',
        'acquire the knowledge and techniques of composition writing in Hausa;',
        'recognize the different segments of composition in Hausa;',
        'recognize the different types of Hausa composition.',
        'translate proverbial and idiomatic expressions and new words from English to Hausa;',
        'recognize the different types of translation;',
        'understand the basic techniques of translating proverbial and idiomatic expressions and new words into Hausa;',
        'identify the problems of translation into Hausa.',
        'analyse the process of sound production and combination of sounds to form meaningful words in Hausa;',
        'appraise the importance of vowels in determining meaning;',
        'distinguish between the phonetic attributes of sounds;',
        'recognize the number of syllables and their types in a word;',
        'analyse the phonological processes in Hausa.',
        'explain the roots and stems of Hausa words;',
        'explain the inflectional process in Hausa word formation;',
        'explain the derivational process of word formation in Hausa;',
        'differentiate between the two morphological processes.',
        'analyse the processes governing word combination to form phrases; clauses and sentences in Hausa;',
        'detect linguistic errors in the grammar;',
        'recognize ideas or thoughts in written form;',
        'construct grammatical sentences for effective communication;',
        'use the appropriate tenses in spoken and written Hausa;',
        'use the appropriate gender and number in spoken and written Hausa;',
        'differentiate between types of sentence structure;',
        'distinguish between nominal and verbal phrase;',
        'distinguish between types of sentences;',
        'compare types of clauses.',
        'analyse the mechanisms of generating meanings in Hausa;',
        'build up their vocabulary;',
        'recognize the various meanings and functions of sentences in communication;',
        'use words and sentences suitable for a particular purpose;',
        'construct meaningful sentences for effective communication.',
      ],
    },
    'Al’adu (Culture)': {
      subtopics: [
        'Rayuwar Hausawa (Hausa customs)',
        'haihuwa (birth) – ɗaukar ciki da goyon ciki da haihuwa da shayarwa da al’adun makon farko na haihuwa da wanka da ɓanti da yaye da kaciya da samartaka;',
        'aure (marriage) – ire-irensa da nema da baiko da ɗaurin aure da biki da zaman aure da saki da zawarci;',
        'mutuwa (death) – faɗar mutuwa da wanka da salla da jana’iza da zaman makoki da sadaka da takaba da gado;',
        'tasirin zamani akan rayuwar Hausawa.',
        'Zamantakewa (Social Institutions)',
        'tsarin zaman iyali da zaman gandu da dangantakar kishiyoyi da ‘yan uwantaka da barantaka da agolanci;',
        'maƙwabtaka;',
        'aikin gandu da na gayya;',
        'abota da ƙawance;',
        'gaisuwa da karamci;',
        'tasirin zamani a kan zamantakewa.',
        'Sana’o’in Gargajiya (Traditional Occupations)',
        'ire-irensu – noma da ƙira da jima da kasuwanci da wanzanci da sassaƙa da farauta da dukanci da saƙa da kitso da rini da fawa da fafar ƙorai, da sauransu;',
        'yanayinsu – hanyoyin gadon su da kayayyakin yin su da matakan tafiyar da su da muhimmancinsu;',
        'kayayyaki ko amfanin da suke samarwa;',
        'sarautunsu;',
        'sana’o’i masu dangantaka da jinsi – aikatau da ƙwadago; kitso da aski.;',
        'tasirin zamani a kan sana’o’in gargajiya.',
        'Kayayyakin Buƙatun Rayuwa (Material Culture)',
        'na buƙatun cikin gida (household) – tufafi da karikitan cikin gida;',
        'na sauran buƙatu (others) – gine-gine da girke-girke da sauransu;',
        'tasirin zamani a kan kayayyakin buƙatuwa.',
        'Bukukuwa da Wasanni (Hausa festivities and recreational activities)',
        'na addini (religious) – irin su bikin salla da takutaha (sallar gani) da cika-ciki da saukar karatu;',
        'na gargajiya (traditional) – irin su kalankuwa da buɗar dawa, da bikin shan kabewa;',
        'na sana’a (occupational) – bikin kamun kifi da dambe da kokawa da wasan farauta da wasan maƙera da hawan ƙaho;',
        'na nishaɗi – sukuwa;',
        'na yara (children’s games) –irin su shalle da kulli-kurciya da a-sha-ruwan-tsuntsaye da gaɗa da carafke;',
        'tasirin zamani kan bukukuwa da wasanni.',
        'Camfe-camfe da Bauta (Traditional Beliefs and Worship)',
        'camfe-camfe irin su kangida da camfi, da kambun baka da maita;',
        'bauta irin su bori da da tsafi;',
        'tasirin zamani a kan camfe-camfe da bauta.',
        'Sarautun Gargajiya (Traditional Authority)',
        'ire-iren su – sarakuna da hakimai da dagatai da masu unguwanni;',
        'na bayin sarki – shantali da jakadiya da baraya da sauransu;',
        'masu alaƙa da addini; irin su liman da alƙali;',
        'ayyukansu.',
        'tasirin zamani a kan sarautun gargajiya.',
        'Magungunan Gargajiya (Traditional Medicine)',
        'ire-iren su;',
        'na gargajiya: sassaƙe-sassaƙe da sawyoyi da na gari da na ruwa;',
        'na addini: layu da rubutu da ɗibbu da duba;',
        'hanyar amfani da su – sha da shafawa da surace da turare da shaƙawa da taunawa da tsotsawa da ɗaurawa da liƙawa da ratayawa;',
        'tsarin amfani da su awo da kimantawa;',
        'ayyukansu – riga-kafi da warkarwa;',
        'tasirin zamani a kansu.',
      ],
      objectives: [
        'bayyana al’adun da ke tattare da ɗaukar ciki har zuwa samartaka;',
        'bayyana tasirin zamani a kan haihuwa;',
        'bayyana al’adun neman aure har zuwa zawarci;',
        'bayyana tasirin zamani akan aure;',
        'bayyana hanyoyin faɗar mutuwa zuwa rabon gado;',
        'bayyana tasirin zamani akan mutuwa;',
        'tantance ma’ana da ire-iren tasirin zamani.',
        'bayyana tsarin dangantaka da mu’amala tsakanin iyali;',
        'bayyana muhimmancin zamantakewa a tsakanin Hausawa;',
        'tantance ire-iren tasirin zamani a kan al’adun zamantakewa.',
        'tantance ɗabi’un masu sana’a;',
        'tantance kayayyakin da ake sana’antawa;',
        'tantance sana’o’in maza da na mata;',
        'zayyana kayayyakin sana’o’in;',
        'tantance hanyoyin gadon sana’o’in;',
        'zayyana amfanin kayayyakin sana’o’in;',
        'bayyana sarautun sana’o’in;',
        'bayyana muhimmancin sana’o’in;',
        'tantance tasirin zamani akan sana’o’in.',
        'tantance kayayyakin buƙatun rayuwa na hausawa;',
        'tantance amfanin kayayyakin buƙatun rayuwa na Hausawa;',
        'tantance tasirin zamani a kan kayayyakin buƙatun rayuwa na Hausawa.',
        'zayyana ire-iren wasanni da bukukuwan Hausawa;',
        'nuna mahimancinsu;',
        'nuna yadda za a adana su kada su ɓace;',
        'nuna yadda ake gudanar da su;',
        'nuna tasirin zamani a kan bukukuwa da wasanni.',
        'tantance ire-ire da hanyoyin aiwatar da su;',
        'bayyana amfaninsu;',
        'bayyana rashin amfaninsu.',
        'bayyana tasirin zamani a kansu.',
        'zayyana su ta fuskar ire-iren muƙamai;',
        'zayyana matakan muƙamai;',
        'tantance aikin kowane mai muƙami;',
        'tantance mahimmancin kowane muƙami.',
        'bayyana tasirin zamani a kansu.',
        'karkasa ire-iren magunguna;',
        'zayyana hanyoyin amfani da su;',
        'fito da amfaninsu;',
        'nuna tasirin zamani a kan su.',
      ],
    },
    'Adabi (Literature)': {
      subtopics: [
        'Adabin Baka (Oral Literature)',
        'Zuben Baka (Narratives)',
        'Irin su tatsuniya da almara da hikaya da ƙissa da tarihi da sauransu.',
        'Maganganun Azanci (Folk – sayings)',
        'Irin su take da kirari da habaici da zambo da karin magana da kacici-kacici da salon magana da adon magana da sauransu.',
        'Waƙoƙi na baka (Oral songs)',
        'ire-iren su – na fada da na jama’a da na maza da na sha’awa da sauransu:',
        'turke (jigo) da salo da zubi da tsari da mawaƙi da kayan kiɗa da abin da aka waƙe.',
        'waƙoƙin aiki: na niƙa da daɓe da na daka da na talla da sauransu;',
        'Waƙoƙin yara (maza da mata); na aure da na dandali da sauransu;',
        'Wasannin Kwaikwayo Na Gargajiya (Traditional Drama)',
        'Na yara:',
        'ire-irensu - langa da wasan ’yartsana da tashe da wasan gauta da dokin kara da sauransu;',
        'yadda ake yin su.',
        'muhimmancinsu',
        'Na manya:',
        'ire-irensu - ‘yan kama da kalankuwa da hoto da wowwo da tashe, da sauransu;',
        'yadda ake yinsu;',
        'muhimmancinsu',
        'Rubutaccen Adabi (Written Literature)',
        'Zube (Prose)',
        'Maraya',
        'Waƙa (Poetry)',
        'Waƙoƙin Wayar Da kai Don Manazarta Hausa Na Ɗaya',
        'Wasan Kwaikwayo (Drama)',
        'Malam Zalimu',
      ],
      objectives: [
        'tantance nau ‘o’in zuben baka;',
        'amfani da kalmomin da suka dace da kan labari.',
        'tantance sigogi da bayyana hanyoyin amfani da su;',
        'naƙalta da amfani da kalmomin da suka dace da maganganun azanci.',
        'tantance ire-iren waƙoƙin baka;',
        'tantance masu yin ire-iren waƙoƙin;s',
        'rarrabe siga da turke (jigo) da salo da zubi da kayayyakin aiwatar da su.',
        'tantance nau’o’in waƙoƙin aiki;',
        'tantance masu yin waƙoƙin aiki;',
        'bambance sigogin waƙoƙin yara.',
        'tantance sigogin wasannin kwaikwayo na gargajiya.',
        'tantance hanyoyin gudanar da wasannin kwaikwayo na gargajiya;',
        'fito da muhimmancin wasannin kwaikwayo na gargajiya;',
        'fayyece bambancin wasan kwaikwayo na yara da na manya.',
        'tantance siga da tsari da jigo da salo da taurarin cikin littafin zube tare da nazarin su;',
        'naƙaltar ƙa’idojin rubutu yayin karanta rubutun zube;',
        'naƙaltar ma’anonin kalmomi da na jumloli domin fahimtar labari;',
        'tantance muhimman saƙonni a cikin labari da yanke hukunci game da labarin.',
        'fahimtar jigo da salo da siga da zubi wajen nazarin zaɓaɓɓiyar waƙa;',
        'yin la’akari da ƙa’idojin rubutu musamman na waƙa;',
        'tantance ma’anonin kalmomi da na jumloli wajen nazarin waƙa;',
        'danganta amfani da kalmomi da jumloli da saƙon waƙa;',
        'tantance muhimman saƙonni a cikin waƙa da yanke hukunci game da ita.',
        'tantance yanayin wurin wasa da jigo da salo da ‘yan wasa da siga da tsarin rubutaccen wasan kwaikwayo da aka zaɓa don nazari;',
        'la’akari da muhimmancin ƙa’idojin rubutu wajen fitar da ma’ana;',
        'naƙaltar ma’anar kalmomi domin fahimtar wasa;',
        'tantance muhimman saƙonni a cikin wasa da yanke hukunci game da saƙonnin.',
      ],
    },
  },
} as const

export type HausaTopic = keyof typeof HAUSA_CONFIG.topics