export const HOME_ECONOMICS_CONFIG = {
  name: 'Home Economics',
  prefix: 'HEC',
  category: 'science',
  priority: 7,
  totalQuestions: 40,
  topics: {
    'Home Economics': {
      subtopics: [
        'Meaning, scope and importance of Home Economics',
        'Objectives and ideals of Home Economics',
      ],
      objectives: [
        'examine the importance of Home Economics to the individual, family, society and nation;',
        'identify the objectives of Home Economics;',
        'determine the scope of Home Economics.',
      ],
    },
    'Areas/Careers in Home Economics': {
      subtopics: [
        'Home Management',
        'Interior decoration',
        'Credit management',
        'Florist',
        'Foods and Nutrition',
        'Catering',
        'Dietetics',
        'Nutritionist',
        'Public Health Education, etc.',
        'Clothing and Textile',
        'Textile designing',
        'Family and Child development',
        'Early and Childhood education',
        'Teaching',
        'Counselling',
        'Media',
        'Research',
      ],
      objectives: [
        'recommend possible vocations in the different areas of Home Economics;',
        'relate Home Economics to each vocation;',
        'assess the benefits of each vocation to the individual, society and nation;',
        'identify current vocations in Home Economics;',
        'identify sources of career information.',
      ],
    },
    'Interrelationship of Home Economics with other subjects': {
      subtopics: [
        'Biology',
        'Geography',
        'Chemistry',
        'Physics',
        'Agricultural Science',
        'Fine Arts',
        'Economics',
        'Mathematics etc.',
      ],
      objectives: [
        'compare the different areas of study which have relationship with Home Economics;',
        'determine the contributions of these subjects to Home Economics.',
      ],
    },
    'Principles of Home Management': {
      subtopics: [
        'Meaning of Home Management',
        'Steps in the management process',
        'Decision-making: meaning and process',
        'Motivation for Home Management e.g. goals, values, standards, needs and wants, likes and dislikes',
      ],
      objectives: [
        'state the meaning of Home Management;',
        'identify steps involved in the management process;',
        'determine issues for decision-making in the home;',
        'describe the role of motivators in Home Management.',
      ],
    },
    'Resources': {
      subtopics: [
        'Human Resources: definition and types',
        'Time management',
        'definition and pattern',
        'types of work time',
        'factors influencing the use of time',
        'advantages of time management',
        'Energy: definition and reasons for energy management',
        'work simplification - its purpose and application',
        'guidelines for work simplification and time saving gadgets',
        'Skills, creativity, attitudes etc.',
        'Material Resources: definition/types',
        'income and money management',
        'meaning and types of income',
        'principles of money management',
        'household budgeting: steps in making a budget',
        'economic security of the family',
        'bank accounts',
        'traditional savings, building societies and insurance',
      ],
      objectives: [
        'identify the resources available to the individual and family;',
        'describe the pattern of work plan;',
        'apply the principle of time management to work simplification in the home;',
        'identify the sources of income available to an individual and family;',
        'determine the means of family saving;',
        'give reasons for saving family income;',
        'determine the steps involve in family budgeting;',
        'suggest alternative resources for Home Management;',
        'analyse the principles of money management;',
        'state other material resources available to individual and family.',
      ],
    },
    'Family Living': {
      subtopics: [
        'Definition and types of family',
        'Advantages and disadvantages of family types',
        'The family life cycle',
        'Family relationships',
        'husband/wife relationship, parent/child relationship, brother/sister or sibling relationships',
        'factors that influence family relationship',
        'Basic personality profiles',
        'meaning of personality',
        'extroversion, introversion and anxiety/stability',
        'Adolescents and their problems',
        'Family crises',
        'Conflict and conflict resolution',
        'Human rights',
        'Meaning of human rights and fundamental human rights',
        'Rights of women and children',
        'Violation of human rights',
        'Communication and role of ICT in the Family',
      ],
      objectives: [
        'compare types of family;',
        'identify roles of family members;',
        'differentiate between the types of relationships that exist in the family;',
        'determine the factors that influence family relationships;',
        'describe factor that influence family relationships;',
        'identify characteristics and problems of adolescents.',
        'compare the basic personality profiles (extrovert, introvert);',
        'identify types of family crises and ways of solving them;',
        'identify sources of conflict and solution strategies;',
        'identify types of human rights and human rights violation;',
        'suggest remedies for breach of human rights;',
        'identify factors that hinder communication in the family;',
        'determine factors that enhance communication in the family;',
        'identify the advantages and disadvantages of ICT.',
      ],
    },
    'Marriage and Reproductive Health': {
      subtopics: [
        'Meanings of marriage and sex education',
        'Boy/Girl relationship',
        'courtship',
        'factors to consider when choosing a partner',
        'Preparation for marriage',
        'meaning and purpose of engagement',
        'types of marriage; Islamic, Christian, Court and Traditional',
        'planning a family',
        'Reproductive health',
        'sexually transmitted infections/ diseases (STIs/STDs and HIV/AIDS) etc.',
      ],
      objectives: [
        'differentiate between types of marriages in Nigeria;',
        'compare the advantages and disadvantages of inter-tribal marriages;',
        'analyse the role of courtship and engagement in marriages;',
        'identify the different ways of planning a family;',
        'state types, causes and prevention of sexually transmitted infections and diseases.',
      ],
    },
    'Pregnancy and childbirth': {
      subtopics: [
        'Menstruation, pregnancy and childbirth, labour delivery and post-natal care',
        'Childcare, baby’s layette, care of the baby, toilet training, bathing, feeding, weaning, etc.',
        'Care of toddlers',
        'common ailments in children',
        'immunization',
        'Child development',
        'good habits and character training',
        'play and play materials',
        'Parenting',
        'meaning and importance',
        'responsibilities of parents',
      ],
      objectives: [
        'describe the process of reproduction from conception to birth;',
        'describe the care an infant need from birth to 5 years;',
        'determine the factors that affect pregnancy;',
        'differentiate between the stages of labour;',
        'identify the symptoms of common ailments in children;',
        'mention types of play materials;',
        'trace the stages of development in children;',
        'recommend suitable play materials for children;',
        'identify responsibilities of parents.',
      ],
    },
    'Housing the family': {
      subtopics: [
        'Houses and home',
        'types of houses',
        'factors that affect the choice of a house',
        'ways of acquiring a house',
        'Interior decoration',
        'wall finishing and the application of principles of art and design to colours, textures, lines and proportions',
        'flower arrangements',
        'Furniture and furnishings in the home',
        'types',
        'factors that affect choices and position',
        'Utilities in the Home',
        'Water: source, uses, purification, etc.',
        'Household fuels e.g gas, coal, electricity, kerosene, fire wood and sawdust',
        'Electricity: related terms, generation, safety, etc.',
        'Communication devices e.g. GSM, computer etc',
      ],
      objectives: [
        'differentiate between a house and a home;',
        'identify the factors that influence residential choice;',
        'describe items that beautify living areas;',
        'suggest suitable colours, textures and other related factors that should be considered in interior decoration;',
        'determine factors that influence choice and arrangement of furniture;',
        'compare different floral arrangements;',
        'identify types of ornament and fixtures;',
        'describe the care of ornaments and fixtures;',
        'identify utilities in the home;',
        'appraise the advantages and disadvantages of these utilities in relation to their alternatives.',
      ],
    },
    'Home surfaces': {
      subtopics: [
        'Types and care of surfaces and coverings e.g. wood, tiles, Formica, concretes, plastics, linoleums, mats, rugs and terrazzo',
        'Identification, preparation and use of cleaning agents such as water, soap, abrasives, polish, etc',
        'Care of home surfaces and coverings e.g. washing, sweeping, dusting, shampooing, buffing, polishing',
      ],
      objectives: [
        'identify common surfaces in the homes;',
        'mention cleaning agents and their uses in the home;',
        'identify materials needed for preparing local cleaning agents;',
        'compare the care of the following: wood, plastic, concrete, rugs, mats, linoleum etc',
      ],
    },
    'Sanitation in the Home': {
      subtopics: [
        'Drainage systems – types and care',
        'Disposal of household refuse',
        'Household pests and control',
        'Pollution and health hazards',
      ],
      objectives: [
        'identify types of waste water;',
        'suggest ways of disposing household refuse;',
        'identify common household pests and their control;',
        'identify some diseases transmitted by pests;',
        'describe sources of pollution;',
        'mention the health hazards of pollution.',
      ],
    },
    'Consumer Education': {
      subtopics: [
        'Meaning and importance of consumer education',
        'Definition and types of market',
        'Distributors or consumer agents',
        'Sources of consumer information',
        'Purchasing practices',
        'Advertising',
        'Consumer rights and responsibilities',
        'Government agencies and regulatory bodies',
      ],
      objectives: [
        'explain the importance of consumer education;',
        'identify the different types of markets;',
        'describe the various consumer agents;',
        'identify sources of consumer advice and information;',
        'apply the principles of consumer education to wise shopping;',
        'identify the types of media used by advertisers;',
        'describe their advantages and disadvantages;',
        'explain the rights and responsibilities of the consumer;',
        'identify the functions of government agencies and regulatory bodies.',
      ],
    },
    'Foods and Nutrition': {
      subtopics: [
        'Definition of Foods and Nutrition',
        'Classification of nutrients, their sources and functions, deficiency diseases',
        'Classification of foods: cereals, fats and oils, milk and milk products, meat, fish, pulses, nuts, fruits, vegetables, etc',
        'Nutrition and health',
        'Relationship of nutrition and health',
        'Factors affecting nutrition e.g. income, food in season, availability of food, etc.',
        'The digestive system',
        'Nutrition for special groups e.g infants, toddlers, adolescents, manual workers, etc.',
      ],
      objectives: [
        'describe the following: food nutrients, carbohydrates, minerals, fat and oil, vitamin, protein and water;',
        'identify the different classes of food;',
        'describe the effect of nutrition on health status;',
        'identify factors affecting good nutrition;',
        'describe the process which breakdown large food molecules;',
        'recommend the nutritional needs for special groups;',
        'determine the reasons for the nutritional needs of the following special groups: expectant/ lactating mothers, infant, toddlers, sedentary /manual workers, children between 5 and 8 years, adolescent, aged, invalid and convalescent.',
      ],
    },
    'Meal planning': {
      subtopics: [
        'Principles of meal planning',
        'Dietary needs and meals for special occasions and groups',
        'Preparation and serving of meals',
        'Snacks and beverages',
        'meaning, types and functions',
        'Table setting, table manners and hostessing',
      ],
      objectives: [
        'identify factors that influence the choice and preparation of food for the family;',
        'plan meals for special occasions e.g. weddings, birthdays, anniversaries, etc;',
        'plan meals for special groups e.g. vegetarians, invalids convalescence, HIV/AIDS patient, COVID patient, etc;',
        'identify types of snacks/beverages and their functions;',
        'compare types of table setting;',
        'describe table manners and qualities of a good host.',
      ],
    },
    'Cookers and cooking': {
      subtopics: [
        'Types, choice and care of cookers e.g. gas, electric, microwave, etc',
        'Reasons for cooking',
        'Cooking terms',
        'Methods of cooking e.g. boiling, stewing, baking, steaming, etc',
        'moist and dry methods of cooking',
        'Methods of heat transfer e.g. conduction, convection and radiation',
      ],
      objectives: [
        'identify types of cookers, their choice and care;',
        'enumerate reasons for cooking;',
        'group the methods of cooking into the following: moist methods, dry methods, fast methods, slow methods',
        'determine the method of heat transfer in the various methods of cooking.',
      ],
    },
    'Flours and uses': {
      subtopics: [
        'Types and uses of flours',
        'Raising agent e.g air, yeast, palm wine, steam, etc.',
      ],
      objectives: [
        'identify types of flours and their uses;',
        'select appropriate raising agents for basic mixtures;',
        'use flour to produce assorted food items;',
      ],
    },
    'Basic mixtures': {
      subtopics: [
        'Pastries / Batters',
        'Definition / uses',
      ],
      objectives: [
        'differentiate between batters and pastries',
        'use batters and pastries for different purposes.',
      ],
    },
    'Scientific methods in Foods and Nutrition': {
      subtopics: [
        'Measure units and accuracy',
        'Various nutrients tests in food e.g test for protein, fats and carbohydrates',
        'Recipe development',
      ],
      objectives: [
        'demonstrate skills in unit measurements;',
        'detect the nutrients in a given food;',
        'develop basic recipes in food preparation.',
      ],
    },
    'The Kitchen': {
      subtopics: [
        'Types of kitchen',
        'Arrangement',
        'Tools and equipment',
        'selection, use and care',
      ],
      objectives: [
        'describe types and arrangement of kitchen;',
        'compare large and small kitchen equipment and tools;',
        'specify factors to consider in selecting kitchen tools and equipment.',
      ],
    },
    'Kitchen safety and hygiene': {
      subtopics: [
        'Common accidents in the kitchen',
        'causes of accidents',
        'preventive measures',
        'First Aid',
        'definition',
        'components of a first aid kit',
        'simple first aid for burns, scalds, cuts bruises, bleeding, electric shock, poisoning, chocking and bites',
        'Kitchen, personal and food hygiene',
        'communicable and non-communicable',
      ],
      objectives: [
        'identify common accidents in the kitchen, their causes and preventive measures;',
        'suggest ways of making the kitchen a safe place;',
        'specify items which should be included in a first aid kit;',
        'suggest simple first aid for scalds, cuts, bleeding, burns, etc;',
        'identify ways in which food is contaminated;',
        'compare communicable and non – communicable disease and their preventive measures;',
      ],
    },
    'Food Storage and Preservation': {
      subtopics: [
        'Meaning and purpose of preservation',
        'causes of food spoilage',
        'principles of food preservation',
        'methods of food preservation',
        'Convenience foods',
        'definition and types',
        'guidelines for selection',
        'use of convenience foods',
        'Food additives',
        'Types and uses',
        'Rechauffe dishes',
        'meaning, rules and types',
        'advantages and disadvantages of rechauffe',
      ],
      objectives: [
        'identify agents of food spoilage;',
        'describe the principles involved in the preservation and storage of foods;',
        'compare the advantages and disadvantages of food preservation method;',
        'identify convenience foods;',
        'compare the advantages and disadvantages of using convenience foods;',
        'identify guidelines for selecting convenience foods;',
        'identify additives used in foods;',
        'compare the advantages and disadvantages of rechauffe dishes.',
      ],
    },
    'Home Gardening': {
      subtopics: [
        'definition',
        'common gardening tools',
        'advantages of home gardening',
        'types of soil',
        'plants and crops suitable for home garden',
        'preparation and care of home garden',
      ],
      objectives: [
        'identify gardening tools;',
        'explain the importance of home gardening;',
        'describe the procedures involved in home gardening.',
      ],
    },
    'Fibres and Fabrics': {
      subtopics: [
        'Origin of fibres',
        'definition of textile terms, e.g. fibres, fabrics, yarn, staple, filament, blends, etc.',
        'locally made fabric e.g. aso-oke, Okene cloth, Benue cloth, Akwete, Gwado, etc',
        'Classification and properties of fibres e.g. cotton, rayon, silk, etc',
        'Fabric finishes: moth-proofing, embossing, durable pleating, flame-proofing, stain-repellent, print e.g. tie and dye, screen printing etc',
        'Textile care label',
        'meaning and types',
        'recognition of washing, cleaning and ironing symbols, wool symbols, etc',
      ],
      objectives: [
        'identify the characteristics of fibre;',
        'differentiate between methods of fabric construction using diagrams;',
        'state reasons for giving finishes to fabrics;',
        'state the uses and importance of locally made fabric;',
        'compare types of labels found on clothing;',
        'state the importance of label on garments.',
      ],
    },
    'Sewing equipment and garment construction': {
      subtopics: [
        'Sewing machine, basic tools and equipment',
        'types, use and care',
        'Basic process in garment construction',
        'basic stitches, seams, edge finishes, crossway strips, etc',
        'Style features',
        'collars, yokes, pockets, frills, cuts, belts, etc',
        'Arrangement of fullness',
        'darts, tuck gathering, pleats, smocking, shirring, etc',
        'Decorative design',
        'embroidery, needlecraft, tarting, crocheting, knitting, appliqué, patch work and soft furnishing',
        'Simple processes and mend garments',
        'patching, darning, renovation, batik/tie and dye',
        'Garment construction',
        'figure types, basic body measurement and pattern drafting',
        'choice of styles for different figures',
        'factors influencing the choice of fabric',
        'Wardrobe planning and maintenance',
        'basic rules in wardrobe planning',
        'factors affecting wardrobe planning, weather, occupation, personal features etc.',
        'Good grooming, dress sense and accessories',
        'definition',
        'types and choice of accessories',
      ],
      objectives: [
        'identify the types, parts and faults of a sewing machine;',
        'identify basic tools and equipment used in garment construction;',
        'describe various process in garment constructions;',
        'apply basic process in garment construction;',
        'identify style features to enhance the beauty and quality of garments;',
        'apply decorative designs on fabrics;',
        'apply the knowledge of sewing to mend and renovate garments;',
        'compare the process of making batik/tie and dye, screen printing and resist dying;',
        'relate body figures to the selection of styles and fabrics;',
        'determine factors which affect the choice of clothing;',
        'identify factors to consider in wardrobe planning;',
        'describe the following terms: good grooming, dress sense, accessories, colour harmony.',
      ],
    },
    'Laundry and care of clothes': {
      subtopics: [
        'Washing and finishing process: sorting, mending, removal of stains, soaking, washing, rinsing, drying, ironing and airing',
        'Laundry agents – water, detergents, soaps, stiffness, disinfectants etc',
        'Stain',
        'meaning, types, agents',
        'process of removal',
        'Iron and ironing temperatures',
      ],
      objectives: [
        'arrange in correct order the processes involved in washing and finishing of clothing;',
        'describe the role of laundry agent;',
        'suggest ways of removing common stains;',
        'describe the following: laundry agents, stains, ironing temperatures.',
      ],
    },
  },
} as const

export type HomeEconomicsTopic = keyof typeof HOME_ECONOMICS_CONFIG.topics