export const IGBO_CONFIG = {
  name: 'Igbo',
  prefix: 'IGB',
  category: 'arts',
  priority: 13,
  totalQuestions: 40,
  topics: {
    'Language': {
      subtopics: [
        'Essay',
        'Types of essay',
        'Narration',
        'Description',
        'Argument',
        'Exposition',
        'Letter writing',
        'Comprehension',
        'Vocabulary development',
        'Idiomatic and figurative expressions',
        'Summary',
        'Sound system',
        'Vowels',
        'Consonants',
        'Syllabic nasals',
        'Syllable structure',
        'Tone',
        'Orthography',
        'Standard orthography',
        'Alphabet',
        'Word division',
        'Loan words',
        'Grammar',
        'Parts of speech',
        'Nouns',
        'Pronouns',
        'Verbs',
        'Adjectives',
        'Adverbs',
        'Conjunctions',
        'Prepositions',
        'Affixes',
        'Sentence structure',
        'Translation',
        'Translation from English to Igbo',
        'Translation from Igbo to English',
      ],
      objectives: [
        'identify the basic principles of essay writing;',
        'use words and expressions appropriate to a particular topic;',
        'differentiate between different essay types;',
        'describe the characteristics of essay types;',
        'compare different types of essay;',
        'criticize other people’s essays.',
        'explain the meanings of difficult words;',
        'give correct answers;',
        'differentiate between figurative and idiomatic expressions from the passage;',
        'deduce conclusion(s) based on the passage.',
        'identify vowels, consonants and syllabic nasals;',
        'distinguish between the speech sounds of the Igbo language;',
        'recognise semi-vowels and nasal homorganicity;',
        'divide words into syllables;',
        'identify the vowel groups in Igbo;',
        'describe vowel assimilation, vowel elision and consonant elision;',
        'assign tone marks appropriately.',
        'detect words written correctly in Igbo;',
        'determine appropriate word division in Igbo.',
        'indicate the Igbo orthography;',
        'distinguish between the Igbo and English orthography.',
        'differentiate between standard Igbo and dialects;',
        'use standard Igbo in their writings.',
        'differentiate between loan and coined words;',
        'identify loan words and loan-blends in Igbo;',
        'spell Igbo words appropriately.',
        'differentiate between grammatical categories;',
        'identify parts of speech and their functions;',
        'differentiate between types of affixes and their functions;',
        'determine types and characteristics of morphemes;',
        'identify words, phrases, clauses, sentences, their types and characteristics.',
        'translate English into Igbo and vice versa;',
        'communicate effectively in Igbo and English.',
      ],
    },
    'Literature': {
      subtopics: [
        'Figures of speech',
        'Alliteration',
        'Assonance',
        'Parallelism',
        'Metaphor',
        'Simile',
        'Hyperbole',
        'Personification',
        'Proverbs',
        'Oral literature',
        'Folktales',
        'Myths',
        'Legends',
        'Poems',
        'Songs',
        'Chants',
        'Riddles',
        'Oral drama',
        'Tongue-twister',
        'Written literature',
        'Prose',
        'Tony U. Ubesie (1993). Jụọ Obinna. Oxford University Press.',
        'Poetry',
        'Inno Ụzọma Nwadike (2014). Akọnuche. Obosi: Pacific Publishers Ltd.',
        'Selected Poems',
        'Ọchịchị',
        'Onye Ndu',
        'Nne Ọma',
        'Oke Ọchịchọ',
        'Asịla M Na Ọ Dị Mma',
        'Ihe Ụwa',
        'Jiri Nwayọ',
        'Eziokwu',
        'Mma',
        'Nwanyị',
        'Aja Ala',
        'Ala Igbo',
        'Ndụ M N’ụwa A',
        'Ọjị',
        'Ụwa Emebighi',
        'Amamihe',
        'Ndụ Nwaanyị',
        'Nna M Ọgọenyi',
        'Ụlọakwụkwọ',
        'Akwa Nnabuenyi Ugonna Bere',
        'Drama',
        'J. C. Maduekwe (1979). Otu Mkpịsị Aka. Longman Nigeria (Learn Africa)',
      ],
      objectives: [
        'identify all literary devices in the passages;',
        'interpret literary devices;',
        'differentiate between types of literary devices;',
        'use Igbo literary devices appropriately',
        'create folk stories, chants, riddles, oral drama etc.',
        'analyse various genres of oral literature;',
        'present ideas/formulae in accordance with underlying principles;',
        'apply the lessons of oral literature to their everyday life.',
        'interpret the text;',
        'isolate the characters in the book;',
        'identify figurative and idiomatic expressions in the text;',
        'analyse the text;',
        'identify the author, publisher and date of publication;',
        'draw moral lessons from the text.',
        'compare the types and themes of the poems;',
        'relate the poet’s idea to the contents of the poems;',
        'compare figurative and idiomatic expressions in the poems;',
        'analyse the structures of the poems;',
        'apply acquired knowledge and moral lessons from the poems to their daily lives.',
        'identify the type of drama the text belongs to;',
        'determine the themes in the text;',
        'identify the story lines;',
        'find out the characters in the book;',
        'appreciate the language style of the play;',
        'appraise the social problems raised by the author in the play;',
        'apply acquired knowledge to their personal lives.',
        'Identify the moral lessons from the drama text.',
      ],
    },
    'Culture': {
      subtopics: [
        'Greetings',
        'Morning greeting',
        'Afternoon greeting',
        'Evening greeting',
        'Greetings at meal time',
        'Greetings for the sick',
        'Greetings at bedtime',
        'Marriage and divorce',
        'Birth and childcare',
        'Naming ceremony',
        'Circumcision',
        'Title taking',
        'Nze and Ọzọ',
        'Eze/Obi/Igwe',
        'Iyọm/Lọọlọ',
        'Death and burial rites',
        'Extended family system',
        'Umunna',
        'Umuokpu/Umuada',
        'Iyomdi',
        'Nwadiala',
        'Age grades',
        'Traditional political organization',
        'Igwe/Eze',
        'Nze na Ọzọ',
        'Umunna',
        'Ezinaụlọ',
        'Umuokpu/Umuada',
        'Traditional worship',
        'Divination',
        'Sacrifice',
        'Oath taking',
        'Masquerade',
        'Okonko',
        'Ekpe',
        'Omabe',
        'Traditional occupations',
        'Farming',
        'Fishing',
        'Blacksmithing',
        'Trading',
        'Pottery',
        'Hunting',
        'Festivals',
        'Ọfala',
        'Iri ji',
        'Ịbọ ụzọ',
        'Akwamozu',
      ],
      objectives: [
        'describe the customs of their people;',
        'determine the rules and regulations guiding specified aspects of the culture and tradition of the Igbo people;',
        'describe the importance of the aspects of Igbo culture;',
        'identify changes that have occurred as a result of civilization;',
        'explore their environment for a better appreciation of their culture.',
      ],
    },
    'Contemporary Issues': {
      subtopics: [
        'Topical issues in the Igbo language, literature and culture',
        'Ahịajiọkụ',
        'Odenigbo lectures',
        'Ọhaneze Ndị Igbo',
        'Authors, publishers, dates and places of publication of works in Igbo',
        'Igbo Studies Association (ISA)',
        'HIV/AIDS',
        'Cancer',
        'Corona Virus',
        'Drug Abuse',
        'Cultism',
        'Rights of Women and Children',
        'Human Rights Violation and Child Abuse',
        'Religious Conflicts',
        'Kidnapping',
      ],
      objectives: [
        'identify some dates, themes and functions of Ahịajiọkụ, Odenigbo and Ọhaneze Ndị Igbo Lectures;',
        'identify authors, publishers and dates of publication of various textbooks in Igbo;',
        'acquaint themselves with the functions and contributions of the Igbo Studies Association (ISA).',
        'acquaint themselves with current issues;',
        'examine their effects;',
        'suggest remedies to the problems.',
      ],
    },
  },
} as const

export type IgboTopic = keyof typeof IGBO_CONFIG.topics