export const ISLAMIC_STUDIES_CONFIG = {
  name: 'Islamic Studies',
  prefix: 'IRS',
  category: 'arts',
  priority: 6,
  totalQuestions: 40,
  topics: {
    'Revelation of the Glorious Qur’ān': {
      subtopics: [
        'Visits of the Prophet (SAW) to Cave Hira',
        'His reaction to the first revelation and its importance',
        'Different modes of revelation (Q.42:51): inspiration behind the veil, through an angel, etc.',
        'Piecemeal revelation (Q.17:106) (Q.25:32)',
        'Names and attributes of the Qur’an',
      ],
      objectives: [
        'analyse the Prophet’s (SAW) visits to Cave Hira and the purpose;',
        'describe the Prophet’s reaction to the first revelation and its importance;',
        'differentiate between the modes of revelation;',
        'explain why the Glorious Qur’ān was revealed piecemeal.',
        'identify the names and attributes of the Qur’an',
      ],
    },
    'Preservation of the Glorious Qur’ān': {
      subtopics: [
        'Recording, compilation and standardization of the Qur’ān',
        'Differences between Makkah and Madinan suwar',
        'The role played by the Companions of the Prophet (SAW) on the collection and compilation of the Qur’ān.',
      ],
      objectives: [
        'analyse how the Glorious Qur’ān was recorded, compiled and standardized.',
        'differentiate between Makkan and Madinan suwar',
        'evaluate the role played by the companions of the Prophet (SAW) on the collection and compilation of the Qur’ān.',
      ],
    },
    'Importance of the Glorious Qur’ān as a source of guidance in spiritual, moral, economic, political and socio-cultural matters': {
      subtopics: [],
      objectives: [
        'examine the importance of the Glorious Qur’ān.',
      ],
    },
    'Divine authenticity of the Glorious Qur’ān': {
      subtopics: [
        'Proof of the Divine authenticity of the Glorious Qur’ān (Q.4:82) (Q.41:42)',
        'Uniqueness of the Glorious Qur’ān (Q.39:27) (Q.17:88) (Q.75:16-19)',
        'Divine preservation of the Glorious Qur’ān (Q.15:9)',
      ],
      objectives: [
        'evaluate the proof of the divine authenticity of the Glorious Qur’ān;',
        'evaluate the uniqueness of the Glorious Qur’ān;',
        'examine the ways by which the Glorious Qur’ān was preserved.',
      ],
    },
    'Tafsīr': {
      subtopics: [
        'Historical development of Tafsīr',
        'Importance of Tafsīr',
        'Types of Tafsir',
      ],
      objectives: [
        'trace the origin and sources of Tafsīr;',
        'evaluate the importance of Tafsīr',
        'identify the types of Tafsir',
      ],
    },
    'Introduction to Tajwīd (Theory and Practice)': {
      subtopics: [],
      objectives: [
        'examine the meaning and importance of Tajwīd',
      ],
    },
    'Study of the Arabic text of the following suwar/ayats with tajwīd': {
      subtopics: [
        'al-Fātihah (Q.1)',
        'al –cĀdiyāt (Q.100)',
        'al –Qari’cah (Q.101)',
        'at-Takāthur (Q.102)',
        'al –cAsr (Q.103)',
        'al-Humazah (Q.104)',
        'al-Mācūn (Q.107)',
        'al-Kawthar (Q.108)',
        'al-Kāfirūn (Q.109)',
        'al-Nasr (Q.110)',
        'al-Masad (Q.111)',
        'al-Ikhlās (Q.112)',
        'al-Falaq (Q.113)',
        'an-Nās (Q.114)',
        'al-Acalā (Q.87)',
        'ad-Duhā (Q.93)',
        'al-Inshirah (Q.94)',
        'at-Tīn (Q.95)',
        'al-cAlaq (Q.96)',
        'al-Qadr (Q.97)',
        'al-Bayyinah (Q.98)',
        'al-Zalzalah (Q.99)',
        'Ayatul-Kursiyy (Q.2:255)',
        'Āmanar-Rasūl (Q.2:285-6)',
        'Laqad jāakum (Q.9:128-129)',
      ],
      objectives: [
        'recite with correct tajwīd the Arabic texts of the suwar;',
        'translate the verses;',
        'deduce lessons from them;',
        'evaluate the teachings of the verses.',
      ],
    },
    'Hadīth': {
      subtopics: [
        'History of Hadīth literature - Collection of Hadīth from the time of the Prophet(SAW) to the period of the six authentic collectors of Hadīth',
        'Authentication of Hadīth',
        'Isnād (Asma’ur-rijāl)',
        'Matn',
        'Classification of Hadīth into Sahīh Hassan and Dacīf',
        'The relationship between Hadīth and the Glorious Qur’ān',
        'The importance of Hadīth',
        'The similarities and differences between Hadīth and the Glorious Qur’ān',
        'The six sound collectors of Hadīth – biographies and their works.',
        'Muwatta and its author – The biography of Imam Malik and the study of his book',
        'The study of the Arabic texts of the following ahādīth from an-Nawāwi’s collection: 1,3,5,6,7,9,10,11,12,13,15,16,18,19,21,22,25,27,34, and 41',
      ],
      objectives: [
        'evaluate the history of Hadīth from the time of the Prophet (SAW) to the period of six authentic collectors.',
        'analyse the Isnād;',
        'analyse the Matn;',
        'distinguish between Hadīth Sahīh, Hassan and dacīf.',
        'examine the importance of Hadīth;',
        'distinguish between Hadīth and the Glorious Qur’ān.',
        'evaluate their biographies and works',
        'evaluate his biography;',
        'analyse his work.',
        'interpret the ahādīth in Arabic',
        'apply them in their daily lives.',
      ],
    },
    'Moral lessons in the Glorious Qur’ān and Hadīth': {
      subtopics: [
        'General moral lessons contained in the admonition of Sage Luqman to his son (Q.31:12-18).',
        'Goodness to parents (Q.17:23-24)',
        'Honesty (Q.2:42)(Q.61:2-3)',
        'Prohibition of bribery and corruption (Q:2:188), alcohol and gambling (Q.2:219) (Q.5:90-91), stealing and fraud (Q.5:41) (83:1-5), smoking, drug abuse and other intoxicants (Q.2:172-173, 195 and 219) (Q.4:43) (Q.5:3) (Q.6:118-121) arrogance (Q.31:18-19) and extravagance (Q.17:26-27) (Q.31:18-19)',
        'Dignity of labour (Q.62:10) (Q.78:11) Hadīth from Bukhari and Ibn Majah: “that one of you takes his rope…….” “never has anyone of you eaten……”.',
        'Behaviour and modesty in dressing (Q.24:27-31) (Q.33:59)',
        'Adultery and fornication (Q.17:32) (Q.24:2), homosexuality (Q.11:77-83) and obscenity (Q:4:14-15) Hadīth – “No one of you should meet a woman privately …… “Bukhari',
        'Leadership (Q.2:124) and justice (Q.4:58 and 135) (Q.5:9) Hadīth – ‘take care everyone of you is a governor ….. concerning his subjects” (al-Bukhari and others)',
        'Trust and obligations (Q:4:58) (Q.5:1) and promises (Q.16:91) Hadīth ‘he has (really) no faith …. Not fulfilled his promise” (Baihaqi)',
        'Piety (Taqwa) (Q:2:177) (Q.3:102) (Q.49:13) Hadīth 18 and 35 of an Nawāwī',
        'Tolerance, perseverance and patience (Q.2:153-157) (Q.3:200) (Q.103:3) Hadīth 16 of an-Nawāwī',
        'Unity and brotherhood (Q.3:103) (Q.8:46) (Q.49:10) Hadīth 35 of an-Nawawi',
        'Enjoining what is good and forbidding what is wrong (Q.3:104 and 110) (Q.16:90) Hādīth 25 and 34 of an Nawāwī',
      ],
      objectives: [
        'use the teachings of the verses in their daily lives;',
        'apply the teachings of the verses to their daily lives;',
        'demonstrate the teachings of the verses in their daily lives.',
        'use the teachings of the verses in their daily lives',
        'apply the teachings of the verses in their daily lives.',
        'demonstrate the teachings of the verses in their daily lives.',
        'apply the teachings of the verses in their daily lives.',
        'apply the teachings of the verses and the Hadīth to their daily lives.',
        'demonstrate the teachings of the verses and the Hadīth in their daily lives.',
        'apply the teachings of the verses and the ahadīth in their daily lives.',
        'Interpret the teachings of the verses and the Hadīth in their daily lives.',
        'demonstrate the teachings of the verses and the Hadīth in their daily lives.',
        'apply the teachings of the verses and the ahadīth in their daily lives.',
      ],
    },
    'Faith': {
      subtopics: [
        'Tawhīd',
        'Its importance and lessons',
        'Kalimatush-Shahadah',
        'Its meaning and importance',
        'The Oneness of Allah as contained in the following verses: (Q.3:18) Q.2:255) (Q.112:1-4)',
        'The servanthood and messengership of the Prophet Muhammad (SAW) as contained in the following verses (Q.3:144) (Q.18:110) (Q.48:29) and (Q.34:28)',
        'Universality of his message (Q.7:158) (Q.34:28)',
        'Finality of his Prophethood (Q.33:40)',
      ],
      objectives: [
        'analyse the concepts of Tawhīd',
        'evaluate the significance of kalimatush-shahadah;',
        'identify the verses dealing with the Oneness of Allah.',
        'explain the significance of the servanthood of the Prophet Muhammad (SAW);',
        'evaluate the significance of the universality of Prophet Muhammad’s message;',
        'examine the significance of the finality of the Prophethood of Muhammad (SAW).',
      ],
    },
    'Shirk': {
      subtopics: [
        'Beliefs which are incompatible with the Islamic principles of Tawhīd:',
        'Worship of Idols (Q.4:48) (Q.22:31)',
        'Ancestral worship (Q.4:48 and 116) (Q.21:66-67)',
        'Trinity (Q.4:171) (Q.5:76) (Q.112:1-4)',
        'Atheism (Q.45:24) (Q.72:6) (Q.79:17-22)',
        'General practices which are incompatible with Islamic principles of Tawhīd:',
        'Superstition (Q.25:43) (Q.72:6)',
        'Fortune-telling (Q.15:16-18) (Q.37:6-10)',
        'Magic and witchcraft (Q.2:102) (Q.20:69) and 73) (Q.26:46)',
        'Cult worship (Q.17:23) (Q.4:48)',
        'Innovation (Bid’ah) (Q.4:116) and Hadīth 5 and 28 of an-Nawāwī',
      ],
      objectives: [
        'identify what actions and beliefs constitute shirk;',
        'explain the implications of beliefs and actions of shirk;',
        'appreciate why they should avoid actions of shirk.',
        'identify those practices that are incompatible with the Islamic principles of Tawhīd;',
        'examine those practices that are incompatible with Tawhīd;',
        'shun off those actions;',
        'demonstrate the teachings of the verses and the ahadīth in their daily lives.',
      ],
    },
    'Articles of faith': {
      subtopics: [
        'Belief in Allah',
        'Existence of Allah (Q.2:255) (Q.52:35-36)',
        'Attributes of Allah (Q.59:22-24)',
        'The works of Allah (Q.27:59:64)',
        'Belief in Allah’s angels (Q.2:177 and 285) (Q.8:50) (Q.16:2)',
        'His books (Q.2:253) and 285) (Q.3:3)',
        'His Prophets: Ulul-azmi (Q.4:163-164)',
        'The Last Day: Yawm-al-Bacth (Q.23:15-16) (Q.70:4)',
        'Destiny: distinction between Qada and Qadar (Q.2:117) (Q.16:40) (Q.36:82)',
      ],
      objectives: [
        'examine the significance of the articles of faith;',
        'list the attributes of Allah;',
        'examine the works of Allah;',
        'explain the belief in Allah’s books;',
        'identify the verses on Allah’s books;',
        'explain the belief in the Prophets of Allah and its significance;',
        'analyse the belief in the Last Day and its significance;',
        'evaluate the belief in destiny and its significance.',
      ],
    },
    'Ibadat and their types': {
      subtopics: [
        'Good deeds (Q.3:134) (Q.6:160) (Q.2:177) (Q.31:8) (Q.103:1-3) 26th Hadīth of an-Nawāwī',
        'Taharah, its types and importance (al-istinja’/istijmar, alwudu’, at-tayammum and al-ghusl (Q.2:222) (Q.5:7) Hadīth 10 and 23 of an-Nawāwī.',
        'Salah',
        'Importance: (Q.2:45) (Q.20:132) (Q.29:45) and Hadīth 23rd of an-Nawāwī',
        'Description and types of salah',
        'Things that vitiate salah',
        'Zakah',
        'Its types and importance (zakatul-fitr, zakatul mal, al-an-am and al-harth (Q.2:267) (Q.9:103) 3rd Hadīth of an-Nawāwī',
        'Collection and disbursement (Q.9:60)',
        'Difference between Zakah and sadaqah',
        'Sawm',
        'Its types and importance (fard, sunnah, qada and kaffarah) (Q.2:183-185) 3rd Hadīth of an-Nawāwī',
        'People exempted from sawm',
        'Things that vitiate sawm',
        'Hajj',
        'Its importance (Q.2:158 and 197) (Q.3:97) (Q.22:27-28)',
        'Type (Ifrad, Qirān and Tamattuc)',
        'Essentials of Hajj (Arkan al Hajj)',
        'Conditions for the performance of Hajj',
        'Differences between Hajj and Umrah',
        'Jihad: Concept, kinds, manner and Lessons (Q.2:190-193) (Q.22:39-40)',
      ],
      objectives: [
        'identity what constitutes acts of ibadah;',
        'distinguish between the different types of taharah;',
        'assess the importance of salah to a Muslim’s life;',
        'analyse different types of salah;',
        'identify things that vitiate salah.',
        'differentiate between the various types of zakkah and the time of giving them out;',
        'explain how to collect and distribute zakah;',
        'distinguish between zakah and sadaqah.',
        'compare the various types of sawm;',
        'list the people who are exempted from fasting;',
        'explain things that vitiate fasting.',
        'examine the importance of Hajj;',
        'differentiate between the types of Hajj;',
        'explain the essentials of Hajj;',
        'evaluate the conditions for performance of Hajj;',
        'differentiate between Hajj and Umrah.',
        'examine the concepts of jihad and its type;',
        'evaluate the manner of carrying out jihad and its lessons.',
      ],
    },
    'Family Matters': {
      subtopics: [
        'Marriage',
        'Importance (Q.16:72) (Q.24:32) (Q.30:20-21)',
        'Prohibited categories (Q.2:221) (Q.4:22-24)',
        'Conditions for its validity (Q.4:4) (Q.4:24-25)',
        'Rights and duties of husbands and wives (Q.4:34-35) (Q.20:132) (Q.65:6-7)',
        'Polygamy (Q.4:3 and 129)',
        'Idrar ill-treatment of wife (Q. 65:1-3)',
        'Divorce',
        'Attitude of Islam to divorce (Q.2:228) (Q.4:34-35) Hadīth “of all things lawful … most hateful to Allah..” (Abu Daud 15:3)',
        'Kinds (Talaq, Khul;, Faskh, Mubara’ah and Licān) (Q.2:229-230) (Q.24:6-9)',
        'Iddah, kinds, duration and importance (Q.2:228 and 234)',
        'Prohibited forms of dissolution of marriage. (Ila and Zihar) (Q.2:226-227) (Q.58:2-4)',
        'Custody of children (Hadanah)',
        'Inheritance',
        'Its importance',
        'Heirs and their shares (Q.4:7-8, 11-12 and 176)',
      ],
      objectives: [
        'analyse the importance of marriage;',
        'list the category of women prohibited to a man to marry;',
        'examine the conditions for validity of marriage;',
        'explain the rights and duties of the spouse;',
        'evaluate polygamy and its significance.',
        'examine the ill-treatment of wife in marriage',
        'analyse the attitude of Islam to divorce.',
        'examine the different kinds of divorce;',
        'differentiate between the various kinds of iddah;',
        'analyse its duration and significance.',
        'explain the prohibited forms of ending marriage.',
        'examine who has the right to custody of children.',
        'evaluate the significance of inheritance.',
        'identify the categories of the Qur’ānic heirs;',
        'explain the share of each heir;',
      ],
    },
    'Sources and Schools of Law': {
      subtopics: [
        'The four major sources (the Qur’ān, Sunnah, Ijmac and Qiyās)',
        'The four Sunni Schools of law and their founders.',
      ],
      objectives: [
        'analyse the four major sources of Islamic law;',
        'examine the biography of the founders of sunni schools of law;',
        'examine contributions of the founders of the sunni school of law',
      ],
    },
    'Islamic Economic System': {
      subtopics: [
        'Islamic attitude to Riba (Q.2:275-280) (Q.3:130) (Q.4:161) Hadīth 6th of an-Nawāwī',
        'At-tatfif (Q.83:1-6)',
        'Hoarding (ihtikar) (Q.9:34)',
        'Islamic sources of revenue: Zakah, Jizyah, Kharaj and Ghanimah',
        'Baitul-mal as an institution of socio-economic welfare',
        'Difference between the Islamic economic system and the Western economic system',
      ],
      objectives: [
        'analyse Islamic attitude to Riba;',
        'relate at-tatfif and its negative consequences;',
        'examine ihtikar and its implications on society.',
        'identify the sources of revenue in Islam;',
        'evaluate the disbursement of the revenue.',
        'explain the uses of baitul-mal in the Ummah.',
        'differentiate between the Islamic and Western economic systems.',
      ],
    },
    'Islamic Political System': {
      subtopics: [
        'Allah as the Sovereign (Q.3:26-27)',
        'The concept of Shurah (consultation) (Q.3:159( (Q.42:38)',
        'The concept of Adalah (justice) (Q.5.9) (Q.4:58 and 135) and Mas’uliyah (accountability)(Q.17:36) (Q..102:8)',
        'The rights of non-Muslims in an Islamic state (Q.2:256) (Q.6:108)',
        'Differences between the Islamic political system and the Western political system.',
      ],
      objectives: [
        'analyse the concept of Allah’s sovereignity;',
        'examine the concept of shurah in Islam;',
        'evaluate the concept of justice and accountability;',
        'examine the rights of non-Muslims in an Islamic state;',
        'differentiate between the Islamic and Western political systems.',
      ],
    },
    'Pre-Islamic Arabia (Jahiliyyah)': {
      subtopics: [
        'Jahiliyyah practices: idol worship, infancticide, polyandry, gambling, usury, etc.',
        'Islamic reforms',
      ],
      objectives: [
        'distinguish the different types of practices common to the Arabs of al-Jahiliyyah;',
        'trace the reforms brought about by Islam to the Jahiliyyah practices.',
      ],
    },
    'The Life of Prophet Muhammad (SAW)': {
      subtopics: [
        'His birth and early life',
        'His call to Prophethood',
        'His Dacwah in Makkah and Madinah',
        'The Hjrah',
        'His administration of the Ummah in Madinah',
        'The battles of Badr, Uhud and Khandaq: causes and effects',
        'The Treaty of al-Hudaibiyyah and the conquest of Makkah',
        'Hijjatul-wada (the farewell pilgrimage) sermon, and lessons.',
        'Qualities of Muhammad (SAW) and lessons learnt from them',
      ],
      objectives: [
        'account for the birth and early life of the Prophet Muhammad (SAW);',
        'provide evidence for the call of Muhammad (SAW) of Prophethood;',
        'analyse the Dacwah activities of the Prophet Muhammad (SAW) to Madinah;',
        'account for the Hijrah of the Prophet Muhammad (SAW) in Makkah and Madinah.',
        'analyse the administration of the Muslim Ummah in Madinah.',
        'account for the causes and effects of the battles of Badr, Uhud and Khandaq;',
        'trace the circumstances leading to the formulation of the Treaty of Hudaibiyya;',
        'account for the Conquest of Makkah;',
        'examine the farewell pilgrimage of the Prophet and its lessons;',
        'analyse the qualities of Muhammad (SAW) their relevance to the life of a Muslim.',
      ],
    },
    'The Rightly Guided Caliphs (al-Khulafa’u rashidun) – the lives and contributions of the four Rightly Guided Caliphs': {
      subtopics: [],
      objectives: [
        'trace the biographies of the four Rightly Guided Caliphs;',
        'evaluate their contributions to the development of Islam.',
      ],
    },
    'Early contact of Islam with Africa': {
      subtopics: [
        'Hijrah to Abyssinia',
        'The spread of Islam to Egypt',
        'The role of traders, teachers, preachers, Murabitun, Sufi orders and Mujaddidun to the spread of Islam in West Africa.',
      ],
      objectives: [
        'evaluate their circumstances leading to the Hijrah to Abyssinia;',
        'give reasons for the spread of Islamic in Egypt;',
        'account for the roles of traders, teachers, preachers, Murabitun, Sufi orders and Mujaddidun in the spread of Islam in West Africa.',
      ],
    },
    'The Impact of Islam in West Africa': {
      subtopics: [
        'The influence of Islam on the socio-political life of some West African Empires: Ghana, Mali, Songhai and Borno',
        'The impact of Islam on the economic life of some West African states: Timbuktu, Kano and Borno',
      ],
      objectives: [
        'analyse the influence of Islam on the socio-political system of some West African States;',
        'evaluate the impact of Islam on the economic life of Timbuktu, Kano and Borno.',
      ],
    },
    'Contributions of Islam to Education': {
      subtopics: [
        'The aims and objectives of Islamic Education',
        'The Glorious Qur’ān and Hadīth on Education (Q.96:1-5) (Q.39:9)',
        '“The search for knowledge is obligatory on every Muslim” (Ibn Majah)',
        '“Seek knowledge from the cradle to the grave”',
        '“The words of wisdom are a lost property of the believer … a better right to it…. “ (Tirmidhi)',
        'Intellectual activities of Islam in West Africa (development of written history in Arabic and the establishment of Sankore University)',
        'Intellectual activities of Ahmad Baba of Timbuktu, Sheikh al-Maghili, Sheikh Usman Danfodio, Sultan Muhammad Bello and Ibn Battuta',
        'Islamic Education Institutions: House of Wisdom in Baghdad, al-Azhar University in Cairo and Nizamiyyah University in Baghdad.',
        'The lives and contributions of Ibn Sina, Al-Ghazali, Ibn Rushd, ar-Razi and Ibn Khaldun to education.',
      ],
      objectives: [
        'explain the aims and objectives of Islamic Education;',
        'assess the position of the Glorious Qur’ān and Hadīth in education;',
        'examine the importance of seeking knowledge in Islam;',
        'analyse the intellectual activities of Islam in West Africa.',
        'assess the contributions of Sheikh al-Maghili, Sheikh Uthman Dan Fodio, Sultan Muhammad Bello and Ibn Battuta to education;',
        'account for the development of intellectual centres in Baghdad and Cairo;',
        'examine the contributions of Ibn Sina to the development of Medicine;',
        'assess al-Ghazali’s contribution to Islamic education;',
        'analyse Ibn Rushd’s contribution to philosophy and fiqh;',
        'assess ar-Razi’s contribution to philosophy;',
        'analyse Ibn Khaldun’s contribution to modern sociology and method of writing history.',
      ],
    },
  },
} as const

export type IslamicStudiesTopic = keyof typeof ISLAMIC_STUDIES_CONFIG.topics