export const LITERATURE_IN_ENGLISH_CONFIG = {
  name: 'Literature in English',
  prefix: 'LIT',
  category: 'arts',
  priority: 2,
  totalQuestions: 40,
  topics: {
    'DRAMA': {
      subtopics: [
        'Types:',
        'Tragedy',
        'Comedy',
        'Tragicomedy',
        'Melodrama',
        'Farce',
        'Opera etc.',
        'Dramatic Techniques',
        'Characterisation',
        'Dialogue',
        'Flashback',
        'Mime',
        'Costume',
        'Music/Dance',
        'Décor/scenery',
        'Acts/Scenes',
        'Soliloquy/aside',
        'Figures of Speech.',
        'Interpretation of the Prescribed Texts',
        'Theme',
        'Plot',
        'Socio-political context',
        'Setting',
      ],
      objectives: [
        'identify the various types of drama;',
        'analyse the contents of the various types of drama;',
        'compare and contrast the features of different types of drama.',
        'demonstrate adequate knowledge of dramatic techniques and stage directions used in each prescribed text;',
        'differentiate between styles of selected playwrights;',
        'determine the theme of any prescribed text;',
        'identify the plot of the play;',
        'apply the lessons of the play to social reality.',
        'identify the spatial setting and temporal period of the play.',
      ],
    },
    'PROSE': {
      subtopics: [
        'Types: Prose fiction',
        'Fiction',
        'Novel',
        'Novella/Novelette',
        'Short story',
        'Non-fiction',
        'Biography',
        'Autobiography',
        'Memoir',
        'Faction: combination of fact and fiction',
        'Narrative Techniques/Devices:',
        'Point of view',
        'Omniscient',
        'First Person',
        'Second person',
        'Third person',
        'Stream of consciousness',
        'Epiphany',
        'Characterisation',
        'Round, flat, foil, hero, antihero villain, heroine. etc',
        'Language',
        'Textual Analysis',
        'Theme',
        'Plot',
        'Setting (Temporal/Spatial)',
        'Socio-political context',
      ],
      objectives: [
        'differentiate between types of novel.',
        'identify the category that each prescribed text belongs to;',
        'analyse the components of each type of prose;',
        'identify the balance of facts and fiction in literary faction.',
        'identify the narrative techniques used in each of the prescribed texts;',
        'determine an author’s narrative style;',
        'distinguish between one type of character from another;',
        'determine the thematic pre-occupation of the prescribed text;',
        'indicate the plot of the novel;',
        'identify the setting and period/timing of the novel.',
        'relate the prescribed text to social reality.',
      ],
    },
    'POETRY': {
      subtopics: [
        'Types:',
        'Sonnet',
        'Ode',
        'Lyrics',
        'Elegy',
        'Ballad',
        'Panegyric',
        'Epic',
        'Blank Verse, etc.',
        'Poetic devices',
        'Imagery',
        'Sound (Rhyme/Rhythm, repetition, pun, onomatopoeia, etc.)',
        'Diction',
        'Persona',
        'Appreciation',
        'Thematic preoccupation',
        'Socio-political relevance',
        'Style.',
      ],
      objectives: [
        'identify different types of poetry;',
        'identify the distinctive features of the poetic types.',
        'determine the devices used by various poets;',
        'show how poetic devices are used for aesthetic effect in each poem;',
        'identify the figure of speech in the texts.',
        'Show how poetic devices convey message and meaning.',
        'Deduce the poet’s thematic preoccupation from the poem;',
        'appraise poetry as an art with moral values;',
        'apply the lessons from the poem to social reality.',
      ],
    },
    'GENERAL LITERARY TERMS AND PRINCIPLES': {
      subtopics: [
        'Literary terms:',
        'foreshadowing',
        'suspense',
        'theatre',
        'monologue',
        'dialogue',
        'soliloquy',
        'symbolism',
        'protagonist',
        'antagonist',
        'figures of speech',
        'satire',
        'stream of consciousness',
        'synecdoche',
        'metonymy',
        'etc,',
        'in addition to those listed above under the different genres.',
      ],
      objectives: [
        'identify literary terms that are specific to drama, prose and poetry;',
        'identify areas of overlap in all the genres e.g. verse in drama and poetry, narration in all the genres.',
      ],
    },
    'LITERARY APPRECIATION': {
      subtopics: [
        'Unseen passages/extracts from Drama, Prose and Poetry.',
      ],
      objectives: [
        'identify literary devices used in a given passage/extract;',
        'provide an interpretation of the given passage/extract;',
        'relate the extract to true life experiences.',
      ],
    },
  },
} as const

export type LiteratureInEnglishTopic =
  keyof typeof LITERATURE_IN_ENGLISH_CONFIG.topics