export const MUSIC_CONFIG = {
  name: 'Music',
  prefix: 'MUS',
  category: 'arts',
  priority: 9,
  totalQuestions: 40,
  topics: {
    'RUDIMENTS OF MUSIC': {
      subtopics: [
        'The staff:',
        'great staff,',
        'ledger lines and spaces,',
        'open score (vocal score) and',
        'C clef, alto (viola clef) and tenor clef.',
        'Music Notes/Rests and their corresponding values.',
        'Time/Time signature:',
        '(simple and compound time signatures), the correct grouping of notes and barring of unbarred passages.',
        'A – Key signatures and scales:',
        'technical names of the various degrees of the scale',
        'diatonic major/minor (natural, harmonic and melodic)',
        'chromatic scales.',
        'B – Determination of the key of a piece of music with or without key signature NOT exceeding two sharps and two flats.',
        'Keyboard setting and enharmonic equivalents',
        'Accidentals',
        'Intervals:',
        'Recognition of diatonic / chromatic intervals and their inversions (e.g. perfect unison, perfect 4th, perfect 5th, perfect 8ve), major/minor 2nd, 3rd, 6th and 7th, diminished 5th and augmented 4th',
        'Recognition of consonant and dissonant intervals.',
        'Definition of simple musical terms, signs and abbreviations.',
        'Transcription of music from staff into tonic solfa notation and vice-versa.',
        'Transposition using the treble (G) and bass (F) staves NOT exceeding two sharps and two flats.',
      ],
      objectives: [
        'identify all the components of the staff and their application.',
        'determine the relative duration of different notes and rests.',
        'interpret varied rhythmic patterns.',
        'ascertain names of the various degrees of the diatonic scales.',
        'identify simple scale passages with or without key signature.',
        'identify the names of the white and black keys and their relationship, e.g. C sharp = = Bx',
        'determine different qualities of intervals (melodic and harmonic).',
        'interpret simple musical signs and terms.',
        'read music in any given notation.',
        'rewrite a music passage on a given stave.',
      ],
    },
    'ELEMENTARY HARMONY': {
      subtopics: [
        'Triads and their inversions in major/minor keys, NOT exceeding two sharps and two flats.',
        'Primary triads in major keys.',
        'Secondary triads in major keys.',
        'Basic chord progressions in four parts vocal style (SATB) in major keys NOT exceeding two sharps and two flats.',
        'Dominant 7th chord in root position only',
        'Kinds of motion;',
        'Parallel, Similar, Contrary and Oblique',
        'Cadences in major keys NOT exceeding two sharps and two flats.',
        'perfect / full close cadence',
        'imperfect / half close / semi cadence',
        'plagal / Amen cadence',
        'interrupted / deceptive / evaded / surprise cadence.',
        'Non-harmonic tones / Non-chord tones; identification and application of the following:',
        'neighbouring tones / auxiliary notes',
        'passing tones / notes',
        'MODULATION',
        'Simple diatonic modulations (using a single melodic line) from any given major key NOT exceeding two sharps and two flats to any of its closely related keys (dominant and subdominant).',
        'Elementary Composition',
        'Setting of words to written melody',
        'Recognition of suitable answers to given musical phrases',
      ],
      objectives: [
        'identify triads;',
        'compare types of triads;',
        'determine the use of triads.',
        'determine the basic chord progressions in a music passage;',
        'recognize the dominant 7th chord.',
        'identify the various kinds of motion in a musical passage.',
        'identify the various types of cadences in a musical score.',
        'relate harmonic or non-harmonic tones to the chords with which they are associated.',
        'determine the key of a given melody and its modulation.',
        'identify suitable melody to given words, compatible, balanced or contrasting phrases.',
      ],
    },
    'HISTORY AND LITERATURE OF AFRICAN MUSIC': {
      subtopics: [
        'Nigerian folksongs, types, forms and characteristics.',
        'Types: cradle, folk-tales, games, war, satirical, dirges / funeral, historical, praise and worksong, etc.',
        'Forms: call and response, strophic, through-composed, antiphony, etc.',
        'Characteristics:',
        'Vocal styles: recitative, yodeling, ululation, incantation, heaving, whistling, nasalisation, etc.',
        'Scales/modes: tritonic, tetratonic, pentatonic, hexatonic etc.',
        'Metre/Rhythm: Metric and non-metric, polymetric, cross rhythm, syncopation, hemiola, poly-rhythm, etc.',
        'General knowledge of the features and forms of Nigerian traditional music and other arts.',
        'Festivals: e.g. Osun, Ifa, Ogun, Ekpo, Ofala, Iriji (New Yam Festival), Ovia Osese, Mmanwu (Masquerade), Ila-Oso, Argungu (Fishing), Eyo/Adamu-Orisa, Gelede, etc.',
        'Dances and other arts: Social, Ritual and Ceremonial e.g. Masquerade, Koroso, Atilogwu, Ikperikpe (War dance), Egedeege, Kwaghir, Agbon, Nkwa Umuagbogho, Bata, Bori, Swange, Dundun, Kokoma, Abigbo, Okonko, etc.',
        'INSTRUMENTS',
        'Nigerian traditional musical instruments:',
        'CLASSIFICATIONS',
        'Aerophones',
        'Chordophones',
        'Idiophones',
        'Membranophones',
        'Knowledge of the lives and music of the following African traditional musicians:',
        'NIGERIANS',
        'OTHER AFRICANS',
        'Evolution and Development of African Popular Music:',
        'Highlife, Juju, Afro-beat, Fuji, Apala, Reggae, Makosa, Ikwokirikwo, Okukuseku, Ekassa, Akuko na egwu, Awurebe, Waka, Hiplife, Hip-hop, etc.',
        'Knowledge of the lives and music of the following African Popular Musicians.',
        'NIGERIANS',
        'OTHER AFRICANS',
        'Knowledge of the lives and music of the following African Art Musicians:',
        'NIGERIANS',
        'OTHER AFRICANS',
      ],
      objectives: [
        'identify various folksongs and their types;',
        'define and compare their forms and features.',
        'analyse the features and forms of Nigerian traditional music and the arts;',
        'differentiate between the various types of festivals and dances.',
        'differentiate between the various types and classes of musical instruments;',
        'classify them into their categories.',
        'identify different groups to which various musicians belong;',
        'trace their biographies;',
        'mention their musical styles;',
        'assess their contributions to the music industry.',
        'differentiate one musical genre from another;',
        'examine their influence on society.',
        'relate the musicians to the music they perform;',
        'trace their biographies;',
        'examine their type of music;',
        'assess their contributions to the development of music.',
        'relate the musicians to the music they perform;',
        'trace their biographies;',
        'examine their type of music;',
        'assess their contributions to the development of music.',
      ],
    },
    'HISTORY AND LITERATURE OF WESTERN MUSIC': {
      subtopics: [
        'Historical development of Western music styles in respect of the periods',
        'Medieval/Middle Age (800 – 1400).',
        'Renaissance period (1400 – 1600).',
        'Baroque period (1600 – 1750).',
        'Classical period (1750 – 1820).',
        'Romantic period (1820 – 1900).',
        'COMPOSERS',
        'Palestrina, Claudio Monteverdi, Henry Purcell, J.S. Bach, G. F. Handel, W. A. Mozart, Franz Joseph Haydn, Ludwig van Beethoven, Franz Schubert, Frederic Chopin, etc.',
        'MUSIC FORMS AND MEDIA',
        'Binary, Ternary, Rondo, Sonata Allegro, Dance Suite, Canon, Free Fantasia, Theme and variation, etc.',
        'Orchestral and Band instruments and classifications',
        'The human voice (its types, ranges and qualities)',
        'Keyboard Instruments – the organ, piano and electronic keyboard, e.t.c.',
        'Knowledge of the following instruments: ukulele, banjo, guitar, mandolin, harp, accordion, xylophone, marimba, etc.',
        'Computer Music Technology: software (Finale, Sibelius, Cubase, Reason, Sound Forge Nero), tuning fork, pitch pipe etc.',
      ],
      objectives: [
        'trace the stages of the development of western musical practice from the medieval to the end of the romantic period.',
        'identify the composers;',
        'assess their contributions.',
        'identify the general forms and various types of instruments in Western music;',
        'relate music to modern technology.',
      ],
    },
    'COMPARATIVE MUSIC STUDIES': {
      subtopics: [
        'An overview of the following black musicians (composers, performers, etc) in the diaspora.',
        'Forms to be examined include spirituals, gospel music, jazz, rhythm and blues, soul, calypso, rock ‘n’ roll, reggae, afro-beat, tango, rap, chachacha, bolero, twist, hip-hop, etc.',
        'The spirit of nationalism in Nigerian music.',
      ],
      objectives: [
        'identify the musicians in the diaspora by their names;',
        'assess their individual musical influences on the global society.',
        'identify the various forms of musical genres;',
        'trace the origins of the musical genres.',
        'identify some of the features and materials used by nationalist composers to create, project and sustain cultural and patriotic awareness;',
        'assess their roles in Nigerian nationalism.',
      ],
    },
  },
} as const

export type MusicTopic = keyof typeof MUSIC_CONFIG.topics