export const PHYSICAL_HEALTH_EDUCATION_CONFIG = {
  name: 'Physical & Health Education',
  prefix: 'PHE',
  category: 'science',
  priority: 8,
  totalQuestions: 40,
  topics: {
    'Foundations and Principles of Physical and Health Education': {
      subtopics: [
        'Principles, meaning, scope and philosophy of Physical Education (PE)',
        'Definition, nature, scope and objectives of PE.',
        'Philosophy of the Founding Fathers of PE (Hetherington, Dudley Sergent, Thomas Wood, John Dewey).',
        'History and Development of PE in',
        'ancient Greece (Sparta, Athens) and Rome.',
        'Pre-colonial, colonial and post-colonial eras in Nigeria.',
        'Philosophy, objectives and settings of Health Education',
        'Meaning, philosophy and objectives of Health Education',
        'Settings of Health Education',
        'home-based',
        'school-based',
        'community based',
        'health facility-based',
        'workplace-based',
        'Meaning of Health Promotion',
      ],
      objectives: [
        'state the meaning, nature, objectives and scope of PE;',
        'narrate the philosophy of the Founding Fathers;',
        'trace the historical development of PE in ancient Greece, Rome and Nigeria.',
        'trace the origin and development of the ancient Greek festivals (Isthmian, Pythian, Nemian and the Olympian).',
        'define health education;',
        'state the philosophy and objectives of health education;',
        'differentiate between the meanings of health promotion and health education.',
      ],
    },
    'Human Anatomy and Physiology in Relation to PHE': {
      subtopics: [
        'Cells, Tissues and Systems of the Human Body',
        'Structure and functions of a typical human cell',
        'Types of cell and tissue – Epithelial, connective, muscle and nerve.',
        'Cell division and differentiation – mitosis, meiosis',
        'Organs and systems of the human body.',
        'Skeletal system',
        'Axial and appendicular skeletons and their functions',
        'Bones and joints involved in movement',
        'Structure and types of bone',
        'Structure and types of joint',
        'Movements at the joints',
        'Muscular System',
        'Major muscles of the body and their functions',
        'Isometric and Isotonic contractions',
        'Nervous System and Sense organs',
        'The structures and functions of the central nervous system (Brain and Spinal Cord)',
        'Types of nerve - voluntary, involuntary (simple reflex action)',
        'Structure and functions of the sense organs;',
        'Skin (tactile/touch)',
        'Nose (olfactory/Smell)',
        'Tongue (taste)',
        'Ear (auditory/hearing)',
        'Eye (sight)',
        'Circulatory System',
        'Structure and functions of the heart and vessels;',
        'Composition and functions of blood',
        'Types of blood circulation (Systemic and pulmonary)',
        'Respiratory System',
        'Structure and functions of the respiratory organs –nose, trachea and lungs;',
        'Process of respiration –inspiration and expiration',
        'Tissue and cellular respiration',
        'Excretory System',
        'Structure and functions of the kidney, skin and excretory functions of lungs;',
        'Formation of excretory products –urine, sweat and carbon-dioxide.',
        'Somatotypes and Posture',
        'Description of endomorph, mesomorph and ectomorph;',
        'Relationship between body types and physical activities.',
        'Definition and characteristics of correct posture;',
        'Types of postural defect –flatfoot, scoliosis, kyphosis, lordosis;',
        'Causes and corrective measures of postural defects.',
      ],
      objectives: [
        'identify cell structures and their functions',
        'identify types of cell, tissue, organ and system in human;',
        'differentiate between mitosis and meiosis;',
        'explain cell differentiation',
        'list organs and systems in human body.',
        'identify the structure of the human skeleton and their functions;',
        'identify types of bone that make up the human skeleton;',
        'differentiate types of joint using appropriate examples;',
        'identify the different kinds of movement permitted at joints.',
        'identify by name and location the major muscles in human;',
        'state the functions of major muscles in human;',
        'differentiate between isometric and isotonic contractions',
        'identify the structures of the central nervous system;',
        'explain the functions of the central nervous system in the body;',
        'state the types of nerve;',
        'describe reflex action with specific examples;',
        'describe the structure of the sense organs and their functions.',
        'draw and label the heart;',
        'compare the specific functions of the arteries, veins and capillaries;',
        'identify the components of blood;',
        'state the functions of blood;',
        'describe the systemic and pulmonary circulations;',
        'describe the structure of the respiratory organs and state their functions;',
        'explain the processes of inspiration and expiration;',
        'explain cellular and tissue respiration.',
        'identify the structure of the kidney, skin;',
        'state the functions of the kidney, skin and excretory functions of lungs;',
        'explain the processes of formation of urine, sweat and carbon-dioxide.',
        'describe the various body types;',
        'relate body types to performance of physical activities;',
        'define and state the characteristics of good posture.',
        'explain the types of postural defects;',
        'state the causes of postural defects, for example: poor habits, accident, heredity and disease;',
        'explain the role of exercise, nutrition, good habits and medical intervention in the correction of postural defects.',
      ],
    },
    'Theory of Practice of Sports and Games': {
      subtopics: [
        'Athletics (Track and Field Events)',
        'Track Events',
        'Short distance races/sprints -50m, 100m, 200m, 400m, hurdles and relay races.',
        'Sprints start styles–bullet/bunch, medium and elongated.',
        'Visual and non-visual baton take-over and take over zone in relay.',
        'Flight over hurdles and distancing in high and low hurdle events.',
        'The start, stride and finish in middle distance races -800m and 1,500m.',
        'The start, stride and finish in long distance races -3,000m, 5,000m, 10,000m, marathon and cross-country.',
        'Rules, regulation and officiating.',
        'Field Events',
        'Throwing events –discus, javelin and shotput.',
        'Facilities and equipment with specification',
        'Styles and techniques',
        'Rules, regulations and officiating',
        'Safety measures.',
        'Jumping events –high jump, long jump, pole vault and triple jump',
        'Facilities and equipment with specification',
        'Style and techniques',
        'Rule, regulations and officiating.',
        'Ball Games -Football and basketball',
        'Skills in football and basketball',
        'Facilities and equipment in football and basketball',
        'Rules, regulations and officiating in football and basketball.',
        'Racket Games –Table tennis and badminton',
        'Skills in table tennis and badminton',
        'Specification of facilities and equipment in table tennis and badminton',
        'Rules, regulation and officiating in table tennis and badminton.',
      ],
      objectives: [
        'name the events that make up the shot distance/sprint races;',
        'identify starting styles in sprint races;',
        'differentiate the visual and non-visual types of baton take-over;',
        'explain the relay take-over zone;',
        'explain the different distances and clearance in hurdling;',
        'describe the start, stride and finish in middle and long distance races.',
        'name the events which make up the middle distance and long distance races;',
        'differentiate the rules, regulations and officiating as applicable to each track events.',
        'name the events which make up throwing and jumping events;',
        'identity various facilities, equipment and specifications;',
        'explain the styles and techniques in throwing and jumping events;',
        'explain the rules and regulations in throwing and jumping events;',
        'discuss safety precautions in throwing events.',
        'describe the skills in football and basketball;',
        'identify various facilities and equipment in football and basketball;',
        'identify the officials of the games of football and basketball and their functions;',
        'differentiate the rules and regulations of football and basketball.',
        'describe the skills in table tennis and badminton;',
        'identify various facilities and equipment in table tennis and badminton;',
        'identify the officials in table tennis and badminton and state their functions.',
        'differentiate the rules and regulations of table tennis and badminton.',
      ],
    },
    'Food, Nutrition and Drugs': {
      subtopics: [
        'Food',
        'Classes, sources and importance of food nutrients.',
        'Definition and composition of balanced diet.',
        'Diet planning for different groups of people –children, adolescents, athletes, pregnant women and aged;',
        'Food preservation, hygiene, preservation and storage.',
        'Nutrition',
        'Definition and nutritional values of beverages.',
        'Common nutritional deficiencies and their remedies',
        'Importance of water in human nutrition.',
        'Drugs',
        'Meaning and types –stimulants, narcotics, hallucinogen, sedatives and ergogenic aids;',
        'Use, misuse and abuse;',
        'Causes and prevention of drug misuse and abuse;',
        'Effects of drug misuse, abuse and self-medication on the body.',
      ],
      objectives: [
        'indicate the sources and importance of the various classes of food nutrients;',
        'define balanced diet and state its importance;',
        'draw up and specify dietary requirements for different groups of people;',
        'explain methods for food preparation, preservation and storage;',
        'explain the principles of food hygiene.',
        'define nutrition and state the nutritional values of beverages;',
        'state the common nutritional deficiencies and their remedies;',
        'highlight the importance of water in human nutrition.',
        'define drug and state the types;',
        'differentiate between drug misuse and abuse;',
        'state causes and prevention of drug misuse and abuse;',
        'explain the effects of drug misuse, abuse and self-medication on the body.',
      ],
    },
    'Physical Fitness and Conditioning Programmes': {
      subtopics: [
        'Physical fitness',
        'Definition of physical fitness;',
        'Components of physical fitness –health-related and performance/skill-related.',
        'Benefits of physical activity and exercise.',
        'Conditioning Programme',
        'Aerobic programme',
        'Anaerobic programme',
        'Strength training programme',
        'Endurance training programme',
      ],
      objectives: [
        'define physical fitness;',
        'outline and explain components of physical fitness;',
        'give examples of health-related and performance/skill-related components;',
        'state the benefits of physical activity and exercise;',
        'differentiate between aerobic and anaerobic programmes;',
        'differentiate between strength and endurance training programme.',
      ],
    },
    'Recreation, Leisure and Dance': {
      subtopics: [
        'Recreation and leisure',
        'Definition and importance of recreation, leisure, work and rest;',
        'Types of recreational activities',
        'Outdoor –jogging, swimming, cycling, watching birds, hiking, camping, picnicking.',
        'Indoor –viewing TV, videogames, computer games, playing musical instruments, billiards, card games, Ayo, draught.',
        'Differences between recreational activities and competitive sports.',
        'Dance',
        'Definition and importance of dance.',
        'Traditional dances and dance steps from various parts of Nigeria.',
        'Costumes for the various traditional dances in Nigeria.',
      ],
      objectives: [
        'differentiate among recreation, leisure, work and rest;',
        'state the importance of recreation, leisure, work and rest;',
        'mention types of recreation and give examples of each;',
        'differentiate between recreational activities and competitive sports;',
        'state safety measures in recreation.',
        'define dance and state its importance;',
        'identify traditional dances from various parts of Nigeria;',
        'describe the dance steps for various traditional dances in Nigeria.',
        'identify the costumes for the various traditional dances.',
      ],
    },
    'First Aid and Safety Education': {
      subtopics: [
        'First Aid',
        'Definition of first aid',
        'Aims and principles of first aid',
        'Qualities of a first aider',
        'First aid box and contents',
        'Common injuries that require first aid –cuts, wound, sprain, strain, dislocation, fracture',
        'Special conditions that require first aid –bleeding, burn, scald, shock, poisoning',
        'Agencies/bodies involved in first aids –St. John’s Ambulance, Red Cross Society',
        'Safety Education',
        'Meaning and types of accident and disaster',
        'Causes and prevention of accident and disaster',
        'Disaster relief activities',
        'Safety at home, workplace, school and community',
      ],
      objectives: [
        'define first aid;',
        'state the aims and principles of first aid;',
        'outline the qualities of a first aider;',
        'list the contents of the first aid box and their uses;',
        'identify types of common injury;',
        'identify types of common condition that require first aid;',
        'identify agencies involved in fist aids services.',
        'define accident and disaster;',
        'identify types of accident and disaster;',
        'state the causes and prevention of accident and disaster;',
        'identify various disaster relief activities;',
        'explain safety measures at home, workplace, school and community.',
      ],
    },
    'National and International Sports Competitions': {
      subtopics: [
        'Sports competitions at national level',
        'Types of competition',
        'National sports competitions organized by different Sports Federations/Associations.',
        'National sports competitions organized by Corporate Organizations',
        'Importance of the National Sports Festival',
        'Organisation and administration of sports competitions',
        'Names and roles of institutional games',
        'The University Games (NUGA)',
        'The Polytechnic Games (NIPOGA)',
        'The Colleges of Education Games (NATCEGA)',
        'National School Sports Games (NSSF)',
        'International sports competitions and the governing bodies',
        'All Africa Games',
        'History and evolution of All Africa Games',
        'Aims of All Africa Games',
        'International sports governing bodies - Names and administrative structure of SCSA, IOC, FIFA, IAAF, ISSF, FIBA, ITTF, BWF.',
      ],
      objectives: [
        'identify by name, sports competitions organized by sports Federations/Association and Corporate Organizations;',
        'state the importance of the National Sports Festival;',
        'highlight the organizational and administrative structures of sports competitions in Nigeria;',
        'state the names and roles of the different institutional games;',
        'narrate the history and evolution of the All Africa Games',
        'identify the aims of the All Africa Games;',
        'identify by name, international sports governing bodies;',
        'describe the administrative structure of international governing bodies.',
      ],
    },
    'Corrective and Adapted Physical Education Programme': {
      subtopics: [
        'Meaning and types of disability and special needs.',
        'Adapted physical activities for people with disabilities and special needs',
        'Social and emotional problems of people with special needs',
        'Prevention of disability',
        'Corrective exercises to rehabilitate people with special needs',
      ],
      objectives: [
        'define disability and describe people with special needs;',
        'identify types of disability and special need;',
        'identify physical activities for people with disabilities and special needs;',
        'state the social and emotional problems of people with disabilities;',
        'state preventive measures of disability;',
        'state corrective exercise to rehabilitate people with special needs.',
      ],
    },
    'Personal, Community and Environmental Health': {
      subtopics: [
        'Personal Health',
        'Meaning and importance of personal health',
        'Meaning of personal health',
        'Importance of personal health',
        'Personal Hygiene –care of various body parts (teeth, mouth, hair, skin, hands and nails)',
        'Method of promotion and maintenance of personal health –exercise, nutrition, regular medical check-up;',
        'Personal health screening',
        'Eye defects and their corrections –myopia, hypermetropia, astigmatism.',
        'Auditory defects and their corrections (Otistis media, partial deafness)',
        'Dental diseases (dental caries, gingivitis)',
        'Community Health',
        'Community health services –providers of health services (orthodox services, traditional services –bone setters, birth attendance)',
        'Various aspects of family health –maternal and child health (ante-natal care, immunization, oral rehydration therapy, breast feeding and safe motherhood).',
        'Aging and death education',
        'Characteristics of elderly persons',
        'Ways of relating with the elderly',
        'Common causes of death',
      ],
      objectives: [
        'define personal health and state its importance;',
        'differentiate the care of various parts of the body;',
        'state the methods of promoting and maintaining personal health;',
        'state the outcome of personal health screening for the eye; ear and dental.',
        'differentiate between orthodox and traditional health services;',
        'different among various aspects of maternal and child health services;',
        'identify the characteristics of elderly persons and state the ways of relating with them;',
        'identify common causes of death.',
      ],
    },
    'Communicable and Non-Communicable Diseases': {
      subtopics: [
        'Disease – Meaning and causes',
        'Communicable diseases',
        'Definition',
        'Classification of communicable diseases',
        'Air-borne/Respiratory diseases –measles, whooping cough, poliomyelitis, tuberculosis and cerebro-spinal meningitis;',
        'Water/Food-borne diseases –dysentery, cholera, typhoid fever;',
        'Insect-borne diseases –malaria, yellow fever, trypanosomiasis;',
        'Worm infections –ascaris lumblicoides (tape worm), ancylastomaduodenale (hook worm), dracunculusmedinensis (guinea worm);',
        'Animal-borne diseases –rabies, leptospirosis;',
        'Contact diseases –gonorrhoea, syphilis, taeniacapitis (ring worm), leprosy, Acquired Immune Deficiency Syndrome (AIDS)',
        'Environmental health',
        'Housing',
        'Characteristics of good housing –location, ventilation, lighting and sanitation',
        'Town planning regulations (spacing, overcrowding)',
        'Water Supply',
        'Importance and sources',
        'Methods of purification',
        'Waste disposal',
        'Types –refuge, sewage',
        'Methods',
        'Pollution',
        'Meaning and types –air, water, soil and noise',
        'Prevention and control',
        'Pest and vector control',
        'Differences between pest and vector and their habits',
        'Harmful effects of pest and vector',
        'Prevention and control',
        'Non-communicable diseases',
        'Definition',
        'Diseases –hypertension, sickle cell, cancer, epilepsy, ulcer, asthma, diabetes.',
      ],
      objectives: [
        'define disease and state the causes;',
        'define communicable disease and state its classification with examples;',
        'highlight the prevention and control measures of communicable diseases.',
        'state the characteristics of good housing;',
        'state the town planning regulations;',
        'state the importance of water supply and list the sources;',
        'explain methods of water purification',
        'differentiate between refuse and sewage disposal methods;',
        'define pollution and state its types',
        'Outline the prevention and control measure of pollution;',
        'Differentiate between pest and vector and state their habits;',
        'Explain the harmful effects of pest and vectors and highlight their prevention and control measures.',
        'define non-communicable diseases with examples;',
        'highlight the prevention and control measures of non-communicable diseases.',
      ],
    },
    'Family Life and Human Sexuality Education': {
      subtopics: [
        'Family',
        'Definition and types',
        'Definition',
        'Types –Nuclear family (monogamous, polygamous, single parent family, family by adoption) and Extended family.',
        'Characteristics of a happy family',
        'Human sexuality education',
        'Meaning and importance',
        'Reproductive health rights –rights to number of children, consent to marry, gender equality and privacy.',
        'Family planning',
        'Definition and importance',
        'Advantages and disadvantages of various methods of family planning –condom, pills, uterine device, abstinence.',
        'Challenges of families in Nigeria –pre-marital sex, extra marital sex, widowhood.',
        'Agencies promoting healthy family living –school, NGO, religions homes.',
      ],
      objectives: [
        'define the family and explain its types;',
        'state the characteristics of a happy family;',
        'explain human sexuality and state its importance;',
        'highlight the reproductive health rights;',
        'define family planning and state its importance;',
        'identify the various methods of family planning and state their advantages;',
        'state the challenges facing family life;',
        'identify agencies promoting healthy family living.',
      ],
    },
  },
} as const

export type PhysicalHealthEducationTopic =
  keyof typeof PHYSICAL_HEALTH_EDUCATION_CONFIG.topics