export const PHYSICS_CONFIG = {
  name: 'Physics',
  prefix: 'PHY',
  category: 'science',
  priority: 5,
  totalQuestions: 40,
  topics: {
    'Measurements and Units': {
      subtopics: [
        'Length, area and volume',
        'Metre rule',
        'Venier calipers',
        'Micrometer Screw-guage',
        'measuring cylinder',
        'Mass',
        'unit of mass',
        'use of simple beam balance',
        'concept of beam balance',
        'Time',
        'unit of time',
        'time-measuring devices',
        'Fundamental physical quantities',
        'Derived physical quantities and their units',
        'Combinations of fundamental quantities and determination of their units',
        'Dimensions',
        'definition of dimensions',
        'simple examples',
        'Limitations of experimental measurements',
        'accuracy of measuring instruments',
        'simple estimation of errors',
        'significant figures',
        'standard form',
        'Measurement, position, distance and displacement',
        'concept of displacement',
        'distinction between distance and displacement',
        'concept of position and coordinates',
        'frame of reference',
      ],
      objectives: [
        'identify the units of length, area and volume;',
        'use different measuring instruments;',
        'determine the lengths, surface areas and volume of regular and irregular bodies;',
        'identify the unit of mass;',
        'use simple beam balance, e.g Buchart’s balance and chemical balance;',
        'identify the unit of time;',
        'use different time-measuring devices;',
        'relate the fundamental physical quantities to their units;',
        'deduce the units of derived physical quantities;',
        'determine the dimensions of physical quantities;',
        'use the dimensions to determine the units of physical quantities;',
        'test the homogeneity of an equation;',
        'determine the accuracy of measuring instruments;',
        'estimate simple errors;',
        'express measurements in standard form.',
        'use strings, meter ruler and engineering calipers, vernier calipers and micrometer, screw guage;',
        'note the degree of accuracy;',
        'identify distance travel in a specified direction;',
        'use compass and protractor to locate points/directions;',
        'use Cartesians systems to locate positions in x-y plane;',
        'plot graph and draw inference from the graph.',
      ],
    },
    'Scalars and Vectors': {
      subtopics: [
        'definition of scalar and vector quantities',
        'examples of scalar and vector quantities',
        'relative velocity',
        'resolution of vectors into two perpendicular directions including graphical methods of solution',
      ],
      objectives: [
        'distinguish between scalar and vector quantities;',
        'give examples of scalar and vector quantities;',
        'determine the resultant of two or more vectors;',
        'determine relative velocity;',
        'resolve vectors into two perpendicular components;',
        'use graphical methods to solve vector problems.',
      ],
    },
    'Motion': {
      subtopics: [
        'Types of motion',
        'translational',
        'oscillatory',
        'rotational',
        'spin',
        'random',
        'Relative motion',
        'Causes of motion',
        'Types of force',
        'contact',
        'force field',
        'linear motion',
        'speed, velocity and acceleration',
        'equations of uniformly accelerated motion',
        'motion under gravity',
        'distance-time graph and velocity time graph',
        'instantaneous velocity and acceleration',
        'Projectiles',
        'calculation of range, maximum height and time of flight from the ground and a height',
        'applications of projectile motion',
        'Newton’s laws of motion',
        'inertia, mass and force',
        'relationship between mass and acceleration',
        'impulse and momentum',
        'force – time graph',
        'conservation of linear momentum',
        'Motion in a circle',
        'angular velocity and angular acceleration',
        'centripetal and centrifugal forces',
        'applications',
        'Simple Harmonic Motion (S.H.M)',
        'definition and explanation of simple harmonic motion',
        'examples of systems that execute S.H.M',
        'period, frequency and amplitude of S.H.M',
        'velocity and acceleration of S.H.M',
        'simple treatment of energy change in S.H.M',
        'force vibration and resonance (simple treatment)',
      ],
      objectives: [
        'identify different types of motion;',
        'solve numerical problem on collinear motion;',
        'identify force as cause of motion;',
        'identify push and pull as forms of force;',
        'identify electric and magnetic attractions, gravitational pull as forms of field forces;',
        'differentiate between speed, velocity and acceleration;',
        'deduce equations of uniformly accelerated motion;',
        'solve problems of motion under gravity;',
        'interpret distance-time graph and velocity-time graph;',
        'compute instantaneous velocity and acceleration;',
        'establish expressions for the range, maximum height and time of flight of projectiles, rockets, missiles',
        'solve problems involving projectile motion;',
        'solve numerical problems involving impulse and momentum;',
        'interpretation of area under force – time graph;',
        'interpret Newton’s laws of motion;',
        'compare inertia, mass and force;',
        'deduce the relationship between mass and acceleration;',
        'interpret the law of conservation of linear momentum and application;',
        'establish expression for angular velocity, angular acceleration and centripetal force;',
        'solve numerical problems involving motion in a circle;',
        'establish the relationship between period and frequency;',
        'analyse the energy changes occurring during S.H.M;',
        'identify different types of forced vibration;',
        'enumerate applications of resonance.',
      ],
    },
    'Gravitational field': {
      subtopics: [
        'Newton’s law of universal gravitation',
        'gravitational potential',
        'conservative and non-conservative fields',
        'acceleration due to gravity',
        'variation of g on the earth’s surface',
        'distinction between mass and weight escape velocity',
        'parking orbit and weightlessness',
      ],
      objectives: [
        'identify the expression for gravitational force between two bodies;',
        'apply Newton’s law of universal gravitation;',
        'give examples of conservative and non-conservative fields;',
        'deduce the expression for gravitational field potentials;',
        'identify the causes of variation of g on the earth’s surface;',
        'differentiate between mass and weight;',
        'determine escape velocity.',
      ],
    },
    'Equilibrium of Forces': {
      subtopics: [
        'equilibrium of particles',
        'equilibrium of coplanar forces',
        'triangles and polygon of forces',
        'Lami’s theorem',
        'principles of moments',
        'moment of a force',
        'simple treatment and moment of a couple (torque)',
        'applications',
        'conditions for equilibrium of rigid bodies under the action of parallel and non-parallel forces',
        'resolution and composition of forces in two perpendicular directions',
        'resultant and equilibrant',
        'centre of gravity and stability',
        'stable, unstable and neutral equilibra',
      ],
      objectives: [
        'apply the conditions for the equilibrium of coplanar forces to solve problems;',
        'use triangle and polygon laws of forces to solve equilibrium problems;',
        'use Lami’s theorem to solve problems;',
        'analyse the principle of moment of a force;',
        'determine moment of a force and couple;',
        'describe some applications of moment of a force and couple;',
        'apply the conditions for the equilibrium of rigid bodies to solve problems;',
        'resolve forces into two perpendicular directions;',
        'determine the resultant and equilibrant of forces;',
        'differentiate between stable, unstable and neutral equilibra.',
      ],
    },
    'Work, Energy and Power': {
      subtopics: [
        'definition of work, energy and power',
        'forms of energy',
        'conservation of energy',
        'qualitative treatment between different forms of energy',
        'interpretation of area under the force-distance curve',
      ],
      objectives: [
        'differentiate between work, energy and power;',
        'compare different forms of energy, giving examples;',
        'apply the principle of conservation of energy;',
        'examine the transformation between different forms of energy;',
        'interpret the area under the force – distance curve.',
        'solve numerical problems in work, energy and power.',
      ],
    },
    'Energy and society': {
      subtopics: [
        'sources of energy',
        'renewable and non-renewable energy e.g. coal, crude oil, sun, wind etc.',
        'uses of energy',
        'energy and development',
        'energy diversification',
        'environmental impact of energy e.g. global warming, greenhouse effect and spillage',
        'energy crises',
        'conversion of energy',
        'devices used in energy production',
      ],
      objectives: [
        'itemize the sources of energy;',
        'distinguish between renewable and non-renewable energy, examples should be given;',
        'identify methods of energy transition;',
        'explain the importance of energy in the development of the society;',
        'analyze the effect of energy use to the environment;',
        'identify the impact of energy on the environment;',
        'identify energy sources that are friendly or hazardous to the environment;',
        'identify energy uses in their immediate environment;',
        'suggests ways of safe energy use',
        'state different forms of energy conversion.',
      ],
    },
    'Dams and energy production': {
      subtopics: [
        'location of dams',
        'energy production',
      ],
      objectives: [],
    },
    'nuclear energy': {
      subtopics: [],
      objectives: [],
    },
    'solar energy': {
      subtopics: [
        'solar collector',
        'solar panel for energy supply',
      ],
      objectives: [],
    },
    'Friction': {
      subtopics: [
        'static and dynamic friction',
        'coefficient of limiting friction and its determination',
        'advantages and disadvantages of friction',
        'reduction of friction',
        'qualitative treatment of viscosity and terminal velocity',
        'Stoke’s law',
      ],
      objectives: [
        'differentiate between static and dynamic friction;',
        'determine the coefficient of limiting friction;',
        'compare the advantages and disadvantages of friction;',
        'suggest ways by which friction can be reduced;',
        'analyse factors that affect viscosity and terminal velocity;',
        'apply Stoke’s law.',
      ],
    },
    'Simple Machines': {
      subtopics: [
        'definition of simple machines',
        'types of machines',
        'mechanical advantage, velocity ratio and efficiency of machines',
      ],
      objectives: [
        'identify different types of simple machines;',
        'solve problems involving simple machines.',
      ],
    },
    'Elasticity: Hooke’s Law and Young’s Modulus': {
      subtopics: [
        'elastic limit, yield point, breaking point, Hooke’s law and Young’s modulus',
        'the spring balance as a device for measuring force',
        'work done per unit volume in springs and elastic strings',
      ],
      objectives: [
        'interpret force-extension curves;',
        'interpret Hooke’s law and Young’s modulus of a material;',
        'use spring balance to measure force;',
        'determine the work done in spring and elastic strings.',
      ],
    },
    'Pressure': {
      subtopics: [
        'Atmospheric Pressure',
        'definition of atmospheric pressure',
        'units of pressure (S.I) units (Pa)',
        'measurement of pressure',
        'simple mercury barometer',
        'aneroid barometer and manometer',
        'variation of pressure with height',
        'the use of barometer as an altimeter',
        'Pressure in liquids',
        'the relationship between pressure, depth and density (P = gh)',
        'transmission of pressure in liquids (Pascal’s Principle)',
        'application',
      ],
      objectives: [
        'recognize the S.I units of pressure (Pa);',
        'identify pressure measuring instruments;',
        'relate the variation of pressure to height;',
        'use a barometer as an altimeter;',
        'determine the relationship between pressure depth and density;',
        'apply the principle of transmission of pressure in liquids to solve problems;',
        'determine and apply the principle of pressure in liquid.',
      ],
    },
    'Liquids At Rest': {
      subtopics: [
        'determination of density of solids and liquids',
        'definition of relative density',
        'upthrust on a body immersed in a liquid',
        'Archimedes’ principle and law of floatation and applications, e.g. ships and hydrometers',
      ],
      objectives: [
        'distinguish between density and relative density of substances;',
        'determine the upthrust on a body immersed in a liquid;',
        'apply Archimedes’ principle and law of floatation to solve problems.',
      ],
    },
    'Temperature and Its Measurement': {
      subtopics: [
        'concept of temperature',
        'thermometric properties',
        'calibration of thermometers',
        'temperature scales –Celsius and Kelvin',
        'types of thermometers',
        'conversion from one scale of temperature to another',
      ],
      objectives: [
        'identify thermometric properties of materials that are used for different thermometers;',
        'calibrate thermometers;',
        'differentiate between temperature scales e.g. Celsius, Faranheight and Kelvin;',
        'compare the types of thermometers;',
        'convert from one scale of temperature to another.',
      ],
    },
    'Thermal Expansion': {
      subtopics: [
        'Solids',
        'definition and determination of linear, volume and area expansivities',
        'effects and applications, e.g. expansion in building strips and railway lines',
        'relationship between different expansivities',
        'Liquids',
        'volume expansivity',
        'real and apparent expansivities',
        'determination of volume expansivity',
        'anomalous expansion of water',
      ],
      objectives: [
        'determine linear and volume expansivities;',
        'assess the effects and applications of thermal expansivities;',
        'determine the relationship between different expansivities;',
        'determine volume, apparent, and real expansivities of liquids;',
        'analyse the anomalous expansion of water.',
      ],
    },
    'Gas Laws': {
      subtopics: [
        'Boyle’s law (isothermal process)',
        'Charle’s law (isobaric process)',
        'Pressure law (volumetric process)',
        'absolute zero of temperature',
        'general gas equation',
        'ideal gas equation',
        'Van der waal gas',
      ],
      objectives: [
        'interpret the gas laws;',
        'use expression of these laws to solve numerical problems;',
        'interpret Van der waal equation for one mole of a real gas.',
      ],
    },
    'Quantity of Heat': {
      subtopics: [
        'heat as a form of energy',
        'definition of heat capacity and specific heat capacity of solids and liquids',
        'determination of heat capacity and specific heat capacity of substances by simple methods e.g. method of mixtures and electrical method and Newton’s law of cooling',
      ],
      objectives: [
        'differentiate between heat capacity and specific heat capacity;',
        'determine heat capacity and specific heat capacity using simple methods;',
        'solve numerical problems.',
      ],
    },
    'Change of State': {
      subtopics: [
        'latent heat',
        'specific latent heats of fusion and vaporization',
        'melting, evaporation and boiling',
        'the influence of pressure and of dissolved substances on boiling and melting points',
        'application in appliances',
      ],
      objectives: [
        'differentiate between latent heat and specific latent heats of fusion and vaporization;',
        'differentiate between melting, evaporation and boiling;',
        'examine the effects of pressure and of dissolved substance on boiling and melting points.',
        'solve numerical problems.',
      ],
    },
    'Vapours': {
      subtopics: [
        'unsaturated and saturated vapours',
        'relationship between saturated vapour pressure (S.V.P) and boiling',
        'determination of S.V.P by barometer tube method',
        'formation of dew, mist, fog, clouds and rain',
        'study of dew point, humidity and relative humidity',
        'hygrometry; estimation of the humidity of the atmosphere using wet and dry bulb hygrometers',
      ],
      objectives: [
        'distinguish between saturated and unsaturated vapours;',
        'relate saturated vapour pressure to boiling point;',
        'determine S.V.P by barometer tube method;',
        'differentiate between dew point, humidity and relative humidity;',
        'estimate the humidity of the atmosphere using wet and dry bulb hygrometers;',
        'solve numerical problems.',
      ],
    },
    'Structure of Matter and Kinetic Theory': {
      subtopics: [
        'Molecular nature of matter',
        'atoms and molecules',
        'molecular theory: explanation of Brownian motion, diffusion, surface tension, capillarity, adhesion, cohesion and angles of contact law of definite proportion',
        'examples and applications',
        'Kinetic Theory',
        'assumptions of the kinetic theory',
        'using the theory to explain the pressure exerted by gas, Boyle’s law, Charles’ law, melting, boiling, vapourization, change in temperature, evaporation, etc.',
      ],
      objectives: [
        'differentiate between atoms and molecules;',
        'use molecular theory to explain Brownian motion, diffusion, surface, tension, capillarity, adhesion, cohesion and angle of contact;',
        'examine the assumptions of kinetic theory;',
        'interpret kinetic theory, the pressure exerted by gases, Boyle’s law, Charles’s law, melting, boiling, vaporization, change in temperature, evaporation, etc.',
      ],
    },
    'Heat Transfer': {
      subtopics: [
        'conduction, convection and radiation as modes of heat transfer',
        'temperature gradient, thermal conductivity and heat flux',
        'effect of the nature of the surface on the energy radiated and absorbed by it',
        'the conductivities of common materials',
        'the thermos flask and vacuum flask',
        'land and sea breeze',
        'combustion engine',
      ],
      objectives: [
        'differentiate between conduction, convection and radiation as modes of heat transfer;',
        'solve problems on temperature gradient, thermal conductivity and heat flux;',
        'assess the effect of the nature of the surface on the energy radiated and absorbed by it;',
        'compare the conductivities of common materials;',
        'relate the component part of the working of the thermos flask;',
        'differentiate between land and sea breeze;',
        'analyse the principles of operating internal combustion jet engines, rockets.',
      ],
    },
    'Waves': {
      subtopics: [
        'Production and Propagation',
        'wave motion',
        'vibrating systems as source of waves',
        'waves as mode of energy transfer',
        'distinction between particle motion and wave motion',
        'relationship between frequency, wavelength and wave velocity (V=f λ)',
        'phase difference, wave number and wave vector',
        'progressive wave equation',
        'Classification',
        'types of waves; mechanical and electromagnetic waves',
        'longitudinal and transverse waves',
        'stationary and progressive waves',
        'examples of waves from springs, ropes, stretched strings and the ripple tank',
        'Characteristics/Properties',
        'reflection, refraction, diffraction and plane polarization',
        'superposition of waves e.g. interference',
        'Beats',
        'Doppler effects (qualitative treatment only)',
      ],
      objectives: [
        'interpret wave motion;',
        'identify vibrating systems as sources of waves;',
        'use waves as a mode of energy transfer;',
        'distinguish between particle motion and wave motion;',
        'relate frequency and wave length to wave velocity;',
        'determine phase difference, wave number and wave vector;',
        'use the progressive wave equation to compute basic wave parameters;',
        'differentiate between mechanical and electromagnetic waves;',
        'differentiate between longitudinal and transverse waves;',
        'distinguish between stationary and progressive waves;',
        'indicate the example of waves generated from springs, ropes, stretched strings and the ripple tank;',
        'differentiate between reflection, refraction, diffraction and plane polarization of waves;',
        'analyse the principle of superposition of waves;',
        'solve numerical problems on waves explain the phenomenon of beat, beat frequency and uses;',
        'explain Doppler effect of sound and application',
      ],
    },
    'Propagation of Sound Waves': {
      subtopics: [
        'the necessity for a material medium',
        'speed of sound in solids, liquids and air',
        'reflection of sound; echoes, reverberation and their applications',
        'advantages and disadvantages of echoes and reverberations',
      ],
      objectives: [
        'determine the need for a material medium in the propagation of sound waves;',
        'compare the speed of sound in solids, liquids and air;',
        'relate the effects of temperature and pressure to the speed of sound in air;',
        'solve problem on echoes, reverberation and speed;',
        'compare the disadvantages and advantages of echoes.',
        'solve problems on echo, reverberation and speed of sound.',
      ],
    },
    'Characteristics of Sound Waves': {
      subtopics: [
        'noise and musical notes',
        'quality, pitch, intensity and loudness and their application to musical instruments',
        'simple treatment of harmonics and overtones produced by vibrating strings and their columns',
        'acoustic examples of resonance',
        'frequency of a note emitted by air columns in closed and open pipes in relation to their lengths',
      ],
      objectives: [
        'differentiate between noise and musical notes;',
        'analyse quality, pitch, intensity and loudness of sound notes;',
        'evaluate the application of (ii) above in the construction of musical instruments;',
        'identify overtones by vibrating stings and air columns;',
        'itemize acoustical examples of resonance;',
        'determine the frequencies of notes emitted by air columns in open and closed pipes in relation to their lengths.',
      ],
    },
    'Light Energy': {
      subtopics: [
        'Sources of Light',
        'natural and artificial sources of light',
        'luminous and non-luminous objects',
        'Propagation of light',
        'speed, frequency and wavelength of light',
        'formation of shadows and eclipse',
        'the pin-hole camera',
      ],
      objectives: [
        'compare the natural and artificial sources of light;',
        'differentiate between luminous and non-luminous objects;',
        'relate the speed, frequency and wavelength of light;',
        'interpret the formation of shadows and eclipses;',
        'solve problems using the principle of operation of a pin-hole camera.',
      ],
    },
    'Reflection of Light at Plane and Curved Surfaces': {
      subtopics: [
        'laws of reflection',
        'application of reflection of light',
        'formation of images by plane, concave and convex mirrors and ray diagrams',
        'use of the mirror formula',
        'linear and angular magnification',
      ],
      objectives: [
        'interpret the laws of reflection;',
        'illustrate the formation of images by plane, concave and convex mirrors;',
        'apply the mirror formula to solve optical problems;',
        'determine the linear magnification;',
        'apply the laws of reflection of light to the working of periscope, kaleidoscope and the sextant.',
      ],
    },
    'Refraction of Light Through at Plane and Curved Surfaces': {
      subtopics: [
        'explanation of refraction in terms of velocity of light in the media',
        'laws of refraction',
        'definition of refractive index of a medium',
        'determination of refractive index of glass and liquid using Snell’s law',
        'real and apparent depth and lateral displacement',
        'critical angle and total internal reflection',
        'Glass Prism',
        'use of the minimum deviation formula',
        'type of lenses: triangular, rectangular etc',
        'use of lens formula',
        'magnification',
      ],
      objectives: [
        'interpret the laws of reflection;',
        'determine the refractive index of glass and liquid using Snell’s law;',
        'determine the refractive index using the principle of real and apparent depth;',
        'determine the conditions necessary for total internal reflection;',
        'examine the use of periscope, prism, binoculars, optical fibre;',
        'apply the principles of total internal reflection to the formation of mirage;',
        'use of lens formula and ray diagrams to solve optical numerical problems;',
        'determine the magnification of an image;',
        'calculate the refractive index of a glass prism using minimum deviation formula.',
      ],
    },
    'Optical Instruments': {
      subtopics: [
        'general principles of microscopes, telescopes, projectors, cameras and the human eye (physiological details of the eye are not required)',
        'power of a lens',
        'angular magnification',
        'near and far points',
        'sight defects and their corrections',
      ],
      objectives: [
        'apply the principles of operation of optical instruments to solve problems;',
        'distinguish between the human eye and the cameras;',
        'calculate the power of a lens;',
        'evaluate the angular magnification of optical instruments;',
        'determine the near and far points;',
        'detect sight defects and their corrections.',
      ],
    },
    'Dispersion of light and colours': {
      subtopics: [
        'dispersion of white light by a triangular Prism',
        'production of pure spectrum',
        'colour mixing by addition and subtraction',
        'colour of objects and colour filters',
        'rainbow and formation',
      ],
      objectives: [
        'identify primary colours and obtain secondary colours by mixing;',
        'understand the formation of rainbow;',
        'deduce why objects have colours;',
        'relate the expression for gravitational force between two bodies;',
        'apply Newton’s law of universal gravitation;',
        'analyse colours using colour filters;',
      ],
    },
    'Electromagnetic spectrum': {
      subtopics: [
        'description of sources and uses of various types of radiation',
      ],
      objectives: [
        'analyse the electromagnetic spectrum in relation to their wavelengths, sources, detection and uses.',
      ],
    },
    'Electrostatics': {
      subtopics: [
        'existence of positive and negative charges in matter',
        'charging a body by friction, contact and induction',
        'electroscope',
        'Coulomb’s inverse square law, electric field and potential',
        'electric field intensity potential and potential difference',
        'electric discharge and lightning',
      ],
      objectives: [
        'identify charges;',
        'examine uses of an electroscope;',
        'apply Coulomb’s square law of electrostatics to solve problems;',
        'deduce expressions for electric field intensity and potential difference;',
        'identify electric field flux patterns of isolated and interacting charges;',
        'analyse the distribution of charges on a conductor and how it is used in lightening conductors.',
      ],
    },
    'Capacitors': {
      subtopics: [
        'types and functions of capacitors',
        'parallel plate capacitors',
        'capacitance of a capacitor',
        'the relationship between capacitance, area separation of plates and medium between the plates',
        'capacitors in series and parallel',
        'energy stored in a capacitor',
      ],
      objectives: [
        'determine uses of capacitors;',
        'analyse parallel plate capacitors;',
        'determine the capacitance of a capacitor;',
        'analyse the factors that affect the capacitance of a capacitor;',
        'solve problems involving the arrangement of a capacitor;',
        'determine the energy stored in capacitors.',
      ],
    },
    'Electric Cells': {
      subtopics: [
        'simple voltaic cell and its defects',
        'Daniel cell, Leclanche cell (wet and dry)',
        'lead –acid accumulator and Nickel-Iron (Nife) Lithium lon and Mercury cadmium',
        'maintenance of cells and batteries (detail treatment of the chemistry of a cell is not required)',
        'arrangement of cells',
        'efficiency of a cell',
      ],
      objectives: [
        'identify the defects of the simple voltaic cell and their correction;',
        'compare different types of cells including solar cell;',
        'compare the advantages of lead-acid and Nikel iron accumulator;',
        'solve problems involving series and parallel combination of cells.',
      ],
    },
    'Current Electricity': {
      subtopics: [
        'electromagnetic force (emf), potential difference (p.d.), current, internal resistance of a cell and lost Volt',
        'Ohm’s law, resistivity and conductivity',
        'measurement of resistance',
        'meter bridge',
        'resistance in series and in parallel and their combination',
        'the potentiometer method of measuring emf, current and internal resistance of a cell',
        'electrical networks',
      ],
      objectives: [
        'differentiate between emf, p.d., current and internal resistant of a cell;',
        'apply Ohm’s law to solve problems;',
        'use metre bridge to calculate resistance;',
        'compute effective total resistance of both parallel and series arrangement of resistors;',
        'determine the resistivity and the conductivity of a conductor;',
        'measure emf. current and internal resistance of a cell using the potentiometer;',
        'identify the advantages of the potentiometer;',
        'apply Kirchoff’s law in electrical networks.',
      ],
    },
    'Electrical Energy and Power': {
      subtopics: [
        'concepts of electrical energy and power',
        'commercial unit of electric energy and power',
        'electric power transmission',
        'heating effects of electric current',
        'electrical wiring of houses',
        'use of fuses',
      ],
      objectives: [
        'apply the expressions of electrical energy and power to solve problems;',
        'analyse how power is transmitted from the power station to the consumer;',
        'identify the heating effects of current and its uses;',
        'identify the advantages of parallel arrangement over series;',
        'determine the fuse rating.',
      ],
    },
    'Magnets and Magnetic Fields': {
      subtopics: [
        'natural and artificial magnets',
        'magnetic properties of soft iron and steel',
        'methods of making magnets and demagnetization',
        'concept of magnetic field',
        'magnetic field of a permanent magnet',
        'magnetic field round a straight current carrying conductor, circular wire and solenoid',
        'properties of the earth’s magnetic field; north and south poles, magnetic meridian and angle of dip and declination',
        'flux and flux density',
        'variation of magnetic field intensity over the earth’s surface',
        'applications: earth’s magnetic field in navigation and mineral exploration',
      ],
      objectives: [
        'give examples of natural and artificial magnets;',
        'differentiate between the magnetic properties of soft iron and steel;',
        'identify the various methods of making magnets and demagnetizing magnets;',
        'describe how to keep a magnet from losing its magnetism;',
        'determine the flux pattern exhibited when two magnets are placed together pole to pole;',
        'determine the flux of a current carrying conductor, circular wire and solenoid including the polarity of the solenoid;',
        'determine the flux pattern of a magnet placed in the earth’s magnetic fields;',
        'identify the magnetic elements of the earth’s flux;',
        'determine the variation of earth’s magnetic field on the earth’s surface;',
        'examine the applications of the earth’s magnetic field.',
      ],
    },
    'Force on a Current-Carrying Conductor in a Magnetic Field': {
      subtopics: [
        'quantitative treatment of force between two parallel current-carrying conductors',
        'force on a charge moving in a magnetic field',
        'the d. c. motor',
        'electromagnets',
        'carbon microphone',
        'moving coil and moving iron instruments',
        'conversion of galvanometers to ammeters and voltmeter using shunts and multipliers',
        'sensitivity of a galvanometer',
      ],
      objectives: [
        'determine the direction of force on a current carrying conductor using Fleming’s left-hand rule;',
        'interpret the attractive and repulsive forces between two parallel current-carrying conductors using diagrams;',
        'determine the relationship between the force, magnetic field strength, velocity and the angle through which the charge enters the field;',
        'interpret the working of the d. c. motor;',
        'analyse the principle of electromagnets and give examples of its application;',
        'compare moving iron and moving coil instruments;',
        'convert a galvanometer into an ammeter or a voltmeter;',
        'identify the factors affecting the sensitivity of a galvanometer.',
      ],
    },
    'Electromagnetic Induction': {
      subtopics: [
        'Faraday’s laws of electromagnetic induction',
        'factors affecting induced emf',
        'Lenz’s law as an illustration of the principle of conservation of energy',
        'a.c. and d.c generators',
        'transformers',
        'the induction coil',
      ],
      objectives: [
        'interpret the laws of electromagnetic induction;',
        'identify factors affecting induced emf;',
        'recognize how Lenz’s law illustrates the principle of conservation of energy;',
        'interpret the diagrammatic set up of A. C. generators;',
        'identify the types of transformer;',
        'examine principles of operation of transformers;',
        'assess the functions of an induction coil;',
        'draw some conclusions from the principles of operation of an induction coil;',
      ],
    },
    'Inductance': {
      subtopics: [
        'explanation of inductance',
        'unit of inductance',
        'energy stored in an inductor',
        'application/uses of inductors',
      ],
      objectives: [
        'interpret the inductance of an inductor;',
        'recognize units of inductance;',
        'calculate the effective total inductance in series and parallel arrangement;',
        'deduce the expression for the energy stored in an inductor;',
        'examine the applications of inductors;',
      ],
    },
    'Eddy Current': {
      subtopics: [
        'reduction of eddy current',
        'applications of eddy current',
      ],
      objectives: [
        'describe the method by which eddy current losses can be reduced;',
        'determine ways by which eddy currents can be used.',
      ],
    },
    'Simple A. C. Circuits': {
      subtopics: [
        'explanation of a.c. current and voltage',
        'peak and r.m.s. values',
        'a.c. source connected to a resistor',
        'a.c source connected to a capacitor-(capacitive reactance)',
        'a.c source connected to an inductor (inductive reactance)',
        'R-L-C circuits',
        'vector diagram, phase angle and power factor',
        'resistance and impedance',
        'effective voltage in an R-L-C circuits',
        'resonance and resonance frequency',
      ],
      objectives: [
        'identify a.c. current and d.c. voltage;',
        'differentiate between the peak and r.m.s. values of a.c.;',
        'determine the phase difference between current and voltage;',
        'interpret R-L-C circuits;',
        'analyse vector diagrams;',
        'calculate the effective voltage, reactance and impedance;',
        'recognize the condition by which the circuit is at resonance;',
        'determine the resonant frequency of R-L-C arrangement;',
        'determine the instantaneous power, average power and the power factor in a. c. circuits.',
      ],
    },
    'Conduction of Electricity Through liquids': {
      subtopics: [
        'electrolytes and non-electrolyte',
        'concept of electrolysis',
        'Faraday’s laws of electrolysis',
        'application of electrolysis, e.g. electroplating, calibration of ammeter etc.',
      ],
      objectives: [
        'distinguish between electrolytes and non-electrolytes;',
        'analyse the processes of electrolysis;',
        'apply Faraday’s laws of electrolysis to solve problems;',
      ],
    },
    'Conduction of Electricity Through gases': {
      subtopics: [
        'discharge through gases (qualitative treatment only)',
        'application of conduction of electricity through gases',
      ],
      objectives: [
        'analyse discharge through gases;',
        'determine some applications/uses of conduction of electricity through gases.',
      ],
    },
    'Elementary Modern Physics-Bohr’s Theory': {
      subtopics: [
        'models of the atom and their limitations',
        'elementary structure of the atom',
        'energy levels and spectra',
        'thermionic and photoelectric emissions',
        'Einstein’s equation and stopping potential',
        'applications of thermionic emissions and photoelectric effects',
        'simple method of production of x-rays',
        'properties and applications of alpha, beta and gamma rays',
        'half-life and decay constant',
        'simple ideas of production of energy by fusion and fission',
        'binding energy, mass defect and Einstein’s Energy equation',
        'wave-particle (duality of matter)',
        'electron diffraction',
        'the uncertainty principle',
      ],
      objectives: [
        'identify the models of the atom and write their limitations;',
        'describe elementary structure of the atom;',
        'differentiate between the energy levels and spectra of atoms;',
        'compare thermionic emission and photoelectric emission;',
        'apply Einstein’s equation to solve problems of photoelectric effect;',
        'calculate the stopping potential;',
        'relate some application of thermionic emission and photoelectric effects;',
        'interpret the process involved in the production of x-rays;',
        'identify some properties and applications of x-rays;',
        'analyse elementary radioactivity;',
        'distinguish between stable and unstable nuclei;',
        'identify isotopes of an element;',
        'compare the properties of alpha, beta and gamma rays;',
        'relate half-life and decay constant of a radioactive element;',
        'determine the binding energy, mass defect and Einstein’s energy equation;',
        'analyse wave particle duality;',
        'solve some numerical problems based on the uncertainty principle and wave – particle duality.',
      ],
    },
    'Introductory Electronics': {
      subtopics: [
        'distinction between metals, semiconductors and insulators (elementary knowledge of band gap is required)',
        'intrinsic and extrinsic semiconductors (n-type and p-type semiconductors)',
        'uses of semiconductors and diodes in rectification and transistors in amplification',
        'elementary knowledge of diodes and transistors',
      ],
      objectives: [
        'differentiate between conductors, semi-conductors and insulators;',
        'distinguish between intrinsic and extrinsic semiconductors (n-type and p-type semiconductors);',
        'distinguish between electron and hole carriers;',
        'analyse diodes and transistor',
        'relate diodes to rectification and transistor to amplification.',
      ],
    },
  },
} as const

export type PhysicsTopic = keyof typeof PHYSICS_CONFIG.topics