export const YORUBA_CONFIG = {
  name: 'Yorùbá',
  prefix: 'YOR',
  category: 'arts',
  priority: 14,
  totalQuestions: 40,
  topics: {
    'LANGUAGE': {
      subtopics: [
        'Comprehension',
        'Prose',
        'Verse',
        'Essay Writing',
        'Argumentative',
        'Descriptive',
        'Narrative',
        'Letter Writing (Formal and Informal) etc.',
        'Sound System',
        'Production of sounds (consonants and vowels)',
        'Tones and tone change',
        'Syllable structure',
        'Sound processes - co-vowel occurrence, elision, deletion, etc.',
        'Grammar',
        'Morphology – Word-formation',
        'Loan-word integration',
        'Word classes – nouns, verbs, adjectives, adverbs, pronouns, conjunctions, prepositions, etc.',
        'Phrases and clauses – types and functions',
        'Sentences – types, structures and functions',
        'Current Orthography',
        'Translation',
      ],
      objectives: [
        'identify central issues in a passage and draw appropriate conclusions;',
        'determine basic assumptions and express ideas;',
        'identify the meanings and functions of given phrases and sentences.',
        'identify different types of essay; and',
        'apply different types of techniques associated with each type.',
        'identify organs of speech, speech sounds and parameters for describing each speech sound;',
        'determine their correct usages;',
        'detect linguistic errors (pronunciations and wrong usages);',
        'determine the syllable components of words;',
        'demonstrate knowledge of the basic principles underlying the relationship between sounds.',
        'demonstrate good knowledge of word derivation;',
        'demonstrate knowledge of word adoption;',
        'identify the appropriate class a word belongs to;',
        'demonstrate knowledge and understanding of Yorùbá syntax;',
        'identify the types, structures and functions of sentences.',
        'present ideas in acceptable written form.',
        'interpret sentences and ideas in accordance with acceptable principles.',
      ],
    },
    'LITERATURE': {
      subtopics: [
        'Oral Literature',
        'Prose (Ìtàn Àròsọ)',
        'Babalọla, A. (2023). Àkójọpọ̀ Àlọ́ Ìjàpá (Apá Kejì). Ìbàdàn: University Press Plc.',
        'Drama (Eré Oníṣe)',
        'Ògúnniran, L. (2022). Eégún Aláré. Ìbàdàn: Golden Pen Publishers.',
        'Written Literature',
        'Prose (Ìtàn Àròsọ)',
        'Ìṣọ̀la, A. (2023). Ogun Ọmọde. Ìbàdàn: University Press Plc.',
        'Poetry (Ewì)',
        'Àdẹ́wọ̀lé, O. (2023). Èdè Abínibí àti Àwọn Àròfọ̀ Míìrán. Ìbàdàn: University Press Plc.',
        'pp 1-50 (2026)',
        'pp 51-83 (2027)',
        'pp 84-116 (2028)',
        'pp 117-152 (2029)',
        'pp 153-216 (2030)',
        'Drama (Eré Onítàn)',
        'Fádìyà, O. (2023). Ò te Oyè. Ìbàdàn: Genius Books Publishers.',
      ],
      objectives: [
        'identify central issues, problems and the component parts of ideas presented in the work of art;',
        'draw moral lessons from the text;',
        'identify the figurative and idiomatic expressions in the text; and',
        'draw appropriate conclusions.',
        'identify the type of drama;',
        'extract the narrative techniques in the drama;',
        'identify the figurative and idiomatic expressions in the drama;',
        'Identify the central theme of the work; and',
        'Interpret same in accordance with acceptable principles of the society.',
        'demonstrate good knowledge of ideas in the work of art;',
        'draw moral lessons from the text;',
        'identify the narrative techniques in the text; and',
        'identify the figurative and idiomatic expressions in the text.',
        'deduce the import of written works of art and genres; and',
        'identify the figurative and idiomatic expressions in the poem.',
        'identify the central theme of the work;',
        'interpret same in accordance with acceptable principles of the society;',
        'identify types of drama;',
        'identify the figurative and idiomatic expressions in the drama; and',
        'extract the narrative techniques in the drama.',
      ],
    },
    'CULTURE': {
      subtopics: [
        'Èrò àti Ìgbàgbọ́',
        'Olódùmarè, àkùdáàyà, emèrè, àjẹ́, àwọn irúnmọlẹ̀, abbl.',
        'Ètò Ìṣèlú àti Ààbò Ìlú',
        'Ẹgbẹ́ àti ọgbà, oyè jíjẹ àti àwọn ìjoyè, ogun jíjà, abbl.',
        'Ètò Ìsìnkú àti Ogún Pínpín',
        'Òkú àgbà, òkú ọ̀fọ̀, òkú òòṣà, ìtúfọ̀, ilẹ̀ òkú gbígbẹ́, ìdí igi, mọlẹ́bí, bàbá ìsìnkú, abbl.',
        'Òǹkà Yorùbá',
        'Oókan títí dé ọ̀kẹ́ kan (1-20,000).',
        'Ètò Ìgbéyàwó àti Ìsọmọlórúkọ',
        'Gbogbo ohun tó rọ mọ ìgbéyàwó àti ìsọmọlórúkọ.',
        'Ètò Ìwòsàn',
        'Ìtọ́jú aláìsàn, ìtọ́jú àti ìgbẹ̀bí aboyún, abbl.',
        'Eré Ìdárayá',
        'eré òṣùpá – àlọ́, bojúbojù, abbl;',
        'eré ojúmọmọ – ìjàkadì, ayò, òkòtó, àrìn, abbl.',
        'Iṣẹ́ Abínibí àti Oúnjẹ Ilẹ̀ Yorùbá',
        'Iṣẹ́-àgbẹ̀, ìṣọ̀nà, ìlù lílù, abbl;',
        'Oúnjẹ – àbàrí, iyán, ẹ̀wà, abbl.',
        'Ẹ̀kọ́ Ilé',
        'Ìwà ọmọlúàbí àti àǹfààní rẹ̀.',
      ],
      objectives: [
        'distinguish traditional practices and acceptable ways of life from modern and common sense beliefs.',
        'assess the functions and roles of individuals, chieftains, and groups in ensuring peace, stability and continuity of society.',
        'distinguish between traditional practices; and',
        'relate them to funerals and inheritance.',
        'count in Yorùbá numerals; and',
        'apply addition, deduction and division methods in Yorùbá.',
        'relate social activities and events to appropriate situations.',
        'demonstrate knowledge of the best way of using the appropriate health care practices.',
        'identify types of Yorùbá traditional games;',
        'identify rules and regulations guiding each game; and',
        'mention values derived from each game.',
        'demonstrate adequate knowledge of the various traditional professions;',
        'compare various traditional professions;',
        'demonstrate knowledge of preparing each type of Yorùbá food; and',
        'mention nutritional values of each food.',
        'identify acceptable patterns of behaviour and attitude that conform with societal norms and values.',
      ],
    },
  },
} as const

export type YorubaTopic = keyof typeof YORUBA_CONFIG.topics